org/postgresql/test/xa/XADataSourceTest.java, org/postgresql/xa/PGXAConnection.java
Cherry-picked commit 8d743380e8a2e50ea42a0b1b111499461f3694b7 from master:
Fix equals-method of the wrapper returned by PGXAConnection.getConnection()
Patch by Florent Guillaume
=> Backport PGXAConnection.equals() fix from master

build.properties, build.xml, org/postgresql/Driver.java.in, org/postgresql/ds/common/BaseDataSource.java, org/postgresql/osgi/PGBundleActivator.java, org/postgresql/osgi/PGDataSourceFactory.java, org/postgresql/test/jdbc2/DriverTest.java, org/postgresql/test/osgi/OsgiTestSuite.java, org/postgresql/test/osgi/PGDataSourceFactoryTest.java
Added OSGi metadata and expose the driver as a JDBC service using dedicated `DataSourceFactory` of OSGi Enterprise.
This fixes enlarged scope of issue #71 and [a related conversation thread](http://www.postgresql.org/message-id/CAHL_zcPSif+Z7ZcpROYN28LOQA=CWU431fDfHYNbkj2x=_xJTA@mail.gmail.com)
The bundle version is defined in `build.properties` file. We may need to do something more generic concerning version computation so as to keep all versions aligned (maven version, osgi version, ant tokens, ...).
Imported and exported packages are computed automatically using `bnd` tool so as to reduce the maintenance cost of metadatas.
For the need of the bundle activator, the driver is now able to deregister from the driver manager (in case the bundle is stopped/unloaded). In addition to this …
=> Make Pgjdbc an OSGi bundle

org/postgresql/Driver.java.in, org/postgresql/core/Parser.java, org/postgresql/core/Utils.java, org/postgresql/core/v2/ConnectionFactoryImpl.java, org/postgresql/core/v2/SimpleParameterList.java, org/postgresql/core/v2/V2Query.java, org/postgresql/core/v3/CompositeQuery.java, org/postgresql/core/v3/ConnectionFactoryImpl.java, org/postgresql/core/v3/QueryExecutorImpl.java, org/postgresql/core/v3/SimpleParameterList.java, org/postgresql/core/v3/SimpleQuery.java, org/postgresql/geometric/PGpath.java, org/postgresql/geometric/PGpolygon.java, org/postgresql/jdbc2/AbstractJdbc2Array.java, org/postgresql/jdbc2/AbstractJdbc2Connection.java, org/postgresql/jdbc2/AbstractJdbc2DatabaseMetaData.java, org/postgresql/jdbc2/AbstractJdbc2ResultSet.java, org/postgresql/jdbc2/AbstractJdbc2ResultSetMetaData.java, org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/jdbc2/CacheMetadata.java, org/postgresql/jdbc2/EscapedFunctions.java, org/postgresql/jdbc3/AbstractJdbc3Statement.java, org/postgresql/jdbc3/PSQLSavepoint.java, org/postgresql/jdbc4/AbstractJdbc4Connection.java, org/postgresql/util/HStoreConverter.java, org/postgresql/util/PGbytea.java, org/postgresql/util/ServerErrorMessage.java
Take advantage of Java 5 using StringBuilder where applicable
- replacement is done when `StringBuffer` is used as a local variable
- public methods using `StringBuffer` are kept but deprecated in favor of the same using `StringBuilder`. Cases can be found in `org.postgresql.core.Utils`. New public methods using `StringBuilder` do not use the same name as their `StringBuffer` counterpart otherwise it would prevent existing code using `null` as a method argument to compile.
=> Replace StringBuffer with StringBuilder

build.xml
This ensures we include full debug info when doing a debug build. It has no effect on non-debug builds.
=> When building a debug jar, use debuglevel="lines,vars,source"

build.xml
All third-party maven dependencies are now optional. Ones relying on features that need optional dependencies should declare it in their own pom as they're no longer transitive.
This is particularly true for users of SSPI functionality which requires waffle on the classpath. Following lines should be used in that case:
```xml
<dependency>
<groupId>com.github.dblock.waffle</groupId>
<artifactId>waffle-jna</artifactId>
<version>1.7</version>
<scope>compile</scope>
</dependency>
```
No concrete implementation of slf4j is made transitive anymore (fixes #251)
=> Maven dependencies fix

.travis.yml, build.xml
- It is no longer necessary to run ant with `ant -lib lib <target>`, required libraries are automatically loaded by the build process (typically `ant all` is sufficient)
- ~~Documentation can be built without requiring prior installation of docbook stylesheet and saxon (saxon and XSLT stylesheets are retrieved from the nexus). The following command can be used to build documentation `ant snapshot-version doc` (fixes #226)~~
- The `clean` target delete the files added to the `lib` directory
=> Build process improvements

org/postgresql/PGProperty.java, org/postgresql/test/jdbc2/PGPropertyTest.java
When a Properties object is initialized with default properties using its one-arg constructor (what Driver#parseURL does), the method [PGProperty#isPresent](https://github.com/alexismeneses/pgjdbc/commit/33d55af9354743903fbc211e0413e4840d0f08a7#diff-ba5d8e206f51468b12a3cb8d32391a62L449) was returning incorrect result for these default properties.
`ssl` parameter is checked using aforementioned method hence the issue.
This fixes #259
=> fix: regression of `ssl` parameter processing when used in additional Properties

org/postgresql/ds/common/BaseDataSource.java, org/postgresql/test/jdbc2/optional/OptionalTestSuite.java, org/postgresql/test/jdbc2/optional/SimpleDataSourceWithUrlTest.java
The latest 9.4 jdbc driver fails with NullPointerException when data source setUrl method is invoked.
Fix it and add test to make sure it does not break again.
=> Fix setUrl method of BaseDataSource. 

lib/.gitignore
Jar files downloaded from maven should be ignored in the code tree.
=> Update entries in lib/.gitignore

.travis.yml
This PR adds testing against PostgreSQL 9.4 to the Travis-CI matrix. I did it in a couple of separate commits that first clean up the order of the order of the JDK versions (openjdk7 was before openjdk6). 
Also, this fixes an bug in the config as it wasn't testing against oraclejdk8/9.2 (9.3 was erroneously included twice).
=> Add PostgreSQL 9.4 to Travis-CI Matrix

org/postgresql/PGConnection.java, org/postgresql/jdbc2/AbstractJdbc2Connection.java
Add methods for escaping identifiers and literals to public PGConnection interface. The methods are added there, rather then exposing the static versions publicly, so that the connection specific standard_conforming_strings property is used.
Closes #198 
This is a pretty straight forward PR ... the only thing that's kind of odd is the `throws SQLException` but that's the contract of the underlying static methods. Both reject zero bytes within strings and throw a `PSQLException` if they encounter one in the string to be escaped.
The descriptions for the javadocs for the two new methods were take from PG docs for `quote_ident(...)` and `quote_literal(...)`.
=> feat: add escapeLiteral(...) and escapeIdentifier(...) to PGConnection

org/postgresql/util/PSQLState.java
This commit adds support for equality comparison of PSQLState
instances by specializing the equals(...) and hashCode() methods.
Previously, two seemingly identical instances (e.g., `new
PSQLState("0100E")` and `new PSQLState("0100E")`) would not compare
equal.
This change is particularly useful to Scala developers. Pattern
matching can now be used against the predefined constant PSQLState
instances.
=> feat: add equality support to PSQLState

org/postgresql/jdbc2/AbstractJdbc2Statement.java
It fix for issue https://github.com/pgjdbc/pgjdbc/issues/288
Property "org.postgresql.forceBinary" uses only only for testing purposes and not change in runtime, so, they can be cached to static variable for improve creating statement instance.
Benchmark for test changes was use from https://github.com/pgjdbc/pgjdbc/pull/290
JFR hot method before changes on my machine
JFR hot method after chanages on my machine
Benchmark that measure create Statement became more faster
```
Benchmark                                                           (autoCloseStatements)  Mode  Cnt     Score     Error   Units
FinalizeStatement.createStatement                                                   false  avgt   10    50,137 ?   1,228   ns/op
```
Previous result was
```
FinalizeStatement.createStatement …
```
=> perf: Excessive time spent in Boolean.getBoolean("org.postgresql.forceBinary")

org/postgresql/ds/common/BaseDataSource.java
The documentation shows the property name for the logging level is "loglevel". All lower case.
A method has been added to the base data source to work in cases where a user configures a datasource with exactly the same case.
=> Added setter method for logging level.

doc/pgjdbc.xml, org/postgresql/PGConnection.java, org/postgresql/PGProperty.java, org/postgresql/ds/common/BaseDataSource.java, org/postgresql/jdbc2/AbstractJdbc2Connection.java, org/postgresql/jdbc4/Jdbc4Connection.java, org/postgresql/jdbc42/Jdbc42Connection.java, org/postgresql/test/jdbc42/CustomizeDefaultFetchSizeTest.java, org/postgresql/test/jdbc42/Jdbc42TestSuite.java
After migration big application from Oracle to PostgreSQL we faced with problem that application use too many memory and as result it lead to OutOfMemoryException. The application that has been developing for more than one year which develops many developers usually there are several entry points to the database. It can be use manually Connection\Statements\etc or it can be Spring JdbcTemplate or some own implementation. Common points it's application server datasource in that configure connection to postgresql. And it's a good point for configure global parameters like default fetch size that allow facilitate migration from Oracle and its default value of 10 to PostgreSQL where by default fetches all records at once.
I add additional property 'defaultRowFetchSize' that can be specify on …
=> Customize default fetchSize for statements

.gitignore, doc/pgjdbc.xml, org/postgresql/PGConnection.java, org/postgresql/PGProperty.java, org/postgresql/ds/common/BaseDataSource.java, org/postgresql/jdbc2/AbstractJdbc2Connection.java, org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/jdbc2/StatementFinalizer.java, ubenchmark/pom.xml, ubenchmark/src/main/java/org/postgresql/benchmark/connection/FinalizeConnection.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/FinalizeStatement.java, ubenchmark/src/main/java/org/postgresql/util/ConnectionUtil.java
Finalize method on Statement was move to a saparete class that is lazily created if user sets "autoCloseUnclosedStatements"="true".
Parameters in state "autoCloseUnclosedStatements"="false" dramatically improves the performance of statement instantiation and reduces garbage collection overhead on several wildly used JMVs.
For demonstrate finalize overhed was add jmh benchmark like disscussed in issue  #289
The added jmh benchmark validates the performance of statement creation.
```java
@Benchmark
public Statement createStatement() throws SQLException
{
Statement statement = connection.createStatement();
statement.close();
return statement;
}
```
I get next result on my mashin(full report: https://gist.github.com/Gordiychuk/72791b7ff5677d11117e)
```
Benchmark …
```
=> perf: Remove expensive finalize methods from Statement and Connection

org/postgresql/jdbc2/AbstractJdbc2ResultSet.java, org/postgresql/test/jdbc2/CursorFetchTest.java
Fixes status returned by ResultSet positioning methods (isFirst/isLast/isBeforeFirst/isAfterLast) in two particular cases:
- fetchsize is non-zero and current position is at the boundary of a fetch (bug reported by Luis Michel Pinto Da Costa in [mailing list](http://www.postgresql.org/message-id/flat/OFF3D569C5.9BC4DC3D-ONC1257E1B.0045CF5C-C1257E1B.00472393@retraite.lan) )
- the resultset is empty (ie. contains no row) as the jdbc spec require all positionning methods to return false
=> Fix: ResultSet positioning methods in some particular cases

README.md
Java 1.5 features can be used since it is the minimal supported version for PgJDBC.
closes #294
=> docs: fix misleading statement on "can't use jdk5 features" in README.md

.gitignore, ubenchmark/pom.xml, ubenchmark/src/main/java/org/postgresql/benchmark/connection/FinalizeConnection.java, ubenchmark/src/main/java/org/postgresql/benchmark/core/Parser.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/FinalizeStatement.java, ubenchmark/src/main/java/org/postgresql/util/ConnectionUtil.java
For instance, Statement create/close loop leads to OutOfMemory in OpenJDK/OracleJDK (finalizer 
queue fills up)
```
-Xmx128m, OracleJDK 1.8u40, MacOS, 2.6Ghz Core i7
java.lang.OutOfMemoryError: GC overhead limit exceeded
```
closes #289
=> feat: Implement micro-benchmark module for performance testing

org/postgresql/core/Parser.java
It is likely double question marks are not used, so add short-circuit to Parser.unmarkDoubleQuestions.
Key observations:
* when query does not have _double_ question marks, unmarkDoubleQuestion becomes 6 times faster, no java garbage is generated
* For big query (6KiB) with "??" at the very end degradation is 18us -> 19us
Before:
```
Benchmark                                                     (literalLength)  (sqlSize)  (withDoubleQuestionmark)  Mode  Cnt      Score     Error   Units
Parser.unmarkDoubleQuestion                                                20          1                     false  avgt   10    175,338 ±   2,144   ns/op
Parser.unmarkDoubleQuestion:·gc.alloc.rate                                 20          1                     false  avgt   10   3132,534 ±  38,399 …
```
=> perf: improve sql parsing performance

org/postgresql/jdbc2/AbstractJdbc2Statement.java
AbstractJdbc2Statement.finalize is not required since server-side resources (if any) are managed in org.postgresql.core.v3.QueryExecutorImpl#processDeadParsedQueries.
Even though dead queries are processed at subsequent operations on the connection, since GC is still required to find dead statements (like with finalizers), and the dead statements would be processed right at the subsequent execute.
It is believed that scenario of "create lots of prepared statements, then stop any activity on the connection" would never happen, so no additional handling is implemented for that case.
Here's what `FinalizeStatement.createAndLeak` gives after the fix (-Xmx128m, OracleJDK 1.8u40, MacOS, 2.6GHz Core i7):
```
Benchmark                                                         (leakPct)  Mode  Cnt …
```
=> perf: improve statement instantiation by removing finalize

org/postgresql/core/v3/QueryExecutorImpl.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/ParseStatement.java
Keep and reuse static values for $1, $2 in UTF8 encoding.
This change cuts 10-30% of heap allocations for statements with 1-20 binds.
=> perf: improve performance of preparing statements

org/postgresql/core/Utils.java, ubenchmark/src/main/java/org/postgresql/benchmark/encoding/UTF8Encoding.java
`Utils.encodeUTF8` seems to use workarounds for java 1.4 & java 1.5.
In OpenJDK 1.6+ just using `String.getBytes(Charset)` is ~3 times faster, so I've updated `Utils.encodeUTF8` implementation with `String.getBytes(Charset)` call.
=> perf: improve performance of UTF-8 encoding

org/postgresql/core/types/PGBigDecimal.java, org/postgresql/core/types/PGBoolean.java, org/postgresql/core/types/PGByte.java, org/postgresql/core/types/PGDouble.java, org/postgresql/core/types/PGFloat.java, org/postgresql/core/types/PGInteger.java, org/postgresql/core/types/PGLong.java, org/postgresql/core/types/PGNumber.java, org/postgresql/core/types/PGShort.java, org/postgresql/core/types/PGString.java, org/postgresql/core/types/PGType.java, org/postgresql/core/types/PGUnknown.java, org/postgresql/jdbc2/AbstractJdbc2Statement.java
Reduce GC stress by using solely two shared PGBoolean instances.
Test shows that setObject(i, v, type) runs 13% faster for boolean.
Prepare future caching of PG* types using valueOf().
Closes #315
=> perf: use shared PGBoolean instances

org/postgresql/core/v3/QueryExecutorImpl.java
`pgStream.Receive(int siz)` allocates `new byte[siz]`, so use `ReceiveChar()` to read one byte
=> perf: cut new byte[1] from QueryExecutorImpl.receiveCommandStatus

org/postgresql/core/v3/SimpleParameterList.java
Flags easily fit into byte[], so use byte[] to reduce heap consumption.
=> perf: SimpleParameterList.flags int[] -> byte[]

org/postgresql/jdbc2/AbstractJdbc2Statement.java
`testReturn` and `functionReturnType` are used in `CallableStatements` only, so avoid overhead for prepared statements.
=> perf: skip instantiation of testReturn and functionReturnType for non-callable statements

README.md
PostgreSQL server accepts empty "database" parameter and
will default it to "username".
Closes #331
=> docs: parameter "database" is optional

org/postgresql/core/v3/QueryExecutorImpl.java, org/postgresql/core/v3/SimpleQuery.java, org/postgresql/test/jdbc4/BinaryTest.java
When using prepared statement, field format needs to be computed only once.
=> perf: avoid useBinary(field) check for each sendBind

org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/jdbc4/AbstractJdbc4Statement.java, org/postgresql/jdbc4/Jdbc4Connection.java, org/postgresql/jdbc42/AbstractJdbc42Statement.java, org/postgresql/jdbc42/Jdbc42CallableStatement.java, org/postgresql/jdbc42/Jdbc42Connection.java, org/postgresql/jdbc42/Jdbc42PreparedStatement.java, org/postgresql/jdbc42/Jdbc42Statement.java
Move `setPrepareThreshold(getPrepareThreshold())` and `setFetchSize(getDefaultFetchSize())` to base `AbstractJdbc2Statement`.
=> refactor: cleanup constructors of JDBC4 and JDBC42 connections/statements

doc/pgjdbc.xml, org/postgresql/PGProperty.java, org/postgresql/core/CachedQuery.java, org/postgresql/core/NativeQuery.java, org/postgresql/core/Parser.java, org/postgresql/core/v2/QueryExecutorImpl.java, org/postgresql/core/v2/V2Query.java, org/postgresql/core/v3/QueryExecutorImpl.java, org/postgresql/core/v3/SimpleQuery.java, org/postgresql/ds/common/BaseDataSource.java, org/postgresql/jdbc2/AbstractJdbc2Connection.java, org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/jdbc2/CachedQueryCreateAction.java, org/postgresql/jdbc2/CallableQueryKey.java, org/postgresql/jdbc3/AbstractJdbc3Statement.java, org/postgresql/test/util/LruCacheTest.java, org/postgresql/util/CanEstimateSize.java, org/postgresql/util/LruCache.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/ParseStatement.java
This allows to use server-side prepared statements when application uses the same SQL multiple times.
Major difference from existing `setPrepareThreshold` is with current fix application does not have to reference exactly the same `PreparedStatement`. When a new statement is prepared, it is checked against existing statements in the cache. If there is a match, parsing result and server-side named query (!) are reused.
Note: this fix comes on top of https://github.com/pgjdbc/pgjdbc/pull/311.
Cache size is configurable. It defaults to 256 queries and 5 MiB maximum per connection.
Feel free to review, add your comments, and merge.
Some measurements:
On a simple `select ?, ?, ?...` the response time is 20-40% better (78us -> 46us for 20 binds).
Execution of cached statements allocates 50% …
=> perf: cache prepared statements across .prepareStatement calls

org/postgresql/core/NativeQuery.java, org/postgresql/core/Parser.java, org/postgresql/core/v2/QueryExecutorImpl.java, org/postgresql/core/v2/V2Query.java, org/postgresql/core/v3/QueryExecutorImpl.java, org/postgresql/core/v3/SimpleQuery.java
This saves a bit of cycles when encoding the query to UTF8 (the whole query can be encoded at once)
I've updated both V2 and V3 queries.
?? -> ? replacing is folded into the parse process.
=> perf: parse SQL to a single string, not a array of fragments

org/postgresql/geometric/PGline.java, org/postgresql/test/jdbc2/GeometricTest.java, org/postgresql/util/PGtokenizer.java
- Modifications to PGline to store coefficients and constant value for linear equation representations used by postgresql for native line datatype.
=> Fix for issue https://github.com/pgjdbc/pgjdbc/issues/342

org/postgresql/jdbc2/AbstractJdbc2Array.java, org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/jdbc2/TypeInfoCache.java, org/postgresql/test/TestUtil.java, org/postgresql/test/jdbc3/CompositeTest.java
Composite types can live if their own schema. This requires type name lookup to cope with it.
Names are case sensitive.
Added simple logic which will split schema/name when . is used.
Postgres allows for names which start with '_' ; therefore it is incorrect to assume array type will start with '_' , although that can be assumed for all builtin types.
Improve type detection and use '[]' suffix as array alias.
Make most of the code backward compatible so it uses old logic with '_' instead of '[]' on lookups and naming.
Relations which live in search_path will be registered using both simple and full name.
Simple arrays will be populated using connection.getObject if everything else fails (only 1-dim array are handled as such)
TODO: handle scenario when '"' is used inside schema or type …
=> feat: Improved composite/array type support and type naming changes.

org/postgresql/jdbc2/AbstractJdbc2Connection.java, org/postgresql/jdbc4/AbstractJdbc4Connection.java, org/postgresql/test/jdbc4/jdbc41/SchemaTest.java
Previously the driver used "show search_path", however it might result into non-evaluated '$user' value
fixes #354
=> fix: use current_schema() for Connection#getSchema

release_notes.sh, release_notes_filter.pl
To be executed like `./release_notes.sh REL9_4_1200..HEAD`
fixes #357
=> chore: simple script to compose release notes

org/postgresql/core/v3/QueryExecutorImpl.java, org/postgresql/test/jdbc2/CopyTest.java
Fixed version of #362 -- the 9.1 problem was that back then `pg_terminate_backend` was more tightly locked down, and so the test wasn't successfully breaking its own connection.
=> Deadlock after IO exception during copy cancel

release_notes_filter.pl
Not all commit messages have PR ids, so the script needs to try finding merge commit
fixes #358
=> chore: teach release_notes.sh to identify PR ids out of merge commits

org/postgresql/copy/CopyManager.java, org/postgresql/test/jdbc2/CopyLargeFileTest.java, org/postgresql/test/jdbc2/Jdbc2TestSuite.java, org/postgresql/test/util/BufferGenerator.java, org/postgresql/test/util/StrangeFileInputStream.java
https://github.com/pgjdbc/pgjdbc/commit/5868e3db41b5e52ee62c7117fa55314718d0b361 seem not to fix the problem (while(len >= 0) instead of while (len > 0) in the read cycle).
This pull request contains test for the #366 plus fix.
=> fix: #366 with test

org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/jdbc2/TimestampUtils.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/BindTimestamp.java
Avoid Calendar cloning and Integer.toString in setCalendar. This improves setTimestamp from 0.8us to 0.2us
Before
```
Benchmark                                                      Mode  Cnt    Score     Error   Units
BindTimestamp.timestampCal                                     avgt    5  754,114 ±  91,625   ns/op
BindTimestamp.timestampCal:·gc.alloc.rate                      avgt    5  931,234 ± 111,715  MB/sec
BindTimestamp.timestampCal:·gc.alloc.rate.norm                 avgt    5  736,007 ±   0,061    B/op
BindTimestamp.timestampCal:·gc.churn.PS_Eden_Space             avgt    5  934,073 ±  86,972  MB/sec
BindTimestamp.timestampCal:·gc.churn.PS_Eden_Space.norm        avgt    5  738,410 ±  34,828    B/op
BindTimestamp.timestampCal:·gc.churn.PS_Survivor_Space         avgt    5    0,405 …
```
=> perf: improve setTimestamp, setTime, setDate performance

org/postgresql/core/QueryExecutor.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/InsertBatch.java
QUERY_FORCE_DESCRIBE_PORTAL shared the same value as QUERY_DISALLOW_BATCHING (128), so batching was effectively disabled.
For instance, simple insert batch for 100 rows improves from 15ms to 1ms (when testing against local postgresql). The same 100 rows take 15ms for non-batched insert.
Before
```
Benchmark                                                   (nrows)  Mode  Cnt      Score        Error   Units
InsertBatch.insertBatch                                         100  avgt   10     15,052 ±      2,501   ms/op
InsertBatch.insertBatch:·gc.alloc.rate                          100  avgt   10      3,408 ±      0,501  MB/sec
InsertBatch.insertBatch:·gc.alloc.rate.norm                     100  avgt   10  53319,755 ±    333,930    B/op
InsertBatch.insertBatch:·gc.churn.PS_Eden_Space …
```
=> pref: improve executeBatch by avoiding statement-by-statement execution

org/postgresql/core/Parser.java, org/postgresql/test/jdbc3/CompositeQueryParseTest.java, org/postgresql/test/jdbc3/Jdbc3TestSuite.java
This allows having trailing "; ".
I'm not sure why users want that, however this seems to be the behavior of a previous pgjdbc version.
Note: I am not sure with the expected behavior in case of "empty queries". Alternative solution would be to throw human-understandable error that would tell user not to use empty queries (or semicolons).
=> feat: ignore empty sub-queries in composite queries

org/postgresql/jdbc2/AbstractJdbc2ResultSet.java, org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/jdbc2/TimestampUtils.java, org/postgresql/test/TestUtil.java, org/postgresql/test/jdbc2/TimezoneTest.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/ProcessResultSet.java, ubenchmark/src/main/java/org/postgresql/benchmark/time/TimestampToDate.java, ubenchmark/src/main/java/org/postgresql/benchmark/time/TimestampToTime.java
This is a follow-up on #376.
I force TimezoneTest to test both text and binary encoding and it makes 
It looks like this PR fixes all known problems with Timestamp/Date/Time parsing.
I wish someone could add more tests.
Here are the measurements (jdk 1.8u60, OS X 10.11, Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz, time zone == Europe/Moscow, local postgresql 9.4).
The test is to perform and fully fetch a query like `select localtimestamp c0, localtimestamp c1, ... from generate_series(1, ?) as t(x)`: https://github.com/pgjdbc/pgjdbc/pull/387/files#diff-962be0de5c547f8cb43ea8efd768dccaR88
Notes:
1) There is a slight degradation of `getTimestamp` when selecting `localtimestamp` if compared with 1203. I believe the degradation is due to more complex logic in `TimestampUtil.guessTimestamp`.
I …
=> fix: binary processing of Date/Time/Timestamps

org/postgresql/test/jdbc3/CompositeQueryParseTest.java
The expected output is empty list of queries
=> test: add tests for parsing of empty queries separated by semicolons

org/postgresql/core/ProtocolConnection.java, org/postgresql/core/v2/ProtocolConnectionImpl.java, org/postgresql/core/v2/QueryExecutorImpl.java, org/postgresql/core/v3/ProtocolConnectionImpl.java, org/postgresql/core/v3/QueryExecutorImpl.java
Fixes a situation where the backend aborts ungracefully. It appears the backend does not attempt to close the connection which leaves the socket "half" open. We just abort and close the underlying socket
=> fix: abort connection on I/O error instead of closing

org/postgresql/jdbc2/AbstractJdbc2ResultSet.java
`FAST_NUMBER_FAILED` is used as a control-flow-exception pattern, thus it does not require a stacktrace.
It turns out `Throwable` might store strong reference to a class, thus it might result in `OutOfMemoryError`.
=> fix: avoid memory leak when redeploying pgjdbc

org/postgresql/jdbc2/TimestampUtils.java
This can cause compilation to fail on some environments with an error
of this type:
[javac] TimestampUtils.java:699: unmappable character for encoding ASCII
=> Remove non-ASCII character in code

org/postgresql/core/PGStream.java
If lc_messages is set to a language which uses UTF-8 then connections which fail garble messages
=> fix: use UTF-8 instead of US-ASCII for initial encoding

org/postgresql/jdbc2/TypeInfoCache.java, org/postgresql/jdbc4/AbstractJdbc4Connection.java, org/postgresql/test/jdbc3/CompositeTest.java, org/postgresql/test/jdbc4/ArrayTest.java
Instead of lowercasing typename which causes problems for types which require quote due to non lowercase casing, lowercase on failed alias check and during type lookup for types without schema or quote.
Improve the quote casing heuristics by checking for quote char.
Support case type in schemas on path without schema reference.
Current rules for casing
type => "type"
TYPE => "type"
"Type" => "Type"
NS.TYPE => "ns"."type"
"NS"."Type" => "NS"."Type"
NS."TYPE" => "ns"."TYPE"
This change introduces breaking change. Previously casing was not changed.
Now unquoted names will be considered lowercase.
So if you had type: CREATE TYPE "TIMESTAMPTZ"(at timestamp, offset int)
you could reference it with TIMESTAMPTZ. Now quotes are required, otherwise it will default to timestamptz which is Postgres …
=> fix: Improve type detection with casing issues.

org/postgresql/translation/cs.po, org/postgresql/translation/de.po, org/postgresql/translation/fr.po, org/postgresql/translation/it.po
This should close #408.
I notice there is an open #348 to make `update-translations.sh` be automatically run (contrary to the maintainer instructions on the [translations page][trn]). I wonder if the project has escaped embarrassment in international quarters exactly because that _didn't_ happen in 2013 when these files got clobbered....
[trn]: https://jdbc.postgresql.org/development/translations.html
=> fix: restore clobbered translations (cs, de, fr, it)

org/postgresql/core/Field.java, org/postgresql/jdbc2/AbstractJdbc2ResultSet.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/ProcessResultSet.java
There are two changes:
1) Fast-path for `long` -> BigDecimal. For small values, database can send binary `long`, so there is no need to convert the received long back to string (see type=BIGINT below)
2) "Cached getSQLType" speeds up getObject (see type=bigdecimal, getter=object below).
Before:
```
Benchmark                 (getter)  (ncols)  (nrows)     (type)  Mode  Cnt      Score    Error  Units
ProcessResultSet.execFetch    BEST        5     1000         INT  avgt    5   599,098 ± 11,030  us/op
ProcessResultSet.execFetch    BEST        5     1000  BIGDECIMAL  avgt    5  2392,760 ± 26,083  us/op
ProcessResultSet.execFetch    BEST        5     1000      BIGINT  avgt    5  3141,686 ± 92,846  us/op
ProcessResultSet.execFetch  OBJECT        5     1000  BIGDECIMAL  avgt    5  3400,252 ± …
```
=> perf: improve performance of resultSet.getObject

org/postgresql/jdbc2/AbstractJdbc2Statement.java, org/postgresql/test/jdbc2/StatementTest.java
Statement.cancel was not thread-safe, thus query timeout from one statement might cancel subsequent statement.
The change introduces state tracking of a statement (ide, in-query, cancelling, cancelled), so out-of-order cancels can be detected and ignored.
There are two basic problems with .cancel handing:
1) `cancel`s called at random from user code. Even thought `Statement#cancel` does not require thread-safety, it would be "a bit" unexpected if `statementA.cancel` would cancel subsequent `statementB` that is run in the same connection.
The thing is backend protocol does not allow to cancel a specific execution, thus if user invokes `cancel`, pgjdbc should ensure that cancel would not terminate another statement by mistake.
The approach is to have `statementState` and skip cancels that …
=> fix: make Statement.cancel and Statement.setQueryTimeout thread safe

.gitattributes
This makes sure text files are sored in LF form in the git repository, so Windows contributors do not end up with "EOL changed" PRs
=> chore: add .gitattributes to ensure automatic end-of-line storage of text files is used

org/postgresql/jdbc2/AbstractJdbc2Array.java, org/postgresql/jdbc2/AbstractJdbc2ResultSet.java, org/postgresql/test/CursorFetchBinaryTest.java, org/postgresql/test/jdbc2/BaseTest.java, org/postgresql/test/jdbc2/BatchExecuteBinaryTest.java, org/postgresql/test/jdbc2/BatchExecuteTest.java, org/postgresql/test/jdbc2/CursorFetchTest.java, org/postgresql/test/jdbc2/Jdbc2TestSuite.java, org/postgresql/test/jdbc2/PreparedStatementBinaryTest.java, org/postgresql/test/jdbc2/PreparedStatementTest.java
It turns out `BigDecimal.valueOf(12, 1) == "12.1"` while `BigDecimal.valueOf(12).setScale(1) == "12.0"`
=> fix: fix invalid values when receiving int2, int4, int8 via getBigDecimal()

org/postgresql/core/Parser.java, org/postgresql/test/jdbc3/CompositeQueryParseTest.java
In [this thread](http://www.postgresql.org/message-id/n2ha84$5u8$1@ger.gmane.org) Thomas Kellerer uttered his surprise that questions marks are replaced with positional parameters in a <tt>java.sql.Statement</tt>.
I think that is a bug, an I came up with this patch to fix it.
My only concern is that this is a behaviour change that might break existing code...
=> Replace question marks only in PreparedStatements

org/postgresql/PGProperty.java, org/postgresql/jdbc2/AbstractJdbc2Connection.java, org/postgresql/test/TestUtil.java, org/postgresql/test/jdbc2/PGPropertyTest.java
This PR fixes changes introduced in 1205 release.
It adds a new method to PGProperty to return a property value without using the default. Allowing NULL to be returned.
Changed the impl of isPresent method. To actually work.
Added two test cases. To check isPresent and getSetString methods both work.
The fixed isPresent method smokes out an issue in an SSL test case. Now the method is fixed this test fails now.
=> Fix to mend debug logging to allow programmatic level setting.

org/postgresql/jdbc2/AbstractJdbc2ResultSet.java
AbstractJdbc2ResultSet#parseQuery contains the following code
```java
if ( !tableFound )
{
}
else
{
}
```
However since that code is inside a loop with the following condition
```java
while ( !tableFound && !tablesChecked && st.hasMoreTokens() )
```
We know that `tableFound` will always be false and therefore the true
branch of the if else will always be executed.
=> Useless condition in parseQuery

org/postgresql/jdbc2/AbstractJdbc2DatabaseMetaData.java
AbstractJdbc2DatabaseMetaData.getTablePrivileges contains the following
code:
```java
// report the owner as grantor if it's missing
String grantor = grantTuple[0].equals(null) ? owner : grantTuple[0];
```
This will cause a `NullPointerException` if the grantor is missing
instead of using the owner because you can't call `#equals` (or any
method) on `null`.
The code should read
```java
// report the owner as grantor if it's missing
String grantor = grantTuple[0] == null ? owner : grantTuple[0];
```
=> Fix null check in getTablePrivileges

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchExecuteTest.java
Register cleanup for statement unprepare early, so it points to the proper statement name.
This might fix #443.
The test causes query executor to re-prepare statement in case types of binds change.
The bug is caused by late creation of PhantomReference->statementName cache entry (as both ParseComplete messages arrive, the Query has changed its statement name)
=> fix: prepared statement "S_2" does not exist in batch executions

pgjdbc/src/main/java/org/postgresql/core/v2/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
This PR fixes #492 to configure ssl when defined as Properties.
The change updates both v2 and v3.
=> fix: load the ssl configuration property when defined through 

pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/v2/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchExecuteTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchFailureTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
Previously, executeBatch did not consider that under error condition, a part of the batch might get rolled back.
closes #502
=> fix: make sure executeBatch returns error response for rows that would not get into database

pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/QuotationTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
=> fix: make sure {fn now()} jdbc translation is not performed in dollar-quoted strings

pgjdbc/src/main/java/org/postgresql/core/ProtocolConnection.java, pgjdbc/src/main/java/org/postgresql/core/Provider.java, pgjdbc/src/main/java/org/postgresql/core/v2/ProtocolConnectionImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/ProtocolConnectionImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimezoneTest.java
Note: tstz in binary is sent without timezone, thus ParameterStatus(TimeZone = GMT-01:00) should be used to track connection's time zone
closes #130
=> fix: binary timestamptz -> getString should add +XX zone offset to text representation

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
Refactored an unnecessary conversion of List<String[]> to String[][] when calling the sendStartupPacket.
Signed-off-by: Florin Asavoaie <florin.asavoaie@gmail.com>
=> Small code refactoring

pgjdbc/src/test/java/org/postgresql/test/jdbc2/GeometricTest.java
This is the only test that fails if the server locale is not English, or en_US, or whatever.
The comment on this code actually says it tests whether the server throws "an exception". The original code checked the nature of the exception, so this does, too.
(Note: I did not set up to run the SSL or XA tests, so they were skipped.)
=> Make tests independent from server LC_MESSAGES

.travis.yml, README.md, pgjdbc/src/main/java/org/postgresql/core/ServerVersion.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, travis_deploy.sh, travis_install_dependencies.sh
This PR adds PostgreSQL 9.6 regression test.
`org.postgresql.jdbc.PgDatabaseMetaData#getIndexInfo` is changed to return `NULL AS ASC_OR_DESC` for 9.6+.
9.6 does not have `pg_am.amcanorder`, thus `getIndexInfo` failed as the following:
```
testPartialIndexInfo(org.postgresql.test.jdbc2.DatabaseMetaDataTest)  Time elapsed: 0.055 sec  <<< ERROR!
org.postgresql.util.PSQLException: ERROR: column am.amcanorder does not exist
Position: 427
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2299)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2015)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:210)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:425)
at …
```
=> fix: support PostgreSQL 9.6

pgjdbc/src/main/java/org/postgresql/core/v3/DescribeRequest.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchExecuteTest.java
Some batch executions might result in "incorrect binary data format" if using non-exact data types (e.g. date) and bind different data types for the same bind position across executions.
Reported here: https://www.postgresql.org/message-id/681cd4467be74455a6e599b3838164f5%40EX2013-DB01.adesso.local
=> fix: incorrect binary data format in bind parameter X when using batch execution

pgjdbc/src/main/java/org/postgresql/core/Oid.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/ArrayTest.java
This is a very minor performance improvement. It adds `json` type info
to the client in order to avoid the execution of a query to retrieve the
oid of the `json` type.
=> Add json type info to Client

pgjdbc/src/main/java/org/postgresql/core/Oid.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
This is a very minor performance improvement. It adds `point` type info
to the client in order to avoid the execution of a query to retrieve the
oid of the `point` type.
=> Add point type info to Client

pgjdbc/src/main/java/org/postgresql/PGConnection.java, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/BaseConnection.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/ResultHandler.java, pgjdbc/src/main/java/org/postgresql/core/ResultHandlerBase.java, pgjdbc/src/main/java/org/postgresql/core/ResultHandlerDelegate.java, pgjdbc/src/main/java/org/postgresql/core/SetupQueryRunner.java, pgjdbc/src/main/java/org/postgresql/core/SqlCommand.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/AutoSave.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/CallableBatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/main/java/org/postgresql/util/PSQLState.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/ParseStatement.java
Bug report: http://stackoverflow.com/questions/34180932/error-cached-plan-must-not-change-result-type-when-mixing-ddl-with-select-via
When using "deallocate all" or "alter table", cached prepared statements might become invalid, thus we need to reexecute query in those cases
It might require some logging, however I'm not sure what is the best way to log that.
Summary (technical details):
1) By default pgjdbc watches for `DEALLOCATE ALL`, and `DISCARD ALL` statements, and invalidates prepared statement cache if those are detected.
That does not mean "deallocate all" should be used often. It just means deallocate all might be suitable for maintenance-like procedures.
Note: `deallocate all` invalidates only a single connection.
2) If either `prepared statement XXX does not exist` or `cached …
=> fix: try re-execute statement if backend responds with "prepared statement is no longer valid"

README.md
Two small OCD induced changes for the project README:
* Change brandnames to use proper capitalization and spacing. As of macOS Sierra the capitalization changed to have an initial lowercase 'm' (and the X in OS X was dropped from the brandname).
* The postgresql.org site is by default serving all traffic over https, change links in README to avoid an extra redirect. The exception is still developer.postgresql.org which only serves traffic over http.
=> Readme OCD fixes

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/util/PSQLException.java
In case transaction fails (i.e. 'current transaction is aborted, commands ignored until end of transaction block'), the initial error is included to the exception chain, so it is easier to analyze.
Example (note how `RootCauseSqlExceptionTestSuite.killTransaction` is included into caused by stack):
```
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2463)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
at …
```
=> feat: include root cause exception in case transaction fails

pgjdbc/src/main/java/org/postgresql/core/CachedQueryCreateAction.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/JsonbTest.java
=> fix: do not convert ?, ? to $1, $2 when statement.executeQuery(String) is used

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/CompositeTest.java
It's possible to use Postgres in an object oriented way.
Driver shouldn't break since some of it's assumptions are not valid in those usages.
"SELECT t FROM table t" will return the whole object, instead of some column inside it.
In those cases FieldMetadata doesn't make too much sense, since it's not returning the field, but rather a whole tuple.
Changed the test not to break (removal of public.) since this is ommited when object is on search path.
=> fix: Don't break when there is no column metadata

pgjdbc/pom.xml
Maven needs to specify the src/main/resources directory when another resources is specified.
=> fix: copy src/main/resources

pgjdbc/pom.xml, pgjdbc/src/main/resources/META-INF/LICENSE
Copy LICENSE file to META-INF folder to make it available to the pgjdbc-jre6 and pgjdbc-jre7 versions.
=> style: copy license file to META-INF folder

pgjdbc/src/main/java/org/postgresql/core/Utils.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
remove some deprecated methods from Utils class
add @Override on some methods in SimpleParameterList and PgConnection classes
=> refactor: remove deprecated Utils' methods

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
Current master branch state not pass travis build, because fail on javadocs generation.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project postgresql: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /home/fol/project/open-source/pgjdbc/pgjdbc/target/gen-src/org/postgresql/core/Parser.java:962: warning: no @throws for java.sql.SQLException
[ERROR] public static String replaceProcessing(String p_sql, boolean replaceProcessingEnabled,
[ERROR] ^
[ERROR] /home/fol/project/open-source/pgjdbc/pgjdbc/target/gen-src/org/postgresql/jdbc/PgDatabaseMetaData.java:2138: error: bad use of '>'
[ERROR] * For instance: SELECT -> user1 -> list of [grantor, grantable]
[ERROR] ^
[ERROR] …
```
=> bug: fix not enscaped special symbol that fail build

.travis.yml, pgjdbc/src/test/java/org/postgresql/test/extensions/HStoreTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/StringTypeParameterTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/ArrayTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/GetObjectTest.java
PostgreSQL 8.2
Tests run: 3527, Failures: 3, Errors: 170, Skipped: 1
At least, it starts & runs
=> test: try CI tests against PostgreSQL 8.2

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
Previously, `getImportedExportedKeys` needed to use `pg_depend` to
determine the index that supported a foreign key constraint. This was
done by joining `pg_depend` with `pg_constraint` to find the dependency
between the foreign key constraint and a row in `pg_class` with type
index.
Starting in version 9.0 of postgres, `pg_constraint` was extended with
the `conindid` column. This column gives us exactly what we want: for
foreign key constraint rows, `conindid` is the `oid` of the index that
supports the constraint.
This commit uses `pg_constraint.conindid` when the server version is new
enough instead of joining against `pg_depend`.
=> Do not use `pg_depend` against postgres 9.0+

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
PgDatabaseMetaData contains the methods rowChangesAreDetected,
rowChangesAreVisible and providesQueryObjectGenerator. They are not
documented, have no tests, always returns false and are not specified
in DatabaseMetaData.
This commit removes them.
=> refactor: clean up PgDatabaseMetaData

pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationStatusTest.java, pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java, pgjdbc/src/test/java/org/postgresql/replication/PhysicalReplicationTest.java, pgjdbc/src/test/java/org/postgresql/replication/ReplicationSlotTest.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java
Postgresql 9.4 doesn't have PID in pg_replication_slots view, so we can't terminate replication session. Instead of it, we wait until postgresql after `replicationConnection.close()` change replication slot status to not active.
```
testReplicationRestartFromLastFeedbackPosition(org.postgresql.replication.LogicalReplicationTest)  Time elapsed: 0.038 sec  <<< ERROR!
org.postgresql.util.PSQLException: ERROR: column "active_pid" does not exist
Position: 29
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2480)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2180)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
at …
```
=> bug: fix drop replication slot on 9.4 for tests

pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
Add query to support pg8.2 in TypeInfoCache.java without using typarray of pg_type
=> fix: add query to support pg8.2 without t.typarray

README.md
Add that the log destination is set by a call to
java.sql.DriverManager.setLogWriter(PrintWriter).
Fix some typos.
Clarify that class names passed as connection parameters
must be in a format that can be used by
Class.forName(String).
=> docs: clarify handling of loglevel

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
Based on the docs of PostgreSQL, valid literals are defined for [Boolean Type](https://www.postgresql.org/docs/current/static/datatype-boolean.html).
This add the valid literals for all TRUE and FALSE values, now it don't fall back to false if the value is not correct.
Note: This only works for [setObject with targetSqlType](http://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#setObject(int,%20java.lang.Object,%20int)).
closes #701
=> fix: robust castToBoolean for setObject in PreparedStatement

.travis.yml, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/ConnectionPoolTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/StringTypeParameterTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/ArrayTest.java
Some tests requiere features not available in PostgreSQL 8.2 and PostgreSQL 8.3, this PR ignore the test that won't work on it.
=> test: ignore tests that don't apply to Pg8.2 and Pg8.3

pgjdbc/pom.xml
if this PR is merged it become possible for checkstyle team to enforce no regression on sources of pgjdbc.
pgjdbc will be used in checkstyle's CI for each commit verification.
checkstyle/checkstyle#3670
=> config: move version of checkstyle to property

.travis.yml
Execute checkstyle first in Travis.
=> style: reorder checkstyle in travis

pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java
"This property is only relevant for server versions less than or equal to 7.2."
=> refactor: remove charset property not used

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
Class: PgDatabaseMetaData
Fix one "Inefficient number constructor"
Fix three "String concatenation in a loop"
related #586
=> fix: huntbugs on PgDatabaseMetaData

pgjdbc/pom.xml, pgjdbc/src/main/checkstyle/checks.xml, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/v3/CopyDualImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3PGReplicationStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3ReplicationProtocol.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/main/java/org/postgresql/largeobject/LargeObjectManager.java, pgjdbc/src/main/java/org/postgresql/replication/LogSequenceNumber.java, pgjdbc/src/main/java/org/postgresql/replication/PGReplicationConnectionImpl.java, pgjdbc/src/main/java/org/postgresql/replication/PGReplicationStream.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/AbstractStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/ChainedCommonStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/ChainedStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/ReplicationCreateSlotBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/ReplicationStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/logical/ChainedLogicalStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/logical/LogicalReplicationOptions.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/logical/LogicalStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/logical/StartLogicalReplicationCallback.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/physical/PhysicalCreateSlotBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/physical/PhysicalStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/util/PGmoney.java, pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationStatusTest.java, pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java, pgjdbc/src/test/java/org/postgresql/replication/ReplicationSlotTest.java, pgjdbc/src/test/java/org/postgresql/test/util/rules/ServerVersionRule.java
Issue #724 
1) extra space was removed
2) fix RightCurly configuration problem, the same update was done in checkstyle project, (checkstyle/checkstyle#3678). DO_WHILE was moved from one RightCurly configuration to another.
3) validation of CallableQueryKey.java is skipped as maintainers do not want fix violation of missed equals() for now
=> resolve violations from checkstyle 7.4

pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
Prevents usage of preparedStatements in `executeBatch` when `prepareThreshold` is set to 0
=> fix: ensure executeBatch() does not use server-side prepared statements when prepareThreshold=0

.travis.yml, .travis/travis_configure_replication.sh
=> test: fix test replication on PG_HEAD

.travis.yml, .travis/travis_check_postgres_health.sh, .travis/travis_configure_xa.sh, .travis/travis_install_head_postgres.sh, .travis/travis_start_postgres.sh
Add script that check health state of postgresql after run tests, because
some tests can lead to fail database with segmentation fault as it was
in #734. For easy debug this scenarios and provide helpfull information to
upstream we need check db state.
Right now health script extract backtrace from core dumps and print logs.
In the future list health checks can be increased.
Example build output https://travis-ci.org/Gordiychuk/pgjdbc/builds/194050719
Closes #735
=> chore: Gather backtrace from core dump on CI

pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimeTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java
remove checks for jdk version 1.4 in the tests
=> refactor: remove checks for jdk version 1.4 (tests)

pgjdbc/src/main/java/org/postgresql/ds/PGPoolingDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc2/optional/ConnectionPool.java, pgjdbc/src/main/java/org/postgresql/jdbc2/optional/PoolingDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc2/optional/SimpleDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc3/Jdbc3ConnectionPool.java, pgjdbc/src/main/java/org/postgresql/jdbc3/Jdbc3PoolingDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc3/Jdbc3SimpleDataSource.java
Deprecated PGPoolingDataSource instead of this class you should use a fully featured connection pool
like HikariCP, vibur-dbcp, commons-dbcp, c3p0, etc.
It also deprecates the backwards compatibility classes of DataSource with a link
to the correct implementation.
closes #729
=> fix: deprecated PGPoolingDataSource

pgjdbc/src/main/java/org/postgresql/jdbc/BooleanTypeUtil.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/util/PSQLState.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
This merge the code used to cast to boolean in getBoolean and setObject, it allows only valid values and reject wrong values.
This follows the specification more close and proper support the boolean types of PostgreSQL.
=> fix: improve handling of getBoolean and setObject

pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationStatusTest.java, pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java, pgjdbc/src/test/java/org/postgresql/replication/PhysicalReplicationTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyBothResponseTest.java
In PostgreSQL 10 the function pg_current_xlog_location() is renamed to pg_current_wal_location().
See https://github.com/postgres/postgres/commit/806091c96f9b81f7631e4e37a05af377b473b5da
=> test: fix replication test in Pg10

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, ubenchmark/pom.xml, ubenchmark/src/main/java/org/postgresql/benchmark/statement/ProcessBoolean.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/ProcessResultSet.java
The BE sends "t" or "f" for Oid.BOOL so there is no need to fall in getString which execute again checkResultSet(), decode and trim the returned String.
All of this can be avoided and get a performance benefit.
=> perf: short circuit Oid.BOOL in getBoolean

pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3PGReplicationStream.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/BooleanTypeUtil.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java
Enclose Logger with isLoggable in multi-parameter cases.
=> fix: add isLoggable around parameterized logger

README.md, docs/_config.yml, docs/_includes/changelog/42.0.0-notes.md, docs/_includes/changelog/42.0.0-release.md, docs/_layouts/default.html, docs/_layouts/default_docs.html, docs/documentation/changelog.md, docs/documentation/head/connect.md, docs/documentation/head/logging.md, docs/download.md, docs/index.html
Now is able to build the site with Jekyll 2.2.
Since Jekyll 2.2 don't support `include_relative`, it's changed to `include`.
Additionally since the *official* release date is today, change 2017-02-18 dates.
After this is merged the site needs to be rebuild and uploaded again.
=> fix: build site with jekyll 2.2.0

docs/documentation/head/replication.md
@Gordiychuk I apologize for not doing this sooner. Please review to make sure I haven't changed the substance of this.
=> Review the documentation for the replication API

docs/documentation/head/replication.md
The follow prop must be set:
```
PGProperty.PREFER_QUERY_MODE.set(props, "simple");
```
on a replication connection to create replication slots. The
docs demonstrate this in the full example near the bottom of
the page but not at the top where it shows creating a slot
thru pgjdbc.
fixes #759
=> Make replication docs use PREFER_QUERY_MODE

pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGPropertyTest.java
To avoid bad declaration of new properties in the driver, this test
check that the name of the enum matches the name of the property and that
for each "_" in the enum uses the lower camel case for the property.
There is an exclusion list for the properties that do not follow
the correct lower camel case but are retained for backward compatibility.
closes #727
=> test: check that new properties follow correct lower camel case

docs/documentation/head/callproc.md
specifies {? there was a space between { ?
fixes #767
=> fix callproc escape documentation the specification\

pgjdbc/src/main/java/org/postgresql/core/Encoding.java
Little refactor to simplify the Encoding class.
=> refactor: simplify Encoding class

docs/documentation/head/listennotify.md, pgjdbc/src/main/java/org/postgresql/PGConnection.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/NotifyTest.java
Improve waiting for notifications using the LISTEN/NOTIFY framework by adding an optional timeout to the PGConnection.getNotifications() method. The change does not have any effects for users that don't use this functionality and the API remain fully backwards compatible.
PS: Please squash commits when merging, the text of this pull request should give a nice commit message.
=> feat: improve waiting for notifications by providing a timeout option

.travis/travis_check_postgres_health.sh
Find coredump without sudo if it's available. It fix problem that travis
print to stdout not stderr message
```
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid, and setgid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
```
that affect command that find corredumps.
=> bug: fix false alarm on check coredump

pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3PGReplicationStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3ReplicationProtocol.java, pgjdbc/src/main/java/org/postgresql/replication/ReplicationType.java, pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationStatusTest.java, pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java, pgjdbc/src/test/java/org/postgresql/replication/PhysicalReplicationTest.java
lastReceiveLSN calculates not valid for logical replication. Right now it calculates like
`startLSN + payloadSize` from XLogData it's correct statement for physical replication 
where payload it's raw data from WAL, and we can easily estimate position of next message [1]. 
But it's does't work for logical replication, because raw data from WAL changes in output plugin
as a result size of output payload not equal to size of payload from WAL. For deal with this problem
logical replication for commit message include to startLSN transaction end lsn + 1 [2]. So we can use 
startLSN as is for lastReceiveLSN.
Thanks Stefan Smith for report this problem [3]. 
[1] https://github.com/pgjdbc/pgjdbc/pull/550#issuecomment-254427102
[2] https://github.com/postgres/postgres/blob/master/src/backend/replic …
=> Bug: Not valid calculate lastReceiveLSN for logical replication 

pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/Jdbc42CallableStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/Jdbc42TestSuite.java
Since DatabaseMetaData#supportsRefCursors now reports true
frameworks like Hibernate now use
callableStatement.getObject(int, ResultSet.class) to fetch the
REF_CURSOR.
Only support ResultSet.class as an argument to keep the patch simple.
Closes: #794
=> feat: support fetching a REF_CURSOR using getObject

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3CallableStatementTest.java
Fixes that function calls without parameters must have had parentheses, see #767 for further details.
I'm unsure about the tests I have added, are those in the correct class? Should there be others or are those sufficient?
=> fix: function calls without parameters do not require parentheses

pgjdbc/src/main/java/org/postgresql/util/ReaderInputStream.java, pgjdbc/src/test/java/org/postgresql/util/ReaderInputStreamTest.java
Fixes #800 (data truncated at the end of the stream, while using `setCharacterStream`)
=> #800: fix last block of stream being ignored if size < 8k

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimestampTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/GetObject310InfinityTests.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/Jdbc42TestSuite.java
Date/Timestamp infinity get converted to LocalDate.MIN/MAX and friends.
fixes #789
=> fix: infinity handling for java.time types

pgjdbc/src/main/java/org/postgresql/core/PGStream.java
This PR adds a check for a SOCKS proxy before resolving the hostname of the database.
If the database connection is passed through a SOCKS proxy, DNS resolution might not be possible from the Java process and the should be deferred so it can occur at the proxy.
I've created [an app on Github to reproduce this problem](https://github.com/jkutner/pg-socket-socks-test), which you can test by deploying for free on Heroku by clicking this button:
[![Deploy to Heroku](https://www.herokucdn.com/deploy/button.png)](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fkissaten%2Fspring-petclinic&template=https%3A%2F%2Fgithub.com%2Fjkutner%2Fpg-socket-socks-test)
By default, it uses a SOCKS proxy that runs alongside the app (on the same server), which works. But if you set the …
=> Only resolve hostname if not using a SOCKS proxy

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
This pull request adds the fallback in question in #810.
It adds the following changes:
* There is a new (private) `setNumber(int, Number)` method in `PgPreparedStatement` with the same functionality as `setBigDecimal(int, BigDecimal)`.
* `setBigDecimal(int, BigDecimal)` does invoke `setNumber(int, Number)`.
* A case has been added in `setObject(int, Object)` for when a `Number` of an unknown/unhandled type is given.
* Unittests for this.
I've opted for the least intrusive way of adding this by simply adding another check "at the end" to see if the given `Object` is of the type `Number`. If yes, it is forwarded to `setNumber(int, Number)`.
=>  fix: Add fallback to setObject(int, Object) for Number

.travis.yml
Use Azul Zulu to test Java 9 builds
=> chore: use zulu-9

pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java
```
ERROR: replication slot "pgjdbc_logical_replication_slot" is active for PID 19978
```
After close replication slot, postgresql require some times to kill
previous session before start new, that why need wait when previous session
die before restart replication replication via replication slot.
More correct way, it's use
org.postgresql.replication.PGReplicationStream#close, in that case not
necessary wait when previous session die, but current version postgresql still
have a bug that not allow stop replication fast enough[1].
1. http://www.postgresql.org/message-id/CAFgjRd3hdYOa33m69TbeOfNNer2BZbwa8FFjt2V5VFzTBvUU3w@mail.gmail.com
=> bug: floating logical replcation test

pgjdbc/src/main/java/org/postgresql/jdbc/BooleanTypeUtil.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
Fix PSQLException messages in getBoolean and setObject removing the type name of the column to avoid confusion.
closes #776
=> fix: remove type name from cast exception of getBoolean and setObject

pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3PGReplicationStream.java
check for statusInterval of 0 and return false when checking if it is time to update
=> fix issue #834 setting statusIntervalUpdate causes high CPU load \

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchExecuteTest.java
Use server-prepared statements when more than 1 row is inserted via executeBatch() API.
Previously it could take up to prepareThresolds batch executions.
see #836
=> fix: use server-prepared statements for batch inserts when prepareThreshold>0

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/test/java/org/postgresql/core/ParserTest.java, pgjdbc/src/test/java/org/postgresql/core/ReturningParserTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/QuotationTest.java
Note: things like  insert into ... select 1 returning from ... are still considered as "having returning keyword"
fixes #824
=> fix: better parsing for returning keyword

pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java
Prior to 8.3, PostgreSQL didn't invalidate cached plans following DDL
changes. This is mentioned in the 8.3 release notes as
Automatically re-plan cached queries when table definitions change
or statistics are updated
https://www.postgresql.org/docs/8.3/static/release-8-3.html
For details, see PostgreSQL commit b9527e9840 and friends.
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=b9527e984092e838790b543b014c0c2720ea4f11
=> test: assume minimum server version 8.3 testing autosave with ALTER

pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
The UUID datatype was added to PostgreSQL in version 8.3.
https://www.postgresql.org/docs/8.3/static/release-8-3.html
=> test: assume minimum server version 8.3 when testing with uuid

.travis.yml, .travis/travis_install_postgres.sh
Travis deprecates Precise. See https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
sudo: required for dist: precise will still be supported for a while, however no updates to that image is planned
Java 6 is not included into Trusty image, and installers no longer work (see http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html) since Oracle removed the installer files from public access.
=> chore: install PostgreSQL 9.1 to Trusty builds via apt, and use Precise for Java 6

pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CallableStmtTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/NotifyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/ParameterMetaDataTest.java
remove useless checks for protocol version in the tests.
Driver is compatible with PostgreSQL 8.2 and higher using the version 3.0 of the protocol.
=> refactor: remove useless checks in the tests

.travis.yml, pgjdbc/src/test/java/org/postgresql/test/jdbc3/StringTypeParameterTest.java
PostgreSQL 8.2 tests at Travis should be green now, so removing allow_failures configuration
=> test: make StringTypeParameterTest 8.3+ since 8.2 misses enum types

pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGTimeTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGTimestampTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimestampTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/GetObject310Test.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/SetObject310Test.java
Float timestamp equality comparisons like comparisons with any float
are problematic if they don't take into account their imprecise
nature. Some timestamp tests produce false negative failures for
servers compiled with float timestamps. Use JUnit assumptions to skip
these tests if the server doesn't have integer datetimes.
GetObject310Test and SetObject310Test still produce these false
negative failures. Failing assumptions in these tests throw
AssumptionViolationException rather than skipping the tests. This
may be due to these tests extending BaseTest which extends
junit.framework.TestCase rather than being treated as JUnit 4
tests. Leave these failing tests as-is for now as it's the existing
behavior, and throwing these exceptions exposes an issue with the test
setup rather than …
=> test: assume integer datetimes for timestamp tests

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ConcurrentStatementFetch.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
Non-zero fetchSize triggers use of named portals (for subsequent fetch requests),
however named portals does not require to use named statements.
fixes #869
=> fix: named statements were used when fetchSize was non-zero and prepareThreshold=0

README.md, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ConcurrentStatementFetch.java
PostgreSQL 8.2 is known to close named portals unexpectedly, so we just ignore the test.
The following scenario might be affected: old backend version + setFetchSize + interleaved ResultSet processing
This is a follow-up for #870 and #869 for PostgreSQL < 8.4
=> test: skip ConcurrentStatementFetch for PostgreSQL < 8.4

pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DriverTest.java
Previously setting these in properties passed to DriverManager.getConnection(url, props) were ignored
=> honour PGPORT, PGHOST, PGDBNAME in connection properties

pgjdbc/src/test/java/org/postgresql/test/README.md, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/extensions/ExtensionsTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/extensions/HStoreTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ServerErrorTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpsertTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/Jdbc4TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/UUIDTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/XmlTest.java, pgjdbc/src/test/java/org/postgresql/test/xa/XADataSourceTest.java, pgjdbc/src/test/java/org/postgresql/test/xa/XATestSuite.java
migrate XATestSuite, Jdbc2TestSuite, Jdbc4TestSuite, ExtensionsTestSuite test suites
https://github.com/pgjdbc/pgjdbc/issues/205
=> refactor: migrate to Junit4

pgjdbc/src/main/checkstyle/checks.xml
This PR is being created because of a backward breaking change being made in CheckStyle.
PR: https://github.com/checkstyle/checkstyle/pull/4893
Issue: https://github.com/checkstyle/checkstyle/issues/3671
We are breaking multiple APIs in Checkstyle 8 to clean up deprecated methods and such. This removed the deprecated property `maxLineLength` in `LeftCurly` as it wasn't doing anything and it's functionality was removed some time ago.
You can either accept this PR and not have an issue when you upgrade CS with this fix in the future,
or make your own change/fix later when you do upgrade CS.
Please let us know which way you intend to go.
Feel free to ask any questions.
Thanks.
=> style: remove deprecated maxLineLength from LeftCurlyCheck

pgjdbc/src/main/java/org/postgresql/Driver.java
The method was removed in https://github.com/pgjdbc/pgjdbc/pull/668, however
certain applications might still depend on it.
Mark the method as deprecated.
=> fix: reintroduce Driver.getVersion for backward compatibility reasons

pgjdbc/src/main/java/org/postgresql/sspi/NTDSAPI.java
doc: Added quotes to URL in `'@see'` tag over org.postgresql.sspi.NTDSAPI#DsMakeSpnW for syntactic correctness
The javadoc syntax in [oracle docs](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#see) states that a string should be enclosed in quotes. Even javadoc tool itself gives an error if unquoted strings are used as `@see` tag's argument. On the other hand `references` in `@see` tag don't need any quotes which can also be concluded looking at the syntax.
[checkstyle](https://github.com/checkstyle/checkstyle/) has actually decided to lay down parse errors for such cases. `checkstyle` uses `pgjdbc` repo in `wercker` CI and this particular input case results in CI failure.
**See also:**  [checkstyle/pull/4550#issuecomment](https://github.com/checkstyle/checkstyl …
=> doc: Added quotes to URL in '@see' tag over NTDSAPI#DsMakeSpnW

pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java
Some replication tests looks that suffer from race conditions for a feature
that is missing from the server "Stopping logical replication protocol".
Full discussion: https://www.postgresql.org/message-id/flat/CAFgjRd3hdYOa33m69TbeOfNNer2BZbwa8FFjt2V5VFzTBvUU3w@mail.gmail.com#CAFgjRd3hdYOa33m69TbeOfNNer2BZbwa8FFjt2V5VFzTBvUU3w@mail.gmail.com
Fixes #934
=> fix: ignore replication test until 11.1 to avoid random failures

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/GetObjectTest.java
In the review of #813 various issues with the initial implementation of
CallableStatement#getObject(int, Class) showed up that
ResultSet#getObject(int, Class) also has. This commit gives both
methods the same behavior.
This commit contains the following changes
- make errors localizable
- add support for SMALLINT <-> Short
- add support for BIGINT <-> BigInteger
- add support for TIMESTAMP <-> java.util.Date
- swap INTEGER and SMALLINT position
=> feat: improve ResultSet#getObject(int, Class)

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
Regex based approach for #960. This should handle all the current cases as well as a couple other ones (ex: "COPY 123").
The new code only throws an exception if the response is out of range (ex: count of rows is greater than 2^31-1). I think there's a separate PR/Issue to address changing the count to a long so I haven't changed any of that behavior here.
If the pattern doesn't match then no parsing error is thrown, it's silently skipped. I think that's a saner default as any new feature added to the server with a possibly incompatible command complete message wouldn't break the driver. Plus any new server responses that matches the generic `COMMAND COUNT` or `COMMAND OID COUNT` format would be handled with no code additions.
I purposely left the commented out `String command = ...` on …
=> feat: Parse command complete message via regex

.travis.yml
Move JDK 6 and 7 up, to catch errors more quickly, delete repeated jobs, only one JDK 6 and 7 remain.
This tries to help reduce the testing time in Travis.
=> chore: streamlining jobs

ubenchmark/src/main/java/org/postgresql/benchmark/encoding/UTF8Decoding.java
We have custom UTF-8 decoding code in UTF8Encoding for performance
reasons but no companion benchmarks to verify its performance.
=> test: add ubenchmark for UTF-8 decoding

.travis.yml, .travis/travis_install_openj9.sh
Run tests on Eclipse OpenJ9.
Not sure if we need to test with it. Comments?
Related: #649
=> test: add openj9 to the matrix

.travis.yml
Travis use "[Oracle Java (JDK) 8 / 9 Installer PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/java)" which pulls binaries directly from Oracle site, that PPA is sometimes slow updating the packages when Oracle release new versions of Java and that cause unstable (error) builds when Oracle release a new version and the former release is archived and requires login to download.
This removes the use of updated java versions since Travis release new images from time to time and we don't actually require using the very latest version.
=> chore: remove unstable updates to java

pgjdbc/src/test/java/org/postgresql/core/ParserTest.java, pgjdbc/src/test/java/org/postgresql/core/ReturningParserTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BlobTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ConnectionTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataPropertiesTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/GetXXXTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGTimeTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/RefCursorTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimestampTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpdateableResultTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/BaseDataSourceTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/ConnectionPoolTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/PoolingDataSourceTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3BlobTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3CallableStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/ClientInfoTest.java
replace assertTrue with more appropriate asserts
=> refactor: replace some usages of assertTrue

CHANGELOG.md, docs/_posts/2017-05-04-42.1.0-release.md, release_notes.sh
This automates the generation of the _posts release file for the website using the CHANGELOG.md notes of Unreleased version, it also updates the CHANGELOG.md to stamp the new version there at the same time.
[skip ci]
=> chore: updates to CHANGELOG.md in release_notes.sh

pgjdbc/src/main/java/org/postgresql/ds/PGPooledConnection.java, pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java
make state of PGXAConnection as enum
=> refactor: state of PGXAConnection as enum

pgjdbc/src/main/java/org/postgresql/core/Utils.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/LogTest.java
If an argument is larger than 200MB it would overflow during escaping due to optimistic size estimation.
Change size estimation so it works for even larger arguments until StringBuilder crashes with negative size error.
=> fix: Avoid integer overflow for large arguments

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/XmlTest.java
The case is clear: the [specification](http://download.java.net/java/jdk9/docs/api/java/sql/SQLXML.html#getString--) says, calling getString() "consumes" the data and cannot be done multiple times on the same object. 
Here a simple fix.
=> don't attempt to read a SQLXML more than once (#964)

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimestampTest.java
This commit trims trailing zeros from the fractional seconds in timestamp strings returned under binary mode, where the fractional seconds used to be zero padded to 6 digits. This provides consistency in the returned timestamp strings under both forced and regular binary modes.
fixes #885
=> fix: trim trailing zeros in timestamp strings returned in binary mode

pgjdbc/src/main/java/org/postgresql/ssl/jdbc4/LibPQFactory.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/Jdbc4TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/LibPQFactoryHostNameTest.java
Qualify the type of the alternative name with ALT_DNS_NAME  to match libpq.
Previous implementation: https://github.com/pgjdbc/pgjdbc/pull/743
=> Support Subject Alternative Names for SSL connections

pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/util/HostSpec.java, pgjdbc/src/test/java/org/postgresql/test/jre8/core/Jre8TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jre8/core/SocksProxyTest.java, pgjdbc/src/test/java/org/postgresql/test/util/HostSpecTest.java
Fixes #975
When a `socksProxyHost` is configured, there needs to be an escape valve so that some hosts are resolved immediately. The Java Networking spec[1] does not specify such an option, but `socksNonProxyHosts` is used in the `sun.net.spi.DefaultProxySelector`. The behavior is mentioned in bug report 5001942[2]. 
This commit uses the `DefaultProxySelector.select` method to determine if the host should be resolved immediately, or deferred and resolved through the SOCKS proxy. This provides the best level of parity with the JVM internals.
[1] http://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
[2] http://bugs.java.com/bugdatabase/view_bug.do?bug_id=5001942
=> Added support for socksNonProxyHosts property

pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/SimpleDataSourceWithSetURLTest.java
Add setURL method to BaseDateSource in order to follow convention used in other DBMS drivers.
Improves JBoss support, allowing to configure XA data source to switch between various DBMS
drivers. Most of vendors use uppercase 'URL' parameter, contrary to PostgreSQL.
Resolves #250. Previous solution was reverted due to issue with tests.
=> feat: add setURL method to BaseDataSource

.travis.yml
Add test for extendedCacheEverything to track issue #955.
The replication is tested on other jobs, so is safe to remove it for 9.4 and use that to test extendedCacheEverything.
=> test: querymode extendedCacheEverything

pgjdbc/src/main/java/org/postgresql/largeobject/LargeObject.java, pgjdbc/src/main/java/org/postgresql/replication/PGReplicationStream.java
=> style: make PGReplicationStream, LargeObject implement AutoCloseable for Java 7+

pgjdbc/src/main/java/org/postgresql/core/PGStream.java
make PgStream implements Flushable
=> refactor: make PgStream implements Flushable

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, ubenchmark/src/main/java/org/postgresql/benchmark/statement/BindArray.java
The purpose of the getPGArrayType method is to get the array type for
a given element type. Let the TypeInfo implementation figure out how
to do that rather than appending "[]" to the element type name in
PgPreparedStatement setArray.
=> refactor: use TypeInfo getPGArrayType instead of munging type name

pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/ArrayTest.java
Fix #420.
Without the changes to PgArray, the new test fails for BinaryMode.REGULAR and passes for BinaryMode.FORCE.
=> fix: always return Short[] for java.sql.Array.getArray() on smallint[]

.travis.yml, pgjdbc/pom.xml, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/jre8/sasl/ScramAuthenticator.java, pgjdbc/src/main/java/org/postgresql/sasl/ScramAuthenticator.java
PostgreSQL 10 comes with SCRAM-SHA-256 support. This commit introduces
support for it.
Work is based on an external dependency, the SCRAM client library:
https://github.com/ongres/scram/
which is now imported as a dependency.
TODO:
- SCRAM client library will be improved, on its own.
Particularily, StringPrep support needs to be added. Final
version of pgjdbc will depend on v1.0
- Testing
- Probably macros to avoid this Java8-only code propagating to
Java < 8 versions of the driver
=> Add SCRAM-SHA-256 support

pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/Jdbc41TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/NetworkTimeoutTest.java
HikariCP logs a warning at connection pool startup when a driver is found to not support get/setNetworkTimeout() -- due to vulnerability to getting stuck during a network disruption or partition event.
Given our user-base of several hundred thousand users, the warning message has turned into a support burden, with users concerned about its meaning.  One solution would be to do away with the warning, but that doesn't really serve the user.
So, here is the implementation of said feature -- I should have done this a year ago out of self-preservation.
=> Fixes #638 Implement support for get/setNetworkTimeout().

pgjdbc/src/main/java/org/postgresql/core/v3/CompositeQuery.java
The Native SQL generation for the first composite query calls toString() instead of getNativeSql().
=> fix: first composite query not calling getNativeSql()

pgjdbc/src/main/checkstyle/checks.xml, pgjdbc/src/main/java/org/postgresql/PGConnection.java, pgjdbc/src/main/java/org/postgresql/PGRefCursorResultSet.java, pgjdbc/src/main/java/org/postgresql/PGStatement.java, pgjdbc/src/main/java/org/postgresql/largeobject/LargeObject.java
add MissingDeprecated into checkstyle + fix warnings
=> refactor: add MissingDeprecated into checkstyle

pgjdbc/src/main/java/org/postgresql/core/JavaVersion.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/core/JavaVersionTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
=> fix: avoid reflective access to TimeZone.defaultTimeZone in Java 9+

.travis.yml
Add coverage for Java 7 builds, make sync with after_n_builds.
=> test: add coverage to java 7

pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
simplify some methods in ConnectionFactoryImpl
=> refactor: simplify methods in ConnectionFactoryImpl

docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/gss/MakeGSS.java
The scenario where this is useful: we have users who use the OS-native Kerberos support to obtain a Kerberos ticket-granting ticket when they start using their workstation. The Kerberos TGT is stored in the OS-native credential cache (e.g. an API: cache on Mac OS X, or a FILE: or KEYRING: cache on Linux). They later want to use a SQL client application (e.g SQL Workbench/J) that uses this JDBC driver to talk to PostgreSQL, using GSS authentication with their existing Kerberos ticket.
Unfortunately there is no support in Oracle's Krb5LoginModule for reading Kerberos tickets out of API: or KEYRING: credential caches, it only supports file ccaches, so the usage of Krb5LoginModule to try and obtain Kerberos credentials throws an exception.
However, there is support in Oracle JDK 8 for using …
=> Make GSS JAAS login optional

docs/documentation/head/load.md
The documentation in head should reflect current best practice while still providing the historical background needed by developers who are maintaining older code. I think this documentation change covers the significant points
1. you no longer need to explicitly load the driver
2. the driver jar file must be on the classpath in order for the driver to load
3. the old way still works but isn't needed
=> docs - change load.md to reflect current practice

README.md
The "//[host][:port][/database]" portion of the URL regex does not accurately represent the URL variations that are actually accepted.
The proposed "[//host[:port]/][database]" does.
=> docs: fix the URL regex

README.md
postgresql-42.1.4 - DriverManager.getConnection("jdbc:postgresql:/", username, password) throws org.postgresql.util.PSQLException: FATAL: database "/" does not exist. The trailing slash is being interpreted as the database name. DriverManager.getConnection("jdbc:postgresql:", username, password) connects to the default port on localhost using the user's name as the database.
=> docs: fix no parameter connect string example

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimezoneTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/SetObject310Test.java
Previous behavior:
getTime(int), getTime(int, Calendar) kind of methods ensured that the resulting java.sql.Time
would render as 1970-01-01 ... in the given time zone (e.g. given Calendar and/or default TimeZone)
Note: the resulting Time object
E.g. if server was sending `1970-01-01 15:00:00 +0300` and `getTime(int, GMT+13)` was used by the client, then pgjdbc subtracted a day since otherwise the timestamp is equal to `1970-01-02 01:00:00 +1300` (note the date is 2).
New behavior:
for 'time with time zone' and 'timestamp with time zone' the value from the server is assumed to be
"instant" (i.e. absolute point in time), and no further adjustments is made to make the date part to be 1970-01-01.
For instance, `1970-01-01 15:00:00 +0300` is parsed as is (no matter which Calendar is provided …
=> fix: use 'time with time zone' and 'timestamp with time zone' values as is and avoid computation with user-provided/default Calendars

pgjdbc/src/main/java/org/postgresql/copy/PGCopyInputStream.java, pgjdbc/src/main/java/org/postgresql/copy/PGCopyOutputStream.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/CallableBatchResultHandler.java
replace some usages of initCause with appropriate constructor
=> refactor: replace some usages of initCause

pgjdbc/src/main/java/org/postgresql/copy/PGCopyInputStream.java, pgjdbc/src/main/java/org/postgresql/copy/PGCopyOutputStream.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/CallableBatchResultHandler.java
=> Revert "refactor: replace some usages of initCause"

pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3PGReplicationStream.java
Fix a bug with V3PGReplicationStream where the server may never
be able to send a CommandComplete message to the client because
the client's status update messages do not advance the received LSN.
This behavior can be reliably reproduced on a server where no
data changes are happening, so the only messages being sent from
the client are status updates and the only messages coming from
the server are keepalives. The LSN reported from the server keepalives
continues to advance, but the client reports a static
lastReceiveLSN, so the server never considers the client caught
up and never sends CommandComplete to trigger the client to shut down.
By updating lastReceiveLSN on keepalive messages, the expected
server CommandComplete and client Terminate messages are exchanged,
allowing the server …
=> fix: advance lastReceiveLSN on keepalive messages

README.md, build.properties, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/hostchooser/HostRequirement.java, pgjdbc/src/main/java/org/postgresql/hostchooser/HostStatus.java, pgjdbc/src/main/java/org/postgresql/hostchooser/MultiHostChooser.java, pgjdbc/src/test/java/org/postgresql/test/hostchooser/MultiHostTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/hostchooser/MultiHostsConnectionTest.java
The community has decided that the naming of replicas in any form
should be referred to as secondary or standby.
We have chosen to use the word secondary
This PR renames (hopefully) all of the uses of slave to secondary
=> prefer secondary over slave referring to standby or secondary servers

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/GetObjectTest.java
=> fix: avoid NPE from getObject(..., Date.class) and getObject(..., Calendar.class) on null timestamps

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
There is an issue in maven checkstyle project called [Issue #5207: add support for LITERAL_CASE and LITERAL_DEFAULT in LeftCurlyCheck](https://github.com/checkstyle/checkstyle/pull/5376) which fails to build wercker on pgjdbc project. 
I deleted unnecessary braces so the build could be stable.
=> chore: remove braces for LeftCurlyCheck issue checkstyle

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
By mistake I've corrected only one couple of braces. In this commit I tried to take into account all of them. 
I removed and replaced some additional braces in case scenarios that are also required for build to proceed. 
However, some braces were not removed and only displaced into other location otherwise it raises an exception of duplicated variable parameters: "Variable has been already defined in this scope"
Please refer to the following issue of the underlying problem : [LeftCurlyCheck](https://github.com/checkstyle/checkstyle/pull/5376)
=> chore: remove additional braces for LeftCurlyCheck checkstyle

pgjdbc/src/test/java/org/postgresql/test/jdbc2/DriverTest.java
java.sql.Driver's javadoc states " The driver should return "null" if it realizes it is the wrong kind of driver to connect to the given URL. This will be common, as when the JDBC driver manager is asked to connect to a given URL it passes the URL to each loaded driver in turn." (https://docs.oracle.com/javase/8/docs/api/java/sql/Driver.html#connect-java.lang.String-java.util.Properties-).
Add test for checking this behaviour.
=> test: check if url is not for PostgreSQL

pgjdbc/src/main/java/org/postgresql/util/HostSpec.java, pgjdbc/src/test/java/org/postgresql/test/util/HostSpecTest.java
Check the "socksProxyHost" system property not only for null, but also for emptiness
=> Fixes issue #1078

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DateStyleTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
Default PostgreSQL configuration is DateStyle='iso, dmy',
however just iso would be fine.
Note: PostgreSQL prints DateStyle value in upper case, and toUpperCase
was added just in case.
fixes #1080
=> fix: avoid connection failure when DateStyle is set to ISO

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/GetObject310Test.java
When fetching objects from an ResultSet, it would be convenient to be able to fetch timestamp columns as both LocalDateTime and LocalDate.
That enables me to write code like this:
```
user.setToDate(rs.getObject("ToDate", LocalDate.class));
```
instead of having to check for null everywhere:
```
LocalDateTime ldt = rs.getObject("ToDate", LocalDateTime.class);
user.setToDate(ltd == null ? null : ltd);
```
=> add support for fetching 'TIMESTAMP(6) WITHOUT TIME ZONE' as LocalDate

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/test/java/org/postgresql/core/ParserTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchedInsertReWriteEnabledTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpsertTest.java
=> fix: reWriteBatchedInserts=true causes syntax error with on conflict

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimestampTest.java
When Timestamp values with nanosecond values < 1000 are submitted as arguments to a PreparedStatement,
avoid formatting them with a trailing dot '.' after the seconds part. This fixes a regression introduced
with PR #896.
closes #1117
Implementation note: the rounding with `Math.round` is necessary to ensure consistent behavior when inserting a timestamp value inlined or as prepared statement argument:
This will insert `2000-02-07 15:00:00.000001`:
```
INSERT INTO testtable (col)
VALUES (timestamp '2000-02-07 15:00:00.000000789')
```
whereas this Statement
```
INSERT INTO testtable (col)
VALUES (timestamp ?)
```
will first format the timestamp as a string with microsecond precision and send that to the server. Without rounding, there would be no way to make both the `testSetTimestampWOTZ` …
=> fix: handle Timestamp values with fractional seconds < 1 microsecond correctly in PreparedStatement arguments

pgjdbc/src/main/java/org/postgresql/PGConnection.java
Update the JavaDoc to show that the return type is PreferQueryMode rather than boolean.
=> docs: fix JavaDoc for getPreferQueryMode()

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpdateableResultTest.java
=> fix: ArrayIndexOutOfBoundsException when using the same SQL for regular and updateable resultset

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/test/java/org/postgresql/core/ParserTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpsertTest.java
pgjdbc will avoid rewriting the query if a bind is identified after values(...)
That is ON CONFLICT... DO update set x=? is NOT rewrite-compatible, and update set x='default' is rewrite-compatible
"reported" here: https://stackoverflow.com/questions/47664889/jdbc-batch-operations-understanding/48349524?noredirect=1#comment84691562_48349524
=> fix: support insert ... on conflict...update for reWriteBatchedInserts=true

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/largeobject/BlobInputStream.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BlobTest.java
Hi,
I spotted an incorrect behaviour using LargeObject BlobInputStream mark() and reset() methods.
Both methods do not take the internal buffer in account.
- mark() actually marks the position after the last byte in the buffer
- reset() changes the large object position, but does not clear the buffer. Buffered bytes from the old position are still returned after reset() until the buffer is depleted.
Here is a suggested fix. The reset() method could be more sophisticated by checking wheter parts of the buffer could be reused.
=> fix: wrong data from Blob/Clob when mark/reset is used

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/core/Oid.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java, pgjdbc/src/test/java/org/postgresql/core/OidToStringTest.java, pgjdbc/src/test/java/org/postgresql/core/OidValueOfTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
timestamp, date, are sent as UNSPECIFIED, and pgjdbc did not verify the actual parameter types at parse time.
This might cause wrong results if the query was parsed with explicit type (e.g. setString(...)), and then re-executed with
TIMESTAMP parameter (timestamps are sent as UNSPECIFIED, thus pgjdbc silently accepted the statement even though it should reparse)
fixes #648
closes #674
=> fix: wrong results when a single statement is used with UNSPECIFIED types

CHANGELOG.md, docs/documentation/head/server-prepare.md, pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
Just in case: I have added `with x as (insert into rollbacktest(a, str) values(43, 'abc') returning ${cols})
select * from x` test case, and it does work "as expected".
That is it might produce `cached plan...` error in case it is using `returning *`. When that happens, pgjdbc could auto re-execute the statement (e.g. if no transaction was present) and it does overcome the error automatically. 
The PR depends on #1137
=> docs: improve documentation and tests for server-side prepared statements

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
Use a more complete list of keywords for Pg 8.2 - 8.4, return the correct list of keywords for PostgreSQL 9.0+ using pg_catalog.pg_get_keywords()
=> fix: improve DatabaseMetaData.getSQLKeywords()

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/main/java/org/postgresql/core/SqlCommand.java, pgjdbc/src/test/java/org/postgresql/core/ParserTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/CompositeQueryParseTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/GeneratedKeysTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/SqlCommandParseTest.java
pgjdbc ignored to add RETURNING to WITH queries even though it makes sense.
fixes #1104
=> fix: support generated keys for WITH queries

docs/documentation/head/java8-date-time.md
Fix typos
Only OffsetTime / TIME [WITHOUT TIME ZONE] should be OffsetTime WITH TIME ZONE ...
Inconsistent examples numerous
=> Fix typos in java8-date-time.md

pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java, pgjdbc/src/main/java/org/postgresql/util/Gettable.java, pgjdbc/src/main/java/org/postgresql/util/GettableHashMap.java, pgjdbc/src/main/java/org/postgresql/util/LruCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetMetaDataTest.java
Clients accessing very dynamic schemas can have issues with the
field metadata cache getting stale.  This change allows configuring the
databaseMetadataCacheFields property to 0 to disable the cache and
avoid these issues where necessary.  This behaviour was already
documented, however did not actually work as the codepath assumed
it could retrieve the fields from the cache.
=> fix: allow disabling field metadata cache

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
In ConnectionFactoryImpl.log function locally generates the logRecord
but doesn't set the loggerName of the current Logger, as a result
the log ignores the class or package level logging configuration
=> set the loggerName of the locally generated LogRecords (#1167)

CONTRIBUTING.md
Hi,
GitHub help links for contributing are broken This commit update the two links to point to new GitHub guides.
Thanks !
=> docs: fix link to GitHub documentation

codecov.yml
In .travis.yml there are actually 10 COVERAGE=Y
=> chore: update after_n_builds to 10

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/OuterJoinSyntaxTest.java
=> fix: support parenthesis in {oj ...} JDBC escape syntax #865

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimestampTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/SetObject310Test.java
PostgreSQL supports microsecond resolution only, so PgJDBC rounds
nanoseconds to micros. When that happens the number of seconds, minutes, etc
might change as well
fixes #1211
=> fix: adjust date, hour, minute, second when rounding timestamp

pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
Use long field for timeout to avoid unexpected "Query timeout must be a value greater than or equals to 0" when query timeout exceeds 2147483=Integer.MAX_VALUE/1000
fixes #1223
=> fix: support query timeouts exceeding 2147483 seconds (~25 days)

pgjdbc/src/main/java/org/postgresql/core/BaseQueryKey.java, pgjdbc/src/main/java/org/postgresql/core/CachedQuery.java, pgjdbc/src/main/java/org/postgresql/core/QueryWithReturningColumnsKey.java
LruCache uses .getSize to limit the size of the cache, so this method
should refrain from doing memory allocations.
closes #1226
=> perf: avoid BaseQueryKey.toString in CachedQuery.getSize

pgjdbc/src/main/java/org/postgresql/copy/CopyManager.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/main/java/org/postgresql/replication/PGReplicationConnection.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/ChainedCommonStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/sspi/NTDSAPI.java, pgjdbc/src/main/java/org/postgresql/sspi/NTDSAPIWrapper.java, pgjdbc/src/main/java/org/postgresql/util/Base64.java, pgjdbc/src/main/java/org/postgresql/util/MD5Digest.java, pgjdbc/src/main/java/org/postgresql/util/WriterHandler.java, pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java
Resolve a small number of warnings when generating the Javadoc
=> chore: add missing javadoc tags to avoid warnings

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/main/java/org/postgresql/core/UTF8Encoding.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/util/URLCoder.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DriverTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGPropertyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/BaseDataSourceTest.java
BaseDataSource did not properly encode url parameters, meaning that users could
not log in if their password contained illegal characters. The error can be
reproduced by setting the test user password to ';/?:@&=+$,' (a bunch of illegal
characters for query parameters).
DriverTest then failed because it did not encode the parameters either.
=> Encode url parameters

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
simplify constructor in PgConnection
=> refactor: simplify PgConnection.java

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/test/java/org/postgresql/core/ParserTest.java
add some tests on Parser#modifyJdbcCall
small optimization on Parser#modifyJdbcCall
remove support for version < 8.1 in Parser#modifyJdbcCall
=> perf: improve parsing performance of JDBC-style { call ...} calls

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DriverTest.java
The logger used in the driver has some calls to levels WARNING and SEVERE, this lower the level to FINE to make the logger quiet.
Changing SEVERE to WARNING is not enough, as WARNING is higher than INFO the default global logging level.
fixes #1009
fixes #1162
closes #1149
=> fix: logger should be generally quiet

docs/_posts/2017-02-20-42.0.0-release.md, docs/_posts/2017-05-04-42.1.0-release.md, docs/_posts/2017-07-12-42.1.2-release.md, docs/_posts/2017-07-14-42.1.3-release.md, docs/_posts/2017-08-01-42.1.4-release.md, docs/_posts/2018-01-17-42.2.0-release.md, docs/_posts/2018-01-25-42.2.1-release.md, docs/_posts/2018-03-15-42.2.2-release.md
This makes changelog consistent with "notable changes"
=> docs: use "PR 42" references instead of "PR#42" in the changelog

pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java
See http://www.postgresql.org/message-id/CAFgjRd3hdYOa33m69TbeOfNNer2BZbwa8FFjt2V5VFzTBvUU3w@mail.gmail.com
=> test: close of replication connection has not been fixed at backend side, so disable the test till 12.1

pgjdbc/pom.xml, pom.xml
This is a missing part of #1236
=> chore: update parent versions to 1.1.4 to enforce Javadoc warnings as errors

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/ArrayTest.java
Implement public void setNull(int parameterIndex, int t, String s)
Fixes #1159
=> fix: setNull for types not in java.sql.Types (e.g. uuid)

pgjdbc/src/main/java/org/postgresql/copy/CopyManager.java
Fixes a typo of "excausted" => "exhausted".
=> fix: Correct typo in CopyManager comment

docs/community/mailinglist.html, docs/development/website.html, docs/documentation/92/escaped-functions.md, docs/documentation/93/escaped-functions.md, docs/documentation/94/connect.md, docs/documentation/94/escaped-functions.md, docs/documentation/changelog.md, docs/documentation/head/thread.md, pgjdbc/src/main/java/org/postgresql/copy/CopyIn.java, pgjdbc/src/main/java/org/postgresql/copy/CopyOperation.java, pgjdbc/src/main/java/org/postgresql/core/VisibleBufferedInputStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/largeobject/LargeObject.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/ChainedCommonStreamBuilder.java, pgjdbc/src/main/java/org/postgresql/ssl/jdbc4/LibPQFactory.java, pgjdbc/src/main/java/org/postgresql/util/Base64.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseEncodingTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/NotifyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/ConnectionPoolTest.java, pgjdbc/src/test/java/org/postgresql/test/ssl/SingleCertValidatingFactoryTestSuite.java
Fixing typos is sometimes very hard. It's not so easy to visually review them. Recently, I discovered a very useful tool for it, [misspell](https://github.com/client9/misspell). 
This pull request fixes minor typos detected by [misspell](https://github.com/client9/misspell) except for the false positives. If you would like me to work on other files as well, let me know. 
```
$ misspell . | grep -v /translation/
docs/community/mailinglist.html:77:16: "transfered" is a misspelling of "transferred"
docs/development/website.html:30:56: "conjuction" is a misspelling of "conjunction"
docs/documentation/92/escaped-functions.md:18:41: "ther" is a misspelling of "there"
docs/documentation/93/escaped-functions.md:18:41: "ther" is a misspelling of "there" …
```
=> Fix typos detected by github.com/client9/misspell

pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
Postgres numeric column can store NaN value which is not convertable to BigDecimal. getBigDecimal() throws exception in this case. But when we call getObject() to retrieve the data we expect any type of object as return value. So it's convenient to return Float.NaN in this case.
Related DataGrip issue: https://youtrack.jetbrains.com/issue/DBE-5141
=> Let ResultSet.getObject() return Float.NaN in case of numeric NaN

pgjdbc/src/main/java/org/postgresql/replication/fluent/AbstractCreateSlotBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/ChainedCommonCreateSlotBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/logical/LogicalCreateSlotBuilder.java, pgjdbc/src/main/java/org/postgresql/replication/fluent/physical/PhysicalCreateSlotBuilder.java, pgjdbc/src/test/java/org/postgresql/replication/ReplicationSlotTest.java
With Postgres 10 it is possible to create temporary replication slots.
The Postgres JDBC Driver provides a DSL to create replication slots, but there was no option to declare the slot as temporary.
This PR extends the DSL by a withTemporaryOption method.
BREAKING CHANGE: AbstractCreateSlotBuilder has no parameterless constructor anymore
Closes https://github.com/pgjdbc/pgjdbc/issues/1305
The `AbstractCreateSlotBuilder` constructor now has a `BaseConnection` parameter which is required to check the server version in the new `withTemporaryOption` method.
=> feat: Extend ReplicationCreateSlotBuilder DSL to support temporary replications slots

pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGPropertyTest.java
=> fix: autosave being overwritten in BaseDataSource by setUrl

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
postgres considers tables to be composite types which
in very large schemas with lots of tables slows down
getTypeInfo.
This fix filters out tables from types
fixes #1301 
=> perf: ignore tables for PgDatabaseMetaData.getTypeInfo

CHANGELOG.md, docs/_posts/2018-08-27-42.2.5-release.md, pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/CopyDualImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3ReplicationProtocol.java
=> perf: fix 1ms per async CopyAPI (regression since 42.2.5)

pgjdbc/src/main/java/org/postgresql/copy/PGCopyInputStream.java, pgjdbc/src/main/java/org/postgresql/util/ReaderInputStream.java
=> fix: Incorrect return value for bytes [128-255] in stream.read

pgjdbc/src/main/java/org/postgresql/core/v3/replication/V3PGReplicationStream.java, pgjdbc/src/main/java/org/postgresql/replication/PGReplicationStream.java
Hi,
**TL;DR version**
Marking the fields holding the sequence numbers as `volatile` will allow the API user to call `setFlushedLSN(lsn)` and `setAppliedLSN(lsn)` (and also the getters) from a thread different than the thread doing the main loop. This is useful when doing a blocking `read()`, as it allows another thread to actually acknowledge an event as flushed/applied.
Without this change, one cannot combine `read()` and parallel processing+acknowledging of WAL events, as there is no guarantee that the updated values will be seen by the main replication loop.
**long version**
I'm working on a logical replication consumer implementation which forwards replication event to a queue service (RabbitMQ in this instance). The flow is as following:
1. The main loop consuming the replication …
=> Allow setFlushedLSN(lsn) and setAppliedLSN(lsn) from outside main loop

build.properties, pgjdbc/src/test/java/org/postgresql/test/hostchooser/MultiHostsConnectionTest.java
The `secondaryServerPort2` is misspelled in the `build.properties` file and do not match with the one used in `MultiHostsConnectionTest.java`. Also make `secondaryServer1` and `secondaryPort1` consistent in the naming.
=> test: fix wrong secondaryPort2 build property

pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
While testing some update to a VM for testing pgjdbc I noticed a bunch of errors in the server error logs for trying to drop missing objects as the test SQL was not using `... IF EXISTS ...`.
The first commit in the PR changes a bunch of the `dropXYZ(...)` methods in `TestUtil` to use `... DROP EXISTS ...` if the connection is not in a transaction. This matches the behavior in the comments around the drop statements. This also changes the method to *not* skip over non-transactional exceptions in the drop statements that are not due to missing objects such as a connection error or a dependency on the dropped object.
That last one (dependencies) lead to a bunch of broken tests that were previously passing because they were ignoring those errors. Here's an example:
``` …
```
=> Fix TestUtil.dropXyz(...) object not exists errors

README.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/core/OptionsPropertyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
Add support for custom `options` connection property. The property is [described in PostgreSQL documentation](https://www.postgresql.org/docs/8.2/libpq-envars.html); the motivation for its introduction was discussed in https://github.com/pgjdbc/pgjdbc/issues/222 (which is closed by this PR).
Implementation is straightforward: a new `PGProperty` is introduced to store `options` parameter value. It works the same way as any other `PGProperty`, thus it can be passed either in URL or in `Properties` object.
The documentation is updated to mention new connection property. Also, a note is added that when some property is present both in URL and in `Properties` object, the first one is prioritized.
`TestUtil` is updated so that it reads `options` property provided by testing environment.
A new …
=> Support custom 'options' connection property

.travis.yml
In fact, Zulu JDK 6 is used for Java 6, so `jdk: openjdk7` does not matter much
=> chore: use openjdk7 to boostrap Travis CI images for JDK 6

pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java, pgjdbc/src/test/java/org/postgresql/test/xa/XADataSourceTest.java
The PGXAConnection inner class call-filtering proxy ConnectionHandler
special cases calls to equals() by testing if the argument is itself
a proxy that should be unwrapped.
However it fails to test if the argument is null before calling getClass()
on it, resulting in an NPE like
java.lang.NullPointerException: null
at org.postgresql.xa.PGXAConnection$ConnectionHandler.invoke(PGXAConnection.java:139)
Fix by testing for null. While we're at it, also defensively check to ensure
there's exactly one argument to .equals. It's not sensible to pass more and
will error later anyway.
=> Fix NPE in PGXAConnection$ConnectionHandler.invoke() of .equals(null)

pgjdbc/src/main/java/org/postgresql/util/Base64.java
The method encode3to4(byte[], byte[], int) from Base64 has never been
used since [1].
[1] 034c2c3fecd39cd1513914d577921913c9810aa6
Signed-off-by: Mykola Nikishov <mn@mn.com.ua>
=> refactor: remove unused method encode3to4 from Base64

pgjdbc/src/main/java/org/postgresql/ssl/LazyKeyManager.java
The old code does ensure that the RAF is closed though it's a bit difficult to reason about it as it happens in two different places depending on where an exception occurs. I took a peek at it after seeing #1371.
This PR refactors loading of keyfile data in LazyKeyManager a bit so that IO happens in a separate method and there is only one close operation. This also has the positive side effect of removing one of the `// NOSONAR` tags.
=> refactor: Clean up loading of reading of keydata file in LazyKeyManager

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/SetObject310Test.java
The assertion in `SetObject310Test.testSetLocalDateTimeBc`  is
>   // -1997-06-30T23:59:59.999999 -> 1997-06-30 23:59:59.999999 BC
This is incorrect.  It is actually `-1996  == 1997 BC` because there is no year zero in AD/BC.
I used a `DateTimeFormatter` in the test to prove my case. This “fix” for this method is to fix `TimeStampUtils.appendDate` and stop using the proleptic year (aka `YEAR`) and start using the year of the era (aka `YEAR_OF_ERA`).
> BC `LocalDateTime` handling was previously incorrect as it didn't handle proleptic year conversion correctly.
=> Fixes `LocalDateTime` handling of BC dates

pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
This has resulted in avoiding the hang issue identified in issue #1403
* [*] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [*] Have you added an explanation of what your changes do and why you'd like us to include them?
* [*] Have you successfully run tests with your changes locally?
=> pgJDBC - StatementTest hangs in Windows 7 / 2012 / 2016

appveyor.yml
Add many more versions of postgres to test against
=> add matrix including master to test

pgjdbc/.editorconfig
add [.editorconfig](https://editorconfig.org/) with configuration for java files
It allows to specify some basic formatting settings which will be used across various editors and IDEs
=> chore: add .editorconfig

pgjdbc/src/main/checkstyle/checks.xml, pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/PGCopyInputStreamTest.java
add [EmptyStatement](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheck.html) checkstyle rule
=> chore: add EmptyStatement checkstyle rule

pgjdbc/src/main/checkstyle/checks.xml, pgjdbc/src/main/java/org/postgresql/ssl/PGjdbcHostnameVerifier.java, pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java, pgjdbc/src/main/java/org/postgresql/util/HostSpec.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/BaseDataSourceTest.java, pgjdbc/src/test/java/org/postgresql/test/ssl/SingleCertValidatingFactoryTestSuite.java
add StaticVariableName checkstyle rule + fix violations + simplify SSPIClient constructor
=> chore: add StaticVariableName checkstyle rule

pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
In addition to caching the underlying core type mapped to a comma,
cache their array equivalent types to avoid querying from the server.
Fixes #1415.
=> Add core type delimiters into cache for array type OIDs.

README.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGPropertyTest.java
Fixes #1407 
* [x ] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
1. [X ] Does your submission pass tests?
2. [X] Does mvn checkstyle:check pass ?
* [NO] Does this break existing behaviour? If so please explain.
* [NO] Have you written new tests for your core changes, as applicable?
* [YES] Have you successfully run tests with your changes locally?
=> Fix:save points causing server to run out of resources

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
=> use PostgreSQL column type name in error message

pgjdbc/src/main/java/org/postgresql/copy/CopyOut.java
This PR is being created because of violations found in CheckStyle's regression of Orekit during implementation of a bug fix.
PR: checkstyle/checkstyle#6529
Issue: checkstyle/checkstyle#6516
A bug was found in identifying javadocs where certain type of javadocs were missed from validation. The change produced new violations in Orekit as seen below:
````
[INFO] --- maven-checkstyle-plugin:3.0.0:check (default-cli) @ postgresql ---
[INFO] Starting audit...
[ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/copy/CopyOut.java:25: Line continuation have incorrect indentation level, expected level should be 4. [JavadocTagContinuationIndentation]
Audit done.
````
You can either accept this PR and not have an issue when you upgrade CS with this fix in the future,
or make …
=> fix: improper indentation for javadoc

pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
Travis build against HEAD fails due to some changes in automated foreign key naming. Ex: https://github.com/pgjdbc/pgjdbc/pull/1435#issuecomment-472724825_
This PR gives explicit names to the failing tests so that the results are consistent across versions.
Also, enhances the validation for that test to better validate the column order and row counts.
=> test: fix metadata test to use explicit PK/FK names

pgjdbc/src/main/java/org/postgresql/ssl/PGjdbcHostnameVerifier.java
Perhaps I'm missing something, but I don't think successful hostname validation should log on SEVERE/ERROR.
=> Fix logging level

pgjdbc/pom.xml
=> Update checkstyle to 8.18

pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/BatchedQuery.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/hostchooser/CandidateHost.java, pgjdbc/src/main/java/org/postgresql/jdbc/AbstractBlobClob.java, pgjdbc/src/main/java/org/postgresql/jdbc/EscapedFunctions.java, pgjdbc/src/main/java/org/postgresql/jdbc/EscapedFunctions2.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/main/java/org/postgresql/largeobject/BlobInputStream.java, pgjdbc/src/main/java/org/postgresql/largeobject/BlobOutputStream.java, pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java, pgjdbc/src/main/java/org/postgresql/util/Base64.java, pgjdbc/src/main/java/org/postgresql/util/PGtokenizer.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3BlobTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/Jdbc42CallableStatementTest.java
This PR is created because of violations found during regression testing after implementing (checkstyle)[https://github.com/checkstyle/checkstyle] ability to check multiple lines with comments and javadocs.
Issue: https://github.com/checkstyle/checkstyle/issues/5981
PR: https://github.com/checkstyle/checkstyle/pull/6388
Checkstyle PR changes produce new violations in pjdbc code, which are fixed in this PR.
=> style: remove extra empty lines

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
Fix a wrong relative cursor movement when a new calculated index is
negative (beyond the first row). According to the java-doc, in this
case the position leaves before the first row. Current implementation
of the 'relative' method delegates the movement to the 'absolute' method
which treats a negative index with respect to the end of the result set.
Example: assume we have next result set `{1, 2, *3, 4, 5, 6}` and we are
on the 3rd position. Move relative to `-6` which means a new index is 
`-3 (3 - 6)`. I expect the result set will be on the zero position with 
before-first status but actually we are on the 4th position (3rd from the end).
=> fix: improper relative cursor movement

pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/PreparedStatementTest.java
Yes.
Yes.
Nop.
Big decimal is set as string without cast, which is parsed as T_String instead of T_Float in postgres, resulting improper operator match thus conversion error.
Yes, see enclosed.
mvn test passed in local env.
=> Fix execution with big decimal in simple query mode.

pgjdbc/src/main/java/org/postgresql/core/Encoding.java, pgjdbc/src/main/java/org/postgresql/core/UTF8Encoding.java, pgjdbc/src/main/java/org/postgresql/util/ObjectFactory.java
2. [X] Does mvn checkstyle:check pass ?
- No it's only internals that are changing.
-----
Was taking a look at the internals of the string decoder to see what would be involved in supporting a "*Use system decoder if longer than X...*  (as a possible alternative to #1433) and noticed a couple minor things to clean up.
PR is split into three commits:
1. Typo correction for `s/weather/whether/`
2. Change the internal test function to validate if a given encoding is "ASCII Number Compatible" to be static.
3. Add a new `protected` (so internal only) constructor to Encoding that allows callers to specify if they're ASCII compatible. This allows the `UTF8Encoding` class to skip the ASCII number compatibility test on every construction as we know it'll …
=> Cleanup encoding

pgjdbc/src/main/java/org/postgresql/ds/PGConnectionPoolDataSource.java
=> Fix inconsistent javadoc for setDefaultAutoCommit

pgjdbc/src/main/java/org/postgresql/translation/messages_bg.java, pgjdbc/src/main/java/org/postgresql/translation/messages_ja.java, pgjdbc/src/main/java/org/postgresql/translation/messages_pt_BR.java, pgjdbc/src/main/java/org/postgresql/translation/messages_ru.java, pgjdbc/src/main/java/org/postgresql/translation/messages_sr.java, pgjdbc/src/main/java/org/postgresql/translation/messages_tr.java, pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java
=> fix: Error messages cannot be formatted

pgjdbc/src/main/java/org/postgresql/replication/LogSequenceNumber.java, pgjdbc/src/test/java/org/postgresql/replication/LogSequenceNumberTest.java
Regarding #1493:
added a Java 6 - compatible `compareTo` implementation for `LogSequenceNumber`, so it implements `Comparable<LogSequenceNumber>`.
=> Make LogSequenceNumber implement Comparable<LogSequenceNumber>

CONTRIBUTING.md
=> Fix maven coordinates

.travis/travis_build.sh, pgjdbc/pom.xml
This should fix Travis build for FEDORA_CI.
=> fix parent version in pgjdbc/pom.xml as well

docs/documentation/head/ext.md, docs/documentation/head/parameterstatus.md, docs/documentation/head/replication.md, docs/documentation/head/server-prepare.md, pgjdbc/src/main/java/org/postgresql/PGConnection.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ParameterStatusTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
Add a new `Map PGConnection.getParameterStatuses()` method that tracks the
latest values of all `GUC_REPORT` parameters reported by the server in
`ParameterStatus` protocol messages from the server. The map is read-only. A
convenience `PGConnection.getParameterStatus(String)` wrapper is also provided.
This provides a PgJDBC equivalent to the `PQparameterStatus(...)` `libpq` API
function.
Extensions may define custom GUCs that are set as `GUC_REPORT` when they
`DefineCustomStringVariable(...)` etc. This feature will properly handle such
GUCs, allowing applications to generate parameter status change messages in
their extensions and have them available to the JDBC driver without needing
round trips.
No assumptions are made about which server GUCs are `GUC_REPORT` or their
names, so it'll …
=> Expose parameter status messages (GUC_REPORT) to the user

pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ConnectTimeoutTest.java
The `ConnectTimeout` test expects an exception of type `SocketTimeoutException` when connecting to the unroutable address `10.255.255.1`. But at least on my host (Fedora 30, OpenJDK 1.8.0_212) the connection attempt actually throws `java.net.NoRouteToHostException`.
That is an entirely reasonable exception to throw in this case, but not the intent of the test.
I think the test is intended to time out while connecting to the unreachable address. But it relies on highly platform-dependent behaviour. In particular if there's any sort of negative caching in place the test may fast-fail:
```
~/.../2Q/pgjdbc (miscfix *%)$ time ping -c 1 10.255.255.1
PING 10.255.255.1 (10.255.255.1) 56(84) bytes of data.
From 61.245.136.1 icmp_seq=1 Packet filtered
--- 10.255.255.1 ping statistics ---
1 packets …
```
=> Make ConnectTimeout test accept NoRouteToHostException

.github/pull_request_template.md
Adds a note to the GitHub PR template to verify that any new test files have been added to an existing test suite to ensure they are actually included in automated CI testing.
If anybody has a better suggestion for the wording feel free to replace. The point is to remind contributors that that any new test additions must be included somewhere to actually run.
=> docs: Add note to GitHub PR templates about test suites

docs/documentation/94/resultset.md
=> docs: add note on behavior of ResultSet.getString() (#1286)

pgjdbc/pom.xml, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/jre7/sasl/ScramAuthenticator.java
Updated scram library version 2.0 with support for Java 7+ and standard SaslPrep implementation.
NOTE: Tests for pgjdbc-jre7 will fail due to missing changes in that repository. This PR requires that PR https://github.com/pgjdbc/pgjdbc-jre7/pull/6 get merged into pgjdbc-jre7.
=> Updated scram to version 2.0

pgjdbc/pom.xml, pgjdbc/src/main/feature/feature.xml
2. [X] Does mvn checkstyle:check pass ?
An explanation of the changes:
1. A karaf-maven-plugin configuraion added to the <build> of the pgjdbc POM
2. A template feature.xml file pulling in the karaf built-in feature transaction-api, which contains all of the postgresql OSGi bundle's runtime dependencies
3. The result of the build is a maven attachment to the jar artifact with type "xml" and classifier "features"
How to use the feature
1. From a maven project for an OSGi bundle that needs postgresql JDBC as a runtime dependency in apache karaf, add the following maven dependency:
```
<dependency>
<groupId>org.postgresql</groupId>
<artifactId>postgresql</artifactId>
<version>42.2.7</version>
<type>xml</type>
<classifier>features</classifier> …
```
=> Add an apache karaf feature for the PostgreSQL JDBC driver to fix #1552

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
This PR is to just to give an idea how to fix issue #1556, but never tested
=> Ensure isValid() will not last more than timeout seconds

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/GetObjectTest.java
Reverts inet type columns to default to returning their value as the text representation returned by the backend rather than parsing them as InetAddress values. This ensures that the mask value is not lost.
Also corrects the getObject(..., InetAddress.class) handling to split out the net mask and return only the address portion.
I've also updated the tests for inet data types to clean it up a bit, explicitly test getString() / getObject(), and add some additional edge cases (ex: "10.20.30.40/32" gets round tripped by the server to strip out the /32).
When (if?) we change the default return type to give a PGInet that test should fail and need to be updated. As I tend to lean toward backwards compatibility, I think we should leave the default as a text and if anything provide PGInet as a …
=> fix: Revert inet to return as a string and handle values with net masks

pgjdbc/pom.xml
Identified at https://github.com/checkstyle/checkstyle/pull/7088
Checkstyle is looking to remove some deprecated methods and our CI noticed that you are not on the latest maven-checkstyle-plugin which is still using some deprecated methods.
=> upgrade maven-checkstyle-plugin to 3.1.0

docs/documentation/92/query.md, docs/documentation/93/query.md, docs/documentation/94/query.md, docs/documentation/head/query.md
Fixes a Markdown formatting issue in the `query.md` section on restrictions with cursor-based `ResultSet`s.
=> Fix Markdown formatting issue

pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/ConnectionPoolTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/IsValidTest.java
This PR:
* Adds some static helpers to TestUtil for retrieving and killing backend connections.
* Cleans up IsValidTest to test/sleep in a loop after killing the connection to deal with the race condition that's periodically breaking testing. Also splits the transaction state tests into separate methods based upon the situation being tested.
* Clean up CopyTest and ConnectionPoolTest to use the new helper. Also changes these to use a non-privileged connection as super user is not required for killing processes owned by the same user.
=> Clean up some tests and fix IsValidTest race condition

pgjdbc/src/test/java/org/postgresql/test/ssl/LazyKeyManagerTest.java, pgjdbc/src/test/java/org/postgresql/test/ssl/SslTestSuite.java
3. [ ] Have you added your new test classes to an existing test suite?
=> Add simple test to make sure we can load a key

.github/pull_request_template.md, pgjdbc/src/test/java/org/postgresql/test/extensions/ExtensionsTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/hostchooser/MultiHostTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/Jdbc42TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jre8/core/Jre8TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/osgi/OsgiTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/ssl/SslTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/xa/XATestSuite.java
Fixes sort order for some test suites so we have cleaner diffs down the road.
Would be nice to have a checkstyle rule or equivalent to enforce this but at the moment we don't run any style checks on src/test/ anyway so I've just added a few words to the PR template.
=> Fix test suite order

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
release auto save points in batch processing in order to avoid out of
shared memory error
fix for the issue https://github.com/pgjdbc/pgjdbc/issues/1582
3. [-] Have you added your new test classes to an existing test suite?
* [-] Does this break existing behaviour? If so please explain.
* [-] Have you written new tests for your core changes, as applicable?
* [+] Have you successfully run tests with your changes locally?
=> fix: add release save point into execute with batch

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
Currently ```setSoTimeout```, ```setKeepAlive```, ```setReceiveBufferSize``` and ```setSendBufferSize``` are called after ```enableSSL```. In such a case SSL handshake uses only ```CONNECT_TIMEOUT``` and ignores other socket settings.
After few network splits we have found a lot of connections in next state for a very long time:
```
#15680 daemon prio=5 os_prio=0 cpu=47.27ms elapsed=76351.16s tid=0x00007f4abc0029e0 nid=0x4a93 runnable  [0x00007f4b4b7f6000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(java.base@11.0.3-internal/Native Method)
at java.net.SocketInputStream.socketRead(java.base@11.0.3-internal/SocketInputStream.java:115)
at java.net.SocketInputStream.read(java.base@11.0.3-internal/SocketInputStream.java:168)
at …
```
=> Perform ssl handshake after socket timeout and buffer size settings

docs/documentation/head/connect.md
on choosing the right cipher suite for client key
I should not recommend to use simple DES without any warnings: I'm supposed to be a security professional after all.
As neither me, and presumably nor others in the project really have more time to research the problem and test solutions, I think this warning is the minimum to sleep well.
* [x ] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
=> security notice and clarifications 

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/util/ByteConverter.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataTest.java
this replaces PR #910 as it was stale and easier to replace than fix. Original work by @zemian
=> fix: issue 716 getTypeInfo() may not return data in the order specified in Oracle documentation

pgjdbc/src/main/java/org/postgresql/copy/PGCopyOutputStream.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java
---
Implemented a fix for `PGCopyOutputStream.close()` throwing an exception after invoking `endCopy()` (issue #1574). The fix is done similar how `PGCopyInputStream` handles `close()`.
While writing the fix noticed that there is no sane way to determine whether the copy operation has ended or not. The `isActive()` method throws a `NullPointerException` after `close()` since `op` field is `null`, should return `false` like done in `PGCopyInputStream.isActive()`.
Besides that added a check for `flush()` so that it throws the same `IOException` with "This copy stream is closed." message like done in `write()` methods, instead of a `NullPointerException`.
=> Fix exception on PGCopyOutputStream.close() after endCopy() (#1574)

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
This updates the error message for COPY to STDIN / STDOUT commands that are *not* executed using the CopyManager API, i.e. via a regular `Statement.executeQuery("COPY ... TO STDOUT ...")`. The revised text for the error message is: 
COPY commands are only supported using the CopyManager API.
If anybody has a better suggestion feel free to chime in. I figure it's enough that someone who does run into the error can then search for "CopyManager" in the context of pgjdbc and hopefully find more info.
This PR does *not* update or remove the old value from the translation files. There's quite a few translations for the old message as it was in the code base for many years. I was considering updating the old message key for the old text so they continue to operate but decided that it's better to …
=> fix: Update error message for COPY commands executed using JDBC API

pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/gss/GssAction.java, pgjdbc/src/main/java/org/postgresql/gss/MakeGSS.java, pgjdbc/src/main/java/org/postgresql/util/PSQLException.java, pgjdbc/src/main/java/org/postgresql/util/ServerErrorMessage.java, pgjdbc/src/test/java/org/postgresql/test/core/LogServerMessagePropertyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
This patch keeps the old behavior but adds a new connection property to disable error detail. It defaults to "true" (the old behavior).
RFC for:
* A better name for the property?
* Whether we really need the single-argument constructor for `PSQLException(ServerErrorMessage)`? (i.e. is the constructor part of our public API, if not remove it to ensure we don't accidentally create it without the option)
* Whether the non-sensitive message should include more than just the SEVERITY + MESSAGE?
* Should we go to the next level and instead add a class-name style property that can customize the error, i.e. instantiate it as an object and call `.getMessage(ServerErrorMessage)` to get the text? (Seems like overkill but would give users option to format things however they'd like)
Consider this …
=> Add connection property to limit server error detail in exception exceptions

pgjdbc/src/main/java/org/postgresql/jdbc/PgSQLXML.java, pgjdbc/src/test/java/org/postgresql/jdbc/PgSQLXMLTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
=> fix: PgSQLXML setCharacterStream() results in null value 

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
=> fix: get correct column length for simple domains

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/CloseOnCompletionTest.java
=> fix: NPE as a result of calling executeQuery twice on a statement 

pgjdbc/src/main/java/org/postgresql/util/PGInterval.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/IntervalTest.java
this is a work in progress looking for comments on how to deal with things like months > 12 should we rationalize this before sending to the backend?
=> fix: pginterval to take iso8601 strings

pgjdbc/src/main/java/org/postgresql/PGConnection.java
Adds `cancelQuery()` to the extended public interface `PGConnection` to allow for issuing of cancels directly to connections rather than having to keep track of individual statements. The internals of the driver and the backend server already operate at a connection level (not a statement level) and this patch only exposes 
the existing cancelQuery() method publicly.
Exposing the `cancelQuery()` publicly is mainly a convenience thing as it's already part of all the concrete implementations. This is how how the server handles cancellation (i.e. at the connection, not statement, level) so I don't foresee any long term baggage associated with exposing this. The backend functionality is not going away.
There's been at least one other request for this in the past: #1084
Any thoughts on merging …
=> feat: Add cancelQuery() to PGConnection public interface

pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java
Fix the test so that cleanSavePoints TRUE and FALSE are tested
=> Actually test cleanSavePoints

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataTest.java
Currently getFunctions adds pg_function_is_visible to the sql looking for functions in all cases. If the user provides a schema but it is not on the search path no functions will be found. This seems counter-intuitive.
With this PR if the user provides a schema then that schema will be searched. If the schema is empty or null then the search path will be searched for the function.
=> fix: DatabaseMetaData.getFunctions should not limit the search to the search_path if the schema is provided

pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataHideUnprivilegedObjectsTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/Jdbc4TestSuite.java
This replaces PR#647 as it required considerable work to merge.
Original work done by Scott Langley @slangley
adds a connection parameter: hideUnprivilegedObjects defaults to false
=> feat: WIP Filter DatabaseMetaData using privileges for the user

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java, pgjdbc/src/test/java/org/postgresql/jdbc/NoColumnMetadataIssue1613.java
As described in https://github.com/pgjdbc/pgjdbc/issues/1613 and a previous PR https://github.com/pgjdbc/pgjdbc/pull/663, the driver throws null pointer exception when building the results for queries without column metadata, e.g. `SELECT <x> FROM <table name> <x>`,  where `<x>` is not a column name but an alias of the table. It should just return the whole table. (There might be other queries that can also reproduce this issue.)
However the above PR only fix one place where `field.getMetadata()` is null. There are four more places might cause the NPE. 
In this minor fix, we return "" as the columnName, schemaName, tableName if the metadata is null, and `ResultSetMetaData.columnNullable` for nullable.
3. [ ] …
=> fix: null pointer exception from PgResultSetMetaData when there's no column metadata

pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/util/ByteConverter.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
=> Add Binary Support for Oid.NUMERIC and Oid.NUMERIC_ARRAY

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
When autocommit is off and the first query in a transaction is a COPY, we were
sending a BEGIN using the extended query protocol. It was being permitted to
use named portals as well, ignoring prepareThreshold.
Fix by forcing simple query mode and marking the BEGIN as oneshot.
Fixes #1638
=> Prevent use of extended query protocol for BEGIN before COPY

pgjdbc/src/test/java/org/postgresql/jdbc/NoColumnMetadataIssue1613Test.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
"query has no results" error was being thrown since executeQuery is expecting a result set.
=> Fix test case by changing executeQuery to execute

pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java
PostgreSQL does not use the port in the service name which is consistent with the GSSAPI docs
=> fix: issue 1482 where the port was being added to the GSSAPI service name

pgjdbc/src/main/checkstyle/checks.xml, pgjdbc/src/main/java/org/postgresql/PGConnection.java, pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/ssl/DefaultJavaSSLFactory.java, pgjdbc/src/main/java/org/postgresql/ssl/LibPQFactory.java, pgjdbc/src/main/java/org/postgresql/ssl/MakeSSL.java, pgjdbc/src/main/java/org/postgresql/ssl/PGjdbcHostnameVerifier.java, pgjdbc/src/main/java/org/postgresql/ssl/jdbc4/LibPQFactory.java, pgjdbc/src/main/java/org/postgresql/util/WriterHandler.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ParameterStatusTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/BaseDataSourceFailoverUrlsTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/JsonbTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/XmlTest.java, pgjdbc/src/test/java/org/postgresql/test/ssl/SslTest.java
Related issue: https://github.com/pgjdbc/pgjdbc/issues/1652
=> style: Preparing for upcoming Checkstyle release 8.28

pgjdbc/src/main/java/org/postgresql/util/PGInterval.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/IntervalTest.java
I noticed issues with interval after upgrading to 42.2.9 from 42.2.8. It appears #1612 is the cause due to overloading issues. Some of the units were changed from int to byte. But I don't believe this is sound because intervals in postgres aren't guaranteed to be justified. For example, it's valid to have hour values greater than 24 hours:
```sql
select interval '900 hours';
-- 0 years 0 mons 0 days 900 hours 0 mins 0.00 secs
select justify_interval(interval '900 hours');
-- 0 years 1 mons 7 days 12 hours 0 mins 0.00 secs
```
I have unjustified intervals in my DB which is how I discovered this.
=> Fix interval overflow

README.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/util/PGPropertyMaxResultBufferParser.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/util/PGPropertyMaxResultBufferParserTest.java
Implementation of new property - maxResultBuffer. Enables max bytes read during reading result set.
Enable declare in two styles:
- as size of bytes (i.e. 100, 150M, 300K, 400G);
- as percent of max heap memory (i.e. 10p, 15pct, 20percent).
Also validates if defined size isn't bigger than enabled. Max possible size is 90% of max heap memory.
If maxResultBuffer property isn't declared, work of driver is not changed.
Commit made for Heimdalldata's request to solve memory problem during reading result set.
2. [x] Does mvn checkstyle:check pass?
Tests added for created PGPropertyMaxResultBufferParser. If necessary, tests for using made property with database can be made, but I would be thankful for information, where that tests could be implemented …
=> feat: Add maxResultBuffer property

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
When dealing with large PostrgeSQL databases of thousands of schemas, tens of thousands of tables and millions of indexes particular PgDatabaseMetaData methods have suboptimal implementation.
The pattern that was utilized in implementation used inner query on pg_catalog.pg_index in order to retrieve keys (information_schema._pg_expandarray(i.indkey) AS keys). Such implementation forced full table scan on pg_catalog.pg_index prior to filtering result set on schema and table name.
The optimization idea was to get rid of inner querry in order to let querry planner to avoid full table scan and filter out pg_catalog.pg_index rows prior to executing (information_schema._pg_expandarray(i.indkey) AS keys).
This optimization was tested on database AWS RDS db.t3.large having:
~2000000 rows in …
=> Metadata queries improvements.

pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
=> fix: actually use milliseconds instead of microseconds for timeouts

pgjdbc/src/main/java/org/postgresql/util/PGInterval.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/IntervalTest.java
Prevents getting a string with scientific notation by using an explicit format string. Uses a fixed precision which makes testing for the presence of decimal point and calculating a coefficient to get to microseconds unnecessary.
Fixes: #1677
=> fix: #1677 NumberFormatException when fetching PGInterval with small value

pgjdbc/src/main/java/org/postgresql/util/PGInterval.java
problem with checkstyle execution in master - https://travis-ci.org/pgjdbc/pgjdbc/jobs/642955505#L509
this blocks PR acceptance in checkstyle repo, as checkstyle CI use master HEAD of pgjdbc for regression testing.
2. [x] Does mvn checkstyle:check pass ? CI will show this.
=> minor: fix checkstyle violation of unused import

pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/VisibleBufferedInputStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
=> fix testSetNetworkTimeoutEnforcement test failure

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataCacheTest.java, pgjdbc/src/test/java/org/postgresql/util/TestLogHandler.java
This PR is our proposed fix for https://github.com/pgjdbc/pgjdbc/issues/1342
It adds a `TypeInfoCache.cacheSQLTypes()` method, which is called by `PgDatabaseMetaData.getTypeInfo()` to pre-populate the `pgNameToSQLType` cache, prior to calling `TypeInfoCache.getSQLType()` for each required type. It includes some refactoring so that we don't have to duplicate SQL and logic between `cacheSQLTypes()` and `getSQLType()`.
We've added a new `DatabaseMetaDataCacheTest` test suite. As the driver classes are tightly-coupled, the simplest way we found to check whether the cache is used is to inspect the debug log in the tests - not ideal - open to better suggestions :)
=> Fix Network Performance of PgDatabaseMetaData.getTypeInfo() method

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/jdbc/TimestampUtilsTest.java
When converting the Java `LocalTime` to PostgreSQL `time` value we have to consider the following:
- Java `LocalTime` has nano and `time` has micro precision
- PostgreSQL `time` max value is `24:00:00` while `LocalTime` is `23:59:59.999999999`
Conversion logic:
- truncate and round up when nanos >= 500
- rounding up all >=  `23:59:59.999999500`  to `24:00:00`
The current code intends to do this but it has a bug where it rounds too much. This PR fixes it.
I've added test for `toLocalTime()` which demostrates that these two methods are asymmetrical, you can lose/change information if you store and retrieve the time.
Example: 
```
timestampUtils.toLocalTime(timestampUtils.toString(LocalTime.parse("23:59:59.999999500")))) -> LocalTime.parse("23:59:59.999999999")
```
I'm open to suggestions on …
=> Fixing LocalTime rounding (losing precision)

README.md, docs/documentation/92/connect.md, docs/documentation/93/connect.md, docs/documentation/94/connect.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java
Alternative to #1504 (I'll close that one out in a min in favor of this). This PR is rebased atop the latest additions for new properties and docs. It passes checkstyle and tests. Should not have any end user change as the only thing modified is the declaration order of the PGProperty enums and I can't imagine the previous sort order being used for anything (it was effectively random anyway).
Summary of PGProperty changes:
* misc: Remove variadic constructor for PGProperty values and split across multiple lines - Longer term we're going to need to add some more structured information to the PGProperty enum so this commit gets rid of the convenience variadic constructor as it'd just be confusing down the road.
* perf: Cache PGProperty values in a map by name - I noticed one of the methods …
=> Cleanup PGProperty, sort values, and add some missing to docs

pgjdbc/pom.xml, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
When dealing with large PostrgeSQL databases of thousands of schemas, tens of thousands of tables and millions of indexes particular PgDatabaseMetaData methods have suboptimal implementation.
The pattern that was utilized in implementation used inner query on pg_catalog.pg_index in order to retrieve keys (information_schema._pg_expandarray(i.indkey) AS keys). Such implementation forced full table scan on pg_catalog.pg_index prior to filtering result set on schema and table name.
The optimization idea was to get rid of inner querry in order to let querry planner to avoid full table scan and filter out pg_catalog.pg_index rows prior to executing (information_schema._pg_expandarray(i.indkey) AS keys).
This optimization was tested on database AWS RDS db.t3.large having:
~2000000 rows in …
=> Metadata queries improvment

docs/documentation/head/connect.md
Document that in addition to the no-args and the deprecated String arg
constructors, a SocketFactory can, like the SSLSocketFactory
constructor, accept a Properties object, as the there otherwise is no
documented, non-deprecated way of customizing the factory.
=> docs: document SocketFactory(Properties)

pgjdbc/src/main/java/org/postgresql/copy/CopyIn.java, pgjdbc/src/main/java/org/postgresql/copy/CopyManager.java, pgjdbc/src/main/java/org/postgresql/copy/PGCopyOutputStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/CopyDualImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/CopyInImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java
Continuing https://github.com/pgjdbc/pgjdbc/pull/953, let's expose the garbageless writer to the COPY protocol as well.
2. [x] Does mvn checkstyle:check pass?
=> feat: Expose `ByteStreamWriter` in CopyManager

pgjdbc/src/main/java/org/postgresql/util/PGInterval.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/IntervalTest.java
=> fix: Always use . as decimal separator in PGInterval.

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
There is currently no way to distinguish between base tables and
partitioned tables in the response from `PgDatabadeMetaData.getTables`.
Fix this by adding `PARTITIONED TABLE` to the `tableTypeClauses` map and
thus the `TABLE_TYPE` field in the query in `getTables`. Also update a test
(`testPartitionedTables`) that was using `TABLE_TYPE` of `TABLE` to grab
partitioned tables.
This should close #1590. However, perhaps this could be considered a
breaking change for anyone using `getTables` and expecting partitioned
tables to show up for `.getTables(s, s1, s2, new String[]{"TABLE"})`?
* [✓] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [✓] Have you checked to ensure there aren't other open [Pull …
=> feat: add way to distinguish base and partitioned tables in PgDatabaseMetaData.getTables

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
fix: allow DatabaseMetaData.getColumns to describe an unset scale
getColumns returns a 0 for the scale of a Decimal or Numeric column when the
scale is 0, and when the scale is null. The caller can then not differentiate
between a 0 or a null without another query.
This change replaces the 0 in the ResultSet for scale with a null when describing
an unscaled Decimal or Numeric column. getInt will still convert the null to a 0,
but the caller can then use wasNull() to find out if the underlying value was 0
or null.
This addresses #1712.  It is a breaking change, but if the correct getter
(getInt) is used for the column, there is no difference. Other getters may behave
differently.
Signed-off-by: crwr45 <charlie.wheelerrobinson@gmail.com>
2. [x] Does …
=> fix: allow DatabaseMetaData.getColumns to describe an unset scale

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataHideUnprivilegedObjectsTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataTest.java
Currently the `PGDatabaseMetaData.getProcedures()` method returns both
procedures and functions. This made sense prior to PostgreSQL11, but now
actual procedures can be created instead of just functions, and pgjdbc
has an added `getFunctions()` method to distinguish between the two. For
only PostgreSQL version 11 and onward, this will make `getFunctions()`
return only functions and `getProcedures()` return only procedures.
I believe this closes #1340 and closes #1629, which both seem to essentially be
the same thing?
* [✓] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [✓] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [?] Does this break …
=> fix: getProcedures returns only procedures (not functions) for psql11+

pgjdbc/pom.xml
perf: upgrade maven-checkstyle-plugin to 3.1.1
upgrade maven-checkstyle-plugin to newest version
=> upgrade maven-checkstyle-plugin to 3.1.1

docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchExecuteTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchFailureTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/MiscTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/TransactionTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3SavepointTest.java, pgjdbc/src/test/java/org/postgresql/test/xa/XAPrepareFailureTest.java
Hopefully, the server would fix the error in the future.
See discussion in pgsql-hackers: https://www.postgresql.org/message-id/b9fb50dc-0f6e-15fb-6555-8ddb86f4aa71%40postgresfriends.org
fixes #1697
For documentation purposes: the feature will be enabled by default.
It can be disabled by setting `raiseExceptionOnSilentRollback=false` connection property.
Sample failure:
```
org.postgresql.util.PSQLException: The database returned ROLLBACK, so the transaction cannot be committed. Transaction failure cause is <<ERROR: savepoint "jdbc_savepoint_1" does not exist>>
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2191)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316)
at org.postgresql.jdbc.PgConnection.executeTransactionCommand(Pg …
```
=> fix: convert silent rollbacks into exception if application sends commit command

pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGPropertyTest.java
Adds a test to check that any new enum values for PGProperty are in sorted order and if not gives a helpful message:
```
Failed tests: 
PGPropertyTest.testSortOrder:86 PGProperty names should be sorted in ascending order: ASSUME_MIN_SERVER_VERSION < AUTOSAVE
```
Also fixes one value that apparently was not in the right order. 
Should be useful to keep things tidy going forward.
=> test: ensure PGProperty entries are declared in ascending order

docs/documentation/head/connect.md
Hi team! I noticed some merge conflict markers in the published documentation at <https://jdbc.postgresql.org/documentation/head/connect.html>, here's a fixed version that also corrects an "if" that should be an "in" in the same paragraph.
=> Remove merge aritfacts and fix a typo

pgjdbc/src/main/java/org/postgresql/translation/messages_ru.java, pgjdbc/src/main/java/org/postgresql/translation/ru.po
=> Fix I/O error ru translation

docs/download.md
docs: Remove a reference to a missing tag
The "Supported versions" leads to a missing section. Cleanup proposed.
=> docs: remove Supported Versions from downloads page

docs/documentation/head/connect.md
This updates the documentation about how to connect using SSL and the key format requirements.
- reflect the filenames the user likely needs
- adds `-nocrypt` flag to prevent driver from attempting to ask the user for a password
=> Updated openssl example command

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataTest.java
Fix issue (#1771) to return only functions in PgDatabaseMetaData.getFunctions()
- This is a breaking change
- Locally tested with Version 10.12 and 12.2
=> Fix issue PgDatabaseMetaData.getFunctions()

.github/pull_request_template.md
GitHub PR template has the old maven checkstyle commands. This fixes it to reference gradle.
=> fix: Update checkstyle command in PR template to reference gradle

docs/documentation/head/server-prepare.md
=> fix documentation with ordered list to be displayed correctly

CHANGELOG.md
This updates the latest changelog entry to clean up some formatting and add links to the fix commit in the latest changelog entry. The other commit also fixes a missing bold heading on an older entry.
Related, would have been nice if the merge commit for the fix had a better title. Seeing "*Merge pull request from GHSA-37xm-4h3m-5w3v*" isn't particularly descriptive when you're scanning commit headings.
Not worth rewriting history for it, but going forward would be good to either rebase and add the actual commits for PRs (if they're individually relevant) or manually update merge titles so they reflect something meaningful at merge time (if they're a bunch of commits that only make sense in tandem).
=> Fix some changelog formatting and add link to XXE fix

docs/documentation/head/connect.md
change the documentation by completing documentation with parameter that
didn't exist
the change is due to https://github.com/pgjdbc/pgjdbc/issues/848
=> docs: change add readOnlyMode on connect.md documentation

pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ConnectionTest.java
fixes #1808 
Use the timeouts and settings from the existing stream after changing the underlying socket to SSL
=> fix: New PGStream constructor which copies settings from old pgstream

pgjdbc/src/test/java/org/postgresql/test/ssl/SslTest.java
This validates that different gssEncMode values do not impact connectivity
when gss is not configured at the server-side.
=> tests: add gssEncMode to SslTest

pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyLargeFileTest.java, pgjdbc/src/test/java/org/postgresql/test/util/StrangeInputStream.java
The messages should be printed only in case of failure:
```
Using seed = 1595149058158 for StrangeInputStream. Set -DStrangeInputStream.seed=1595149058158 to reproduce the test
Using seed = 1595149058580 for StrangeInputStream. Set -DStrangeInputStream.seed=1595149058580 to reproduce the test
Using seed = 1595149059017 for StrangeInputStream. Set -DStrangeInputStream.seed=1595149059017 to reproduce the test
Using seed = 1595149059459 for StrangeInputStream. Set -DStrangeInputStream.seed=1595149059459 to reproduce the test
Using seed = 159514
```
=> test: reduce stdout verbosity of CopyLargeFileTest

.github/workflows/buildcache.yml, .github/workflows/main.yml, .travis.yml, .travis/travis_build.sh, build.gradle.kts, gradle.properties, pgjdbc/build.gradle.kts, settings.gradle.kts
This PR adds caching to CI jobs, and it collects `Gradle Build Scan` for some of the jobs.
1) [Gradle Build Cache](https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_configure) caches task outputs (e.g. compilation results, Javadoc, Checkstyle, etc. That means it could download task output from the remote build cache (see `FROM-CACHE` task status).
Remote cache is populated by GitHub Actions / Travis CI jobs. Otherwise, it is used in a read-only mode.
2) [Gradle Build Scan](https://guides.gradle.org/creating-build-scans/) is a detailed report on the build execution. I've added its collection for certain jobs. For instance, `Ubuntu, PG latest (JDK 8)` Actions CI job.
See the following at the end of `Test` step:
BUILD SUCCESSFUL in 6m 27s
14 actionable tasks: 11 …
=> Build cache

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/SocketTimeoutTest.java
fixes #1816 
I have added a failing test for the `socketTimeout` and then made the required changed to `ConnectionFactoryImpl` to make sure the `socketTimeout` is actually set using the `setNetworkTimeout()` method.
One thing I am not sure about, is the fact that the `pgInput` may be recreated when switching to SSL. This requires `ConnectionFactoryImpl` to re-set the `socketTimeout`, but it may be better if `PGStream` makes sure it keeps the `pgInput.timeoutRequested` state when it recreates `pgInput`. But that would require changes in two places (`PGStream.changeSocket()` and `PGStream.setSecContext()`) which does not seem to great either.
I ran the tests and I had no new test failures. I was unable to run the replication tests as it seems the suggested docker-compose file does not have …
=> fix: make sure socketTimeout is enforced

pgjdbc/src/main/java/org/postgresql/ssl/LibPQFactory.java
check for the most common PKCS-12 extensions (.p12, .pfx) and assume
PKCS-8 if these do not match
closes #1819
=> fix: assume PKCS-8 SSL key format by default (#1819)

docs/documentation/head/connect.md, docs/documentation/head/ssl-client.md
document differences between how PKCS-8 and PKCS-12 keyfiles are
handled, and when the sslcert setting has an effect
**NOTE:** This change describes and depends on #1832. I've assumed the release version of these changes would be 42.2.16, but if not, that needs to be adjusted in the text.
=> docs: touch up SSL keyfile documentation

.github/workflows/buildcache.yml, .github/workflows/main.yml
It unlocks fine-grained remote build cache with GitHub Actions backend (=faster builds), and it adds error markers (e.g. compilation errors right in the commit diffs)
See https://github.com/burrunan/gradle-cache-action#gradle-cache-action
=> chore: delegate Gradle execution to gradle-cache-action

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/jdbc/ArrayEncoding.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ArrayTest.java
* [ x] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
All binary array representations changing to be 1 based, which matches the string representation.
* [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x ] Have you written new tests for your core changes, as applicable?
* [x ] Have you successfully run tests with your changes locally?
=> Binary array index

CHANGELOG.md, docs/_posts/2020-01-30-42.2.10-release.md, docs/_posts/2020-03-31-42.2.12-release.md, docs/_posts/2020-06-04-42.2.13-release.md, docs/_posts/2020-08-14-42.2.15-release.md, docs/_posts/2020-08-20-42.2.16-release.md, pgjdbc/src/main/java/org/postgresql/core/Oid.java, pgjdbc/src/main/java/org/postgresql/jdbc/ArrayDecoding.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/EnumTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/JsonbTest.java
```
enum[] => String[]
jsonb[] => String[]
json[] => PGobject[]
```
fixes #1876
=> fix: make enum, json, and jsonb array result classes to be the same as 42.2.14 and earlier

pgjdbc/build.gradle.kts
Currently we have no automated way to test this
=> fix:remove osgi from karaf fixes Issue #1891

pgjdbc/build.gradle.kts, pgjdbc/src/main/java/org/postgresql/jdbc/GSSEncMode.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java, pgjdbc/src/main/java/org/postgresql/util/PGtokenizer.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/util/PGtokenizerTest.java
=> Pre release42.2.17

pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java
I'm working on adding support for procedure OUT parameters to the JDBC driver. More on that later. In the meantime, while I was playing around with various ideas, I noticed that the parameters of type `void` are sent to the server with a payload value of `"null"` as a string. This seems a bit strange and wasteful. I suggest to change this to a real null value.
I looked up the original commit where this came in (ccc8f4c37), but didn't see any explanation there either. Perhaps it wasn't ever questioned.
=> fix: send type void parameters as null value

.travis.yml, buildSrc/build.gradle.kts
Let's see what's inside /home/travis/.gradle/caches/modules-2/files-2.1/org.apache.bcel/bcel/6.0/7d08bcac4832f81467d3e2ca5bd58ad627288656/bcel-6.0.jar
=> chore: remove broken files from .gradle cache folder

packaging/rpm/postgresql-jdbc.spec.tpl
This dependency is no longer needed for package build
=> chore: remove dependency on java-comment-preprocesor from postgresql-jdbc.spec.tpl

pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
This is more stable, and has the added benefit of fixing #1948.
I'd like to remove the pgNameToSQLType map too, but that's used for the public api of getPGTypeNamesWithSQLTypes() - I'm not certain I can just remove that and be done with it...
- I believe so
- possibly has overlap with #914 
- It alters the API of TypeInfoCache to prefer OID type lookups over named lookups, to correctly determine the type of data of which the OID is known, and only a qualified path is known (e.g. off-path types) 
- yes
=> Rework sql type gathering to use OID instead of typname.

pgjdbc/src/main/java/org/postgresql/copy/PGCopyOutputStream.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java
This PR fixes #1777 
It's just a fix for the out of order writes and an additional test for the corrected functionality. It does not deprecate the existing copy classes or add new replacements. We can follow up with that in a subsequent release.
=> Fix PGCopyOutputStream out of order writes

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/jdbc/ConnectionValidTest.java
The usage of `setQueryTimeout();` with the same value as the `setNetworkTimeout();` is blocking the current transaction timeout.
The timeouts are blocking each other with this approach.
=> isValid() timeout should not be blocked

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/jdbc/BitFieldTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
This PR is to fix issue #892. I spent some time reading the code, and to fix the issue I decided to comment out the line of code that adds the bit data type to the types array in TypeCacheInfo. I had two reasons for it: 1. The bit field is not really in a boolean field, according to the docs it is a string of 1s or 0s. 2. The driver should be consistent in the way it handles bit and varbit fields. There is also another issue #908 related to bit fields but I think this is another discussion. For now I attempted to fix the exception that occurs when ResultSet getObject on a bit field. I created a test …
=> Fixed issue #892

pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java
Its a checkstyle indentation changes for annotation array initialization that is coming with merging PR checkstyle/checkstyle#8083
please see the diff report run on latest changes with checkstyle/checkstyle#8083 : https://abhishek-kumar09.github.io/github-actions-report-fetch/
=> style: fix annotaion array initiliazation indent according to checkstyle new check changes

benchmarks/src/jmh/java/org/postgresql/benchmark/encoding/UTF8Encoding.java, pgjdbc/src/main/java/org/postgresql/core/ByteOptimizedUTF8Encoder.java, pgjdbc/src/main/java/org/postgresql/core/Encoding.java, pgjdbc/src/main/java/org/postgresql/core/OptimizedUTF8Encoder.java, pgjdbc/src/main/java/org/postgresql/core/Utils.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/Portal.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java, pgjdbc/src/main/java/org/postgresql/jdbc/ArrayDecoding.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/ssl/SingleCertValidatingFactory.java, pgjdbc/src/main/java/org/postgresql/util/ReaderInputStream.java
Use [StandardCharsets](https://docs.oracle.com/javase/8/docs/api/java/nio/charset/StandardCharsets.html) constants rather than encoding names as strings.
=> improv: Standard charsets

pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataCacheTest.java
populate the "real" types into the map to avoid case conversions to
check for alternate representations.
populate new mappings to optimize future use
=> improv: type alias handling in TypeInfoCache

CHANGELOG.md, build.gradle.kts, gradle.properties, pgjdbc-jre6/gradle.properties, settings.gradle.kts
This prevents unwanted method calls, and it ensures the produced bytecode is parseable.
=> Verify code via forbidden-apis (jdk-internal and jdk-non-portable signatures)

gradle/wrapper/gradle-wrapper.properties
=> chore: bump gradle 6.3 -> 6.7.1

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
Due to issue https://github.com/checkstyle/checkstyle/issues/5711 some violations in the Javadoc were not reported.
This PR is to pass validation with the new Checkstyle version.
No changes in the code or docs, only some new whitespases.
=> chore: javadoc changes in PgResultSet.java to pass upcoming checkstyle version

pgjdbc/src/main/java/org/postgresql/Driver.java
Due to issue https://github.com/checkstyle/checkstyle/issues/5711 some violations in the Javadoc were not reported.
This PR is to pass validation with the new Checkstyle version.
No changes in the code or docs, only some new whitespases.
=> chore: javadoc changes in Driver.java to pass upcoming checkstyle version

.github/workflows/cancel_actions.yml
It should reduce CI load when PR is updated often.
=> chore: cancel stale workflows in GitHub Actions CI

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/copy/PGCopyInputStream.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/PGCopyInputStreamTest.java
2. [X] Does `./gradlew autostyleCheck checkstyleAll` pass ?
###
Fixes #2016.
Actual fix is one line, the rest is cleaning up the tests and adding some new ones to catch this behavior.
Having read through that PGCopyInputStream class a bit more, I really don't like the internals. Half the methods have variables that shadow the private members and it's pretty confusing to understand what it's trying to do. To keep this PR simple I haven't touched any of it here, but I'm planning on submitting a separate PR that eventually cleans that up. Maybe we should deprecate the CopyOut interface half of those classes first though.
=> Fix PGCopyInputStream readFromCopy() returning last row twice and add tests

pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
When creating LruCache instance, integer arithmetic is used to convert
from megabytes to bytes, even though LruCache takes a long value.
=> fix: potential overflow when reading cache sizes

pgjdbc/src/main/java/org/postgresql/ssl/PKCS12KeyManager.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java
The checkstyle has done some major changes for Indentation, due to this some part of the code may fail when checked against the checkstyle ruleset. 
This PR is about those changes, have tried to change the code to follow the checkstyle configuration written by pgjdbc more accurately.
The changes by checkstyle will affect the pgjdbc repo when their new release will be out. If merged now, the ci-cd pipelines may fail temporarily.
**PR references in checkstyle that introduces these changes:**
https://github.com/checkstyle/checkstyle/pull/9079, https://github.com/checkstyle/checkstyle/pull/9092
=> style: Change code style to follow checkstyle configuration more accurately

.travis/travis_install_head_postgres.sh, .travis/travis_install_postgres.sh, CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/jre7/sasl/ScramAuthenticator.java, pgjdbc/src/test/java/org/postgresql/jdbc/ScramTest.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java
Using NO_PREPARATION the handling of spaces was incorrect, the driver should use SASL_PREPARATION.
Fixes: #1970 
Fixes: #2000
=> fix: Use SASLprep normalization for SCRAM authentication

pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java, pgjdbc/src/test/java/org/postgresql/test/util/StrangeProxyServer.java
If we set a socket timeout on `PGStream`'s socket, but don't set `PGStream.pgInput.timeoutRequested` to `true`, then `PGStream.pgInput` will ignore SocketTimeoutExceptions ([VisibleBufferedInputStream.java#L169](https://github.com/pgjdbc/pgjdbc/blob/0dbc6078b98215f11413a8b0f3a15a7c08180a29/pgjdbc/src/main/java/org/postgresql/core/VisibleBufferedInputStream.java#L169)) and the timeout effectively doesn't work.
`PGStream.setNetworkTimeout()` sets both the timeout and the `timeoutRequested` field.
=> fix: properly set cancel socket timeout

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/jdbc/ConnectionValidTest.java
The usage of `setQueryTimeout();` with the same value as the `setNetworkTimeout();` is blocking the current transaction timeout.
The timeouts are blocking each other with this approach.
This is a cherry-pick of #1943 since it was not back-ported.
=> isValid() timeout should not be blocked (cherry-pick of #1943)

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
This pull request wraps the statements executed during startup inside a transaction.
This is important in pool-by-transaction scenarios in order to make sure that all the statements reaches the same connection that is being initialized. Since these are `SET` statements their changes persists outside the transaction scope, but we do receive the `Z????T` messages from the server.
This should only be considered for 42.3.
=> Group startup statements

pgjdbc/src/test/java/org/postgresql/replication/ReplicationConnectionTest.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java
2. [X] Does `./gradlew autostyleCheck checkstyleAll` pass ?
-------
Adds helpers to wait for a terminated process to exit by repeatedly checking `pg_stat_activity` in a loop for up to five seconds. This needs to be done everywhere that we call `pg_terminate_backend(...)` as it only sends the termination signal without waiting. That makes a race condition for anything that is subsequently testing against the terminated process. Ex: https://github.com/pgjdbc/pgjdbc/pull/1087#issuecomment-798700040
Rather than have to remember to add the `waitForBackendTermination(...)` everywhere that we issue a terminate, I've made it the default and renamed the original method to `terminateBackendNoWait(...)`.
Hopefully this gets rid of some CI gremlins...
=> Change TestUtil.terminateBackend(...) to wait for terminated process to exit

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpdateableResultTest.java
Fix for #1975 
* fix: make sure the table have defined primary keys when using updateable resultset
* test: add test for updateable resultset without primary key
=> fix: make sure the table have defined primary keys when using updateable resultset

.github/workflows/main.yml
Looks like #2096 / d6ef27ab6d91b305f028079f0c0d26ef420e7c0e broke CI to run only on the self-hosted runners. I think it's because the YAML config works by overriding the `os` tag rather than merging the values as list. Not sure if that should be an error or if it's a "feature" of YAML.
Comparing the CI matrix for the PR I submitted to fix the login time https://github.com/pgjdbc/pgjdbc/runs/2410396955 and the CI matrix this one https://github.com/sehrope/pgjdbc/actions/runs/774372965 and you'll see the latter has twice as many jobs.
This PR hopefully fixes things. For now I just replaced the lists inline but may be worth a second look later to run some parts (e.g. checkstyle or the checker framework) only on ubuntu-latest as they're source based and I don't expect anybody cares about …
=> test: Fix GitHub actions os matrix to use inline arrays

.github/workflows/buildcache.yml, .github/workflows/main.yml, appveyor.yml
Cleans up the GitHub Actions a bit to skip CI if the only changes are docs or markdown changes. Per the GitHub docs, `paths-ignore` will skip the action if all the changed files in the diff match those glob patterns.
=> test: Add paths-ignore to GitHub actions to skip on doc only changes

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/main/java/org/postgresql/core/SqlCommandType.java, pgjdbc/src/test/java/org/postgresql/core/ParserTest.java
When trying to create or alter a table that includes a foreign key constraint and an `ON DELETE` or `ON UPDATE` clause, the parser incorrectly marks the `CommandType` as `DELETE` or `UPDATE`, respectively.  Combined with a `returningColumns` of `{"*"}` (which is the default when just passing in the `autoGeneratedKeys` flag to `execute` in `PgStatement`) this causes a `RETURNING` clause to be added where it is invalid.
This PR adds four test cases showing the issue.
This PR also adds two new `CommandType` values for `CREATE` and `ALTER` to detect this scenario and prevent the `RETURNING` clause from being added. This is my first PR to this project and while the tests are passing, there may be a better implementation.  I defer to the more seasoned contributors.
I want to add that while …
=> RETURNING clause mistakenly added to CREATE and ALTER table statements

docs/documentation/head/resultset.md
Replace U+3000 character ("ideographic space") with a regular space in Markdown documentation file.
(This can lead to build failures for example when creating a PDF of the documentation.)
=> style: fix Unicode junk

pgjdbc/src/main/java/org/postgresql/ssl/jdbc4/LibPQFactory.java
* [Yes] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [Yes] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [No] Does this break existing behaviour? If so please explain.
These changes are with respect to [Issue](https://github.com/checkstyle/checkstyle/issues/9941), [PR](https://github.com/checkstyle/checkstyle/pull/9942) of the checkstlye project. Only minor changes have been done as wrecker was failing on pgjdbc project.
=> fix: Fixing the order of javadoc tags

.github/workflows/omni.yml
Adds action inputs to customize gradle arguments and filter the generated matrix.
Also adds uploading of code coverage step at the end of the omni ci action. It's set to execute only if the gradle args actually include `jacoco`. Code coverage is enabled by default so the daily scheduled executions should give us a nice history as well.
By default the matrix filters allow the entire matrix as it's intended to be executed once per day on the full set. Manual dispatches to start the omni action can filter whatever subset they want:
This let's you do things like "*Only run on PG version 11*", "*Only run on JDK version 11*", or "*Only run on Zulu with SCRAM disable*".
=> Add code coverage and matrix filters to omni action

CHANGELOG.md
First commit syncs the latest CHANGELOG from release/42.2.20 into master. It also cleans up the tag lists at the bottom of the file as the ones in release/42.2.20.
The next two commits add entries for two fixes that went in since the last release. I think this should bring us up to date so anything new can actually be added in the right place.
@davecramer @vlsi Can one of you eyeball this?
=> Sync CHANGELOG from latest release into master

CHANGELOG.md, README.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/core/BaseConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/jdbc/AbstractArraysTest.java, pgjdbc/src/test/java/org/postgresql/test/core/LogServerMessagePropertyTest.java
=> Avoid leaking server error details through BatchUpdateException when logServerErrorDetail=false

.github/workflows/omni.yml, docker/docker-compose.yml, docker/scripts/entrypoint.sh, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseEncodingTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/CharacterStreamTest.java
First commit fixes the quoting in some default docker-compose environment values so that they're actually disabled. Second disables some more server settings by default that we don't need in the test environment: autovaccum and track_counts
The rest of the commits clean up some more tests to use temp tables. I took at a peek at these tests in particular because I noticed they were randomly hanging during CI runs. 
For example the DatabaseEncodingTest was randomly taking *30+ minutes* to run: https://github.com/pgjdbc/pgjdbc/runs/2589252666?check_suite_focus=true#step:10:303
```
1852.4sec, org.postgresql.test.jdbc2.DatabaseEncodingTest > testEncoding
```
It does a crazy amount of inserts so seemed like low hanging fruit to switch it to an unlogged temp table. Ditto for CharacterStreamTest …
=> More test speeds ups with temp tables and disabling autovaccum

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/util/PSQLState.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/TestTerminate.java
=> try to read any notifies or errors that come in asynchronously

.github/workflows/buildcache.yml, .github/workflows/main.yml, .github/workflows/omni.yml, build.gradle.kts, docker/docker-compose.yml, pgjdbc/src/test/java/org/postgresql/test/util/ByteStreamWriterTest.java
First commit marks two more "big" methods as slow tests.
Second teaches gradle to include `build.properties`, `build.local.properties` (if it exists), and `ssltest.properties` as runtime dependencies for tests. Otherwise changes to those files don't actually trigger re-running tests because gradle thinks all the inputs match its cached values.
Third commit teaches gradle to include the files `gradle.ci.test-runtime-only` and `gradle.ci.test-implementation` as dependencies and has the CI actions populate the test-runtime file with the matrix, OS, and PostgreSQL server version information. The actual contents of the file don't matter, it just needs to include something to uniquely identify that environment.
I noticed that similar to `build.properties`, changing the PostgreSQL server version …
=> Gradle and CI improvements

.github/workflows/buildcache.yml
Fixes typo in seed build cache action to actually run when the secrets are available.
Tested by debug logging the values in a separate dummy commit: https://github.com/sehrope/pgjdbc/runs/2640150751?check_suite_focus=true
=> test: Fix typo in seed build cache action output name

.github/workflows/main.yml
Adds removing existing docker containers before starting them and always at the end of the test job. This has not been necessary for the hosted runners but the self-hosted one preserves state between runs so we need to clean up it up.
If this runs through CI cleanly then we'll have a clean slate on the self-hosted runner and be able to switch around both the ports and parent directory (docker-compose uses that for network and volume naming).
See #2154 for more details.
=> test: Add explicit stop and remove of docker-compose containers in CI

docker/postgres-head/Dockerfile
Fixes emptiness check in postgres-head building Dockerfile. Had a bash-ism so it was always failing the emptiness check but didn't notice locally as as the `docker/bin/postgres-head` script always supplies a value. Updated check works in my fork: https://github.com/sehrope/pgjdbc/runs/2676337730?check_suite_focus=true#step:6:18
=> test: Fix git hash emptiness check in postgres-head Dockerfile

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataTest.java
2. [X] Does `./gradlew autostyleCheck checkstyleAll` pass ?
> Fixes getProcedures() and getFunctions() to not filter by search_path when no schema pattern is specified.
----
Closes #2173. See also discussion on #1633.
This PR changes those two metadata functions to ignore the search_path. Previously without a schema pattern they restricted the results to the active search path.
The rest of the changes update the tests to reflect that behavior and subsequently clean up and improve them a bit. The last commit adds some more detail to the getProcedures() test to validate the result set columns similar to how were were already validation the result set of getFunctions().
=> Fix metadata functions getProcedures() and getFunctions() to ignore search_path

pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DriverTest.java
Fix https://github.com/pgjdbc/pgjdbc/issues/2130.
When closing `java.util.logging.Handler`, it also closes the internal `OutputStream`.
In some cases, the internal `OutputStream` is `System.out` or `System.err`, and in these cases, we should not close it, so stop closing the Handler.
This fix is a bit rough, but I don't see any other way to fix it.
I don't think it's possible to change the behavior of re-setting `PARENT_LOGGER` based on the props argument every time `getConnection`, because it's a breaking change.
I thought about giving special treatment to `System.err` and `System.out`, but that's not a fundamental solution because the same problem can occur in the stream returned by `DriverManager.getLogWriter()` (re-used when calling `getConnection` multiple times).
=> fix: When calling Driver.connect multiple times, System.err is closed unexpectedly.

docker/postgres-server/scripts/entrypoint.sh
The latest versions of the postgres docker container no longer symlink the entrypoint script to the root. This PR fixes our customized entry point to handle both the old and newer container versions.
=> fix: Correct path to docker entrypoint in postgres-server container

pgjdbc/src/test/java/org/postgresql/test/jdbc3/EscapeSyntaxCallModeCallIfNoReturnTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/EscapeSyntaxCallModeCallTest.java
Removes special handling for PG 14 procedure errors. The behavior in the latest source builds of the server now matches previous versions.
Fixes #2190
I tried this out in the omin action in my fork and it looks good there: https://github.com/sehrope/pgjdbc/runs/2943561822?check_suite_focus=true
=> test: Remove PG 14 procedure error special handling

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpdateableResultTest.java
Created a protected method inside PgDatabaseMetaData to extend the search for primary keys to include unique keys as well
Added tests
=> fix: resultsets should be updateable if there is a unique constraint on the table fixes issue #2196

pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
Fix: Rework sql type gathering to use OID instead of typname. This does not have the issue of name shadowing / qual-names, and has the added benefit of fixing #1948.
Types that are not on the search path (e.g. they are shadowed, or in a schema that is not included in the search path) are stored in the caches as fully qualified type names and OIDs. As we cannot easily query the pg_type catalog using qualified type names, we replace the pgTypeName with the oid of the type name to query properties of the type.
Testcases are added to improve coverage of correctly detecting SQL types that are not on the path, but are available through OID or qualified lookup. These types are stored internally as a fully qualified type, but we cannot use this name for lookup in pg_type.
Special consideration …
=> backpatch #1949

docs/documentation/head/connect.md
The fork mentioned previously seems unmaintained and mainstream project is supporting Postgresql connection even in the documentation
=> Update socket connection description

pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
Correctly handle the non-signedness of OIDs in relation to signed java integers in this new OID-based type storage.
Previously, OIDs >= 2**31 could not be handled by the driver. This was exposed in 42.2.23, when OIDs became the primary source of truth about type information (before that version this was the type string). 
This patch fixes the bugged behaviour of 42.2.23, and other misbehaviours with int-typed OIDs by first casting the oids to positive Long values, such that the full OID space is represented in integer values, and can be handled correctly.
=> Fix issue #2215 - handle OIDs >= 2**31

pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
OIDs are unsigned integers and were not being handled correctly when they exceeded the size of signed integers
This occurs in databases where there are large schemas or lots of schema changes
=> fix: backpatch PR#2217 to fix issue #2215. 

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/jdbc/LargeObjectManagerTest.java
QueryExecutorImpl.receiveFastpathResult did not properly handle ParameterStatus messages.
This in turn caused failures for some LargeObjectManager operations.
Fixed by adding the missing code path, based on the existing handling in processResults.
Closes #2237
* [n] Does this break existing behaviour? If so please explain.
* [y] Have you added an explanation of what your changes do and why you'd like us to include them?
* [y] Have you written new tests for your core changes, as applicable?
* [y] Have you successfully run tests with your changes locally?
=> fix: handle ParameterStatus messages in QueryExecutorImpl.receiveFastpathResult

pgjdbc/src/test/java/org/postgresql/jdbc/LargeObjectManagerTest.java
Fixes the database connection leak in LargeObjectManagerTest introduced in #2247.
=> fix: close database connection in LargeObjectManagerTest

pgjdbc/src/test/java/org/postgresql/jdbc/LargeObjectManagerTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
The omni CI and appveyor are failing on some of the older server versions. Couple unrelated causes.
First is #2245 added some DDL for adding a `COMMENT ON FUNCTION ... f ...` (rather than `f()`) that only works on server v10+.
Second is that some tests were creating connections but not closing them. Again on some older versions and on appveyor this was leading to connection exhaustion. Same PR had one offender and I found another in Statement Test.
Finally, the new test added in #2247 was failing on v8.4 as updating `application_name` is not supported.
This PR should fix all of that. The StatementTest change is just a wrapping that block in try-with-resources so viewing the diff with whitespaced ignored is a easier:
```diff
diff --git …
```
=> Clean up open connections to fix test failures on omni and appveyor

pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/jdbc/LargeObjectManagerTest.java
QueryExecutorImpl.receiveFastpathResult did not properly handle ParameterStatus messages.
This in turn caused failures for some LargeObjectManager operations.
Fixed by adding the missing code path, based on the existing handling in processResults.
Closes #2237
Original by Simon Strassl https://github.com/strassl
=> backpatch PR#2247

CHANGELOG.md, README.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/core/BaseConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/jdbc/AbstractArraysTest.java, pgjdbc/src/test/java/org/postgresql/test/core/LogServerMessagePropertyTest.java
1. [x] Does your submission pass tests?  -> All passes except replication tests, I'm sure this is a local issue on my side (replications tests are failing with `must be superuser or replication role to start walsender`)
3. [x] Have you added your new test classes to an existing test suite in alphabetical order? (Has already been like this)
This is a follow up to https://github.com/pgjdbc/pgjdbc/issues/2244 and should do the trick to get https://github.com/pgjdbc/pgjdbc/pull/2148 also into 42.2. 
I have cherry-picked https://github.com/pgjdbc/pgjdbc/commit/7bdc4e041ce2055a72b028dafe9e18373ac97d33 , https://github.com/pgjdbc/pgjdbc/commit/12c7fffd69fff99ebd4557dcaf956159d52989e6 and …
=> Backport PR2148 into 42.2.x

pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
=> fix startup regressions caused by PR #1949. Instead of checking all types by OID, we can return types for well known types

pgjdbc/src/main/java/org/postgresql/util/ByteConverter.java, pgjdbc/src/test/java/org/postgresql/util/BigDecimalByteConverterTest.java
=> doc: improv doc around binary decoding of numeric data

pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java
TimestampUtil is not thread safe. It raises exeptions when multiple
Threads use ResultSets of one
connection. If PgStatement and PgResultSet use their own TimestampUtil
no synchronize is needed.
Issue: fix: synchronize modification of shared calendar (#921)
=> fix: use local TimestampUtil in PgStatement and PgResultset for thread safety

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/hostchooser/MultiHostsConnectionTest.java
<details>
<summary>PR checklist</summary>
</details>
Since PG 14 reports `in_hot_standby` GUC on connection there is an opportunity to skip `show transaction_read_only` query during new connection opening phase.
=> perf: read in_hot_standby GUC on connection

pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
The new mview metadata tests in #2209 broke the omni build on the older platforms that do not support mviews: https://github.com/pgjdbc/pgjdbc/runs/4202223480?check_suite_focus=true#step:11:491
This PR fixes those tests to only be enabled on 9.3+ where mviews are supported.
Tested in the omni action in my repo, at https://github.com/sehrope/pgjdbc/actions/runs/1458865278, so once this passes style etc in CI I'll merge it.
=> test: Fix DatabaseMetadataTest to perform mview tests only on 9.3+

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
Previously we did not honour this requirement.
Honestly not sure if the synchronization is necessary. Thoughts ?
Fixes Issue #2300
=> fix Issue #2300. The spec says that calling close() on a closed connection is a noop.

docs/documentation/head/escaped-functions.md
This is a trivial PR fixing a misprint in `escaped-functions.md`
`randow` => `random`
=> Fix misprint in escaped-functions.md for random

README.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/AuthenticationPluginManager.java, pgjdbc/src/main/java/org/postgresql/core/ConnectionFactory.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/plugin/AuthenticationPlugin.java, pgjdbc/src/main/java/org/postgresql/plugin/AuthenticationRequestType.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/plugin/AuthenticationPluginTest.java, pgjdbc/src/test/java/org/postgresql/test/plugin/PluginTestSuite.java
This is a revised version of #2321. I'll close that one out in favor of this.
The first two commits do some refactoring to consolidate where username and passwords are pulled from the properties map and removing those args from the various internal creation methods. This simplifies the changeset for actual feature which adds a plugin hook for dynamically providing the password. The plugin callback also provides the authentication type so the caller has a bit more information to make a decision (e.g. the caller can ensure they are using SCRAM and not sending the password over plaintext).
Because of the message flow of the driver, if the server is configured with trust authentication then no callback will be invoked.
@davecramer While reviewing, in particular take a peek at the public …
=> Add plugin manager to allow dynamically supplying passwords

pgjdbc/src/main/java/org/postgresql/geometric/PGbox.java, pgjdbc/src/main/java/org/postgresql/util/PGBinaryObject.java, pgjdbc/src/main/java/org/postgresql/util/PGobject.java
Fix typos in the javadocs of PGobject, PGBinaryObject and PGbox.
- replace 'overidden' with 'overridden'
- replace 'inteface' with 'interface'
=> style: fix typos in pgobject javadoc

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
Use imports for java.time types in TimestampUtils.
=> style: import java.time types in TimestampUtils

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
Use imports for java.time types in all remaining classes.
Follow up for #2380
=> style: import java.time types in more classes

pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3CallableStatementTest.java
Throw SQLException instead of ClassCastException when calling
CallableStatement#getBoolean(int) on BIT(>1).
Currently when users call `CallableStatement#getBoolean(int)` on an out parameter of type `BIT(>1)` they get `ClassCastException` because the driver casts the result to a `Boolean` without checking the type first. This works for `BIT(1)` bit fails for `BIT(>1)` because then the type currently is `PGobject`. I know there are many related issues and PRs resolving around how we should treat bistring types
- #1910
- #892 
- #908
- #698
- #813
This PR doesn't preclude any approach on these issues, it just changes the exception type for the current behavior.
There are many related ones but I didn't find any for this specific issue.
Users get `SQLException` instead of `ClassCastException`. …
=> fix: throw SQLException for #getBoolean BIT(>1)

pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyLargeFileTest.java
Remove all remaining checks whether the source is lower than Java 8
or JDBC 4.2.
See #1848
=> style: remove Java 8 / JDBC 4.2 checks

CONTRIBUTING.md
Remove the Java 6 and 7 references from contributing.md.
See #1848
=> docs: remove Java 6 and 7 references from contributing

pgjdbc/src/main/java/org/postgresql/largeobject/BlobInputStream.java, pgjdbc/src/main/java/org/postgresql/largeobject/LargeObject.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BlobTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/BlobTest.java
fixes https://github.com/pgjdbc/pgjdbc/issues/2374
=> perf: add read(b,o,l) to BlobInputStream

pgjdbc/src/test/java/org/postgresql/test/jdbc2/RefCursorFetchTest.java
This PR fixes the omni action that has been failing on a couple of the older platforms. First commit fixes the test and the second removes an unnecessary try-catch.
Once it cycles through CI I'll merge it.
=> Fix omni ci test ref cursor fetch test

pgjdbc/src/main/java/org/postgresql/util/PGPropertyServiceParser.java
Fix for default location of file pg_service.conf on Windows:
Current (wrong) location/name:
**`"%APPDATA%\postgresql\pg_service.conf"`**
Fixed (correct) location/name:
**`"%APPDATA%\postgresql\.pg_service.conf"`**
* [yes] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [yes] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [no ] Does this break existing behaviour? If so please explain.
* [yes] Have you successfully run tests with your changes locally?
=> fix: default file name is ".pg_service.conf" on Windows (not "pg_service.conf")

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
* [ x] Does this break existing behaviour? If so please explain.
=> fix: we will ask the server if it supports GSS Encryption if gssEncryption is prefer or require

docs/documentation/head/setup.md
This PR proposes docs information about minimal Maven build of the pgjdbc.
=> docs: add info about convenience maven project

pgjdbc/src/main/java/org/postgresql/ssl/LazyKeyManager.java, pgjdbc/src/main/java/org/postgresql/ssl/PKCS12KeyManager.java, pgjdbc/src/test/java/org/postgresql/test/ssl/LazyKeyManagerTest.java, pgjdbc/src/test/java/org/postgresql/test/ssl/PKCS12KeyTest.java
Previously, these functions ignored the keyType (or 'strings') argument to the chooseClientAlias function. Some libraries (e.g. Bouncy Castle) expect that when chooseClientAlias is called and key types are passed in, that it will return null if the cert doesn't use one of the given key types. For example, if ['EC'] was passed in for keyType and the cert contained an RSA key, since this would return 'user' rather than null in that case, it would cause Bouncy Castle to assume using an ECDSA signing algorithm was okay, and cause problems during the Certificate Verify part of the handshake.
This modifies these functions to only return 'user' if keyType is passed in and the cert contains a key of that type. If keyType is empty or null, it will ignore this and continue to check only the issuer. …
=> Add cert key type checking to chooseClientAlias

pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3CallableStatementTest.java
I took a look into fixing #2399 but it's more complicated than I thought. This PR doesn't actually fix anything yet. It just disables those three new tests in simple query mode so as not to break the CI. Nothing has changed recently in that part of the driver, those are just new tests that exposed existing broken behavior.
Here's the block in Parser where the extra parameter is being added:
https://github.com/pgjdbc/pgjdbc/blob/d281a788b227b73e5a5236a10f3e5f5e73d011e7/pgjdbc/src/main/java/org/postgresql/core/Parser.java#L1167-L1204
That "parameter" is actually an out parameter to reflect the functions return value. However removing it ends up breaking subsequent invocations to `CallableStatement.registerOutParameter(...)` as then the driver thinks there are no out parameters.
The reason …
=> test: Disable no-arg callable statement tests in simple query mode

pgjdbc/src/main/java/org/postgresql/largeobject/BlobInputStream.java, pgjdbc/src/main/java/org/postgresql/largeobject/LargeObject.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BlobTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/BlobTest.java
Reverts pgjdbc/pgjdbc#2376
As @vlsi mentioned a better solution would be to buffer at the LargeObject layer.
As I'm not entirely sure this doesn't introduce more issues I am reverting in favour of a different implementation
=> Revert "perf: add read(b,o,l) to BlobInputStream"

.github/workflows/fedora-copr-build.yml
Sorry for the rush.  Going through PR to actually test the PR workflow.
=> Fix the RPM CI - typo in branch names

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
=> Use non-synchronized getTimeZone in TimestampUtils

pgjdbc/src/main/java/org/postgresql/Driver.java
=> fix: Throw an exception if the driver cannot parse the URL instead of returning NULL 

pgjdbc/src/main/java/org/postgresql/util/PGInterval.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/IntervalTest.java
change parse seconds segment from Integer to Double
=> fix: change PGInterval parseISO8601Format to support fractional second

CHANGELOG.md
Minor cosmetic fix.
Example of rendered documents on GitHub:
Before:
After:
=> docs: Fix CHANGELOG.md misformatted markdown headings

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/GetObject310Test.java
This fixes #2221:
I added a new method to TimestampUtils that directly converts the epoch days to a LocalDate. Interestingly this allows to not use the cryptic proleptic seconds hack. You can pass the plain epoch days from postgres, just added a few number of days -- actually the strange constant at beginning to `toJavaSecs()` method:
```
// postgres epoc to java epoc
secs += 946684800L;
```
divided by 86400 (to get it in days). The following code in toJavaSecs is not needed and returns broken results, because `LocalDate` also does its own Julian/Gregorian transformation.
I also beefed the test for LocalDate to cycle through all timezones (should not be needed, as timezone is not involved). I also added dates like 0001-01-01 to tests for LocalDate and LocalDateTime.
=> feat: use direct wire format -> LocalDate conversion without resorting to java.util.Date, java.util.Calendar, and default timezones

docs/_posts/2021-02-01-42.2.25-release.md
This just adds an entry for 42.2.25 into the downloads to clarify that it is the official latest 42.2.x version
=> added post for 42.2.25 [SKIP CI]

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/GetObject310Test.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/SetObject310Test.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/TimestampUtilsTest.java
After #2464 I took care about the remaining conversions between Postgres wire format, legacy calendars and Timestamp/Date/Time and the modern java.time APIs.
This PR especially takes care of TIMETZ, which was converted from/to calendars and `java.sql.Time`. This implements a parser for the `TIMETZ` wire format and also allows them to get using `ResultSet#getObject(col, OffsetTime.class)`, which preserves the original server-stored timezone!
This also fixes `TimestampUtils#parseBackendTimestamp()` to use a `ZoneOffset` instead of allocating and modifying legacy calendar instances. This allows to easier read also the old legacy code but also the wire format parsers, because you don't need to calculate with raw offsets. This also removes state from `TimestampUtils`.
1. [X] Does your …
=> feat: add support for ResultSet#getObject(OffsetTime.class) and PreparedStatement#setObject(OffsetTime.class)

pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DateTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/GetObject310Test.java
This is a PR related to issues found in #2476, maybe caused by #2464 or #2467
=> More test and fix for issues discovered by #2476

docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/PGStream.java
In [#2341](https://github.com/pgjdbc/pgjdbc/pull/2341) the option to
configure tcpNoDelay was added, with a default value of false.
The previous value of this setting was true, as set in
PGStream.changeSocket(Socket) with the following code:
```
// Submitted by Jason Venner <jason@idiom.com>. Disable Nagle
// as we are selective about flushing output only when we
// really need to.
connection.setTcpNoDelay(true);
```
`changeSocket()` is called from the `PGStream` constructor, which is
called in `ConnectionFactoryImpl`, and then later we overwrite the value
with the one from the properties.
We had a performance issue when upgrading from 42.2.24 to 42.3.3, and we suspected the
issue in 42.3.2 and confirmed that by passing the property `tcpNoDelay=true` to the driver,
the performance issue …
=> perf: enable tcpNoDelay by default

README.md, docs/documentation/head/connect.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/hostchooser/HostRequirement.java, pgjdbc/src/main/java/org/postgresql/hostchooser/MultiHostChooser.java, pgjdbc/src/test/java/org/postgresql/test/hostchooser/MultiHostsConnectionTest.java
@davecramer - this PR is a cleaner copy of the [PR#1430](https://github.com/pgjdbc/pgjdbc/pull/1430) as we discussed here: https://www.postgresql.org/message-id/CADK3HHJBQJje9Etd29HY6_1S1kRdR4KEviPev-vjtrQp-dZ%2BFQ%40mail.gmail.com
Below is the original [PR#1430](https://github.com/pgjdbc/pgjdbc/pull/1430) Description:
> Allows a new `preferMaster` value for `targetServerType` parameter, which forces the driver to preferably connect to a master host. The behaiviour is basically the inverse of `preferSecondary` value and the usecases are described in the mailing list: https://www.postgresql.org/message-id/VI1PR05MB5295AE43EF9525EACC9E57ECBC750%40VI1PR05MB5295.eurprd05.prod.outlook.com
> 
> Also updated the documentation and readme for the parameter. …
=> feat: targetServerType=preferPrimary connection parameter

docs/_posts/2022-02-01-42.3.2-release.md, docs/_posts/2022-02-15-42.3.3-release.md, docs/_posts/2022-04-15-42.3.4-release.md, docs/_posts/2022-05-04-42.3.5-release.md, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/RefCursorFetchTest.java
`PgResultSet` might hold `ResultCursor cursor` for fetching the next rows.
So we should use `ResultCursor cursor==null` condition to check if we want to close `<unnamed portal 1>` from refcursors.
See https://github.com/pgjdbc/pgjdbc/issues/2227
See https://github.com/pgjdbc/pgjdbc/pull/2371
/cc @davecramer
=> fix: close refcursors when underlying cursor==null instead of relying on defaultRowFetchSize

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
See issue #2520
Modified existing test cases.
=> fix: return correct base type for domain from getUDTs (#2520)

CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchedInsertReWriteEnabledTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/PreparedStatement64KBindsTest.java
Previously the execution failed with "Tried to send an out-of-range integer as a 2-byte value"
when the user attempted executing a query with more than 32767 parameters.
Technically speaking, the wire protocol limit is 2-byte-unsigned-int,
so we should support 65535 parameters.
In practice, simple mode (preferQueryMode=simple) allows executing queries
with an arbitrary number of parameters, however, that escape hatch is not recommended
as it still has limits on the SQL length, and it would likely be slow.
fixes #1311
=> fix: support queries with up to 65535 (inclusive) parameters

README.md
When a release is published the README.md has to be updated to reflect every new version, and sometimes it could be forgotten, and since we already provide links to maven central to the latest version there is no need to explicitly declare the version in the README.md.
With this, the readme could be more static and still always reflect the latest version thanks to the badges.
=> chore: Make the readme version agnostic

.github/workflows/buildcache.yml, .github/workflows/debezium.yml, .github/workflows/fedora-copr-build.yml, .github/workflows/main.yml, .github/workflows/nightlysnapshot.yml, .github/workflows/omni.yml, CHANGELOG.md
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
See
https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
=> chore: set "read" permissions for GitHub actions

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
This change adds a table alias to the generated query for `getUDT` method, in order to make it more clear which table is being referenced.  
This was done based on the feedback on initial PR (https://github.com/pgjdbc/pgjdbc/pull/2522)
=> Add table alias to the getUDT query for clarity

pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/jdbc/ArraysTestSuite.java, pgjdbc/src/test/java/org/postgresql/jdbc/UUIDArrayTest.java
Hello,
pgjdbc has had issue for some time that calling .setObject on PreparedStatement only works for some kind of arrays (arrays listed in `ArrayEncoding.ARRAY_CLASS_TO_ENCODER`. Unfortunately, UUID is not in that list. 
Using `stmt.setArray(parameterPosition, con.createArrayOf("uuid", myUuidArray))` works, but unfortunately connection can sometimes be buried deep in multiple abstraction layers and not really accessible to caller (i.e. when using spring NamedParameterJdbcTemplate). 
Since I am not deeply familiar with pgjdbc design philosophy, I tried to make something that could be useful starting point for proper fix, but I am sure that maintainers will have better and more elegant way of solving this issue. 
1. [x] Does your submission pass tests? 
Yes, at least tests relevant to my …
=> fix: make setObject accept UUID array

pgjdbc/src/main/java/org/postgresql/gss/MakeGSS.java
=> fix mismatched types for invokeExact. Have to tell invokeExact what type we are expecting

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
Hi!
When we call `PgResultSet.getInt` for float-typed columns fast number parser (`getFastInt`) fails on dot symbol and then we go to very slow path: Integer.parseInt throw new NumberFormatException (with stacktrace) that immediately swallowed and finally we parse integer through BigDecimal/BigInteger.
I propose to not fail fast parsing or fraction part but just discard it.
=> perf: improve performance of PgResultSet getByte/getShort/getInt/getLong for float-typed columns

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
* [x ] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X ] Have you written new tests for your core changes, as applicable?
* [X ] Have you successfully run tests with your changes locally?
Fixes #2639
=> fix: binary decoding of bool values

.git-blame-ignore-revs
See https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view Local repo can be configured via
git config blame.ignoreRevsFile .git-blame-ignore-revs
=> chore: add .git-blame-ignore-revst to hide reformatting commits from GitHub blame UI

pgjdbc/src/main/java/org/postgresql/util/ByteConverter.java, pgjdbc/src/test/java/org/postgresql/util/BigDecimalByteConverterTest.java
fix binary conversion of numeric values longer than 4 * 2^15 digits
fixes https://github.com/pgjdbc/pgjdbc/issues/2695
=> fix - binary conversion of (very) long numeric values

docs/content/documentation/use.md
=> docs: Document the need to encode reserved characters in the connection URL

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
=> minor: enhance readability connection of startup params

README.md
* The image did not load because the specified src did not exist
* Only the alt text was showing so I changed the src to where I found the image
=> fix: img src in README

pgjdbc/src/main/java/org/postgresql/core/BaseConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
TimestampUtil is not thread safe. It raises exeptions when multiple threads use ResultSets of one connection. If PgResultSet uses its own TimestampUtil, no synchronization is needed.
Fix for Issue: ArrayIndexOutOfBoundsException with postgresql driver version 42.5.1 (https://github.com/pgjdbc/pgjdbc/issues/2723)
=> fix: improve thread safety of PgResultSet#getTimestamp

.github/workflows/buildcache.yml, .github/workflows/debezium.yml, .github/workflows/main.yml, .github/workflows/matrix.js, .github/workflows/nightlysnapshot.yml, .github/workflows/omni.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See https://github.com/actions/toolkit/blob/6c1f9eaae833355a0b212b66c5f2e3ac366de185/packages/core/src/core.ts#L192
=> Bump GitHub action versions, replace deprecated set-output usage

.editorconfig, pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/test/core/QueryExecutorTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CustomTypeWithBinaryTransferTest.java
* Get existing oids for binary transfer of custom types from QueryExecutor
* Add new oids for binary transfer of custom types to QueryExecutor
* Unit test to make sure oids are correctly set
https://github.com/pgjdbc/pgjdbc/issues/2554
2. [X] Does `./gradlew autostyleCheck checkstyleAll` pass ?
3. [X] Have you added your new test classes to an existing test suite in alphabetical order?
=> feat: Define binary transfer for custom types dynamically (#2554)

config/forbidden-apis/forbidden-apis.txt, pgjdbc/src/main/java/org/postgresql/Driver.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/v3/CopyOperationImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/ds/PGPoolingDataSource.java, pgjdbc/src/main/java/org/postgresql/hostchooser/GlobalHostStatusTracker.java, pgjdbc/src/main/java/org/postgresql/jdbc/AbstractBlobClob.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgBlob.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgClob.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgSQLXML.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/ResourceLock.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/main/java/org/postgresql/largeobject/BlobInputStream.java, pgjdbc/src/main/java/org/postgresql/ssl/PKCS12KeyManager.java, pgjdbc/src/main/java/org/postgresql/util/LogWriterHandler.java, pgjdbc/src/main/java/org/postgresql/util/LruCache.java, pgjdbc/src/main/java/org/postgresql/util/SharedTimer.java, pgjdbc/src/test/java/org/postgresql/jdbc/ResourceLockTest.java, pgjdbc/src/test/java/org/postgresql/test/TestUtil.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyLargeFileTest.java
Referencing https://github.com/pgjdbc/pgjdbc/issues/1951 for outline / motivation which is to improve compatibility with loom.
Change PgStatement, PgPreparedStatement and PgCallableStatement replacing synchronized (this) blocks with use of ReentrantLock to be compatible with loom.
In doing this change for PgStatement this PR must include:
All synchronized (this) blocks in PgStatement
All synchronized (this) blocks in it's sub types (PgPreparedStatement and PgCallableStatement)
I confirm that this PR includes all synchronized (this) blocks across PgStatement and all it's sub types.
Note that this PR does not add any new tests or change any existing tests. I do not believe either is required.
=> refactor:(loom) replace the usages of synchronized with ReentrantLock

.github/workflows/main.yml
=> chore: tune down the number of CI jobs for PR builds from 7 to 5

.github/workflows/main.yml
from @vlsi 
```
I guess we need to adjust branches: '*' to branches: '**' in the workflow definition: 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
```
=> Make sure that github CI runs tests on all PRs

pgjdbc/src/test/java/org/postgresql/core/OidValuesCorrectnessTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataCacheTest.java
We used to search for box type but it is now cached
fix OidValueCorrectnessTest BOX_ARRAY OID, by adding BOX_ARRAY to the oidTypeName map
=> fix: fix testGetSQLTypeQueryCache by searching for xid type instead of box. 

pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java, pgjdbc/src/main/java/org/postgresql/core/QueryExecutorCloseAction.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnectionFinalizeAction.java, pgjdbc/src/main/java/org/postgresql/util/StreamWrapper.java, pgjdbc/src/main/java/org/postgresql/util/StreamWrapperFinalizeAction.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyTest.java
Previously, an abandoned PgConnection could retain a significant amount of heap. Now the bare minimum is moved to a separate class, so the abandoned connections can be removed from the heap earlier.
This does not remove the use of `.finalize()`, and it only reduces the amount of retained heap memory.
=> fix: reduce memory overhead of .finalize() methods in PgConnection and StreamWrapper

.github/workflows/main.yml, .github/workflows/matrix.js, build-logic/jvm/src/main/kotlin/build-logic.test-base.gradle.kts
javac and kotlinc have issues with hashcode collision, so it becomes impractical to test with that setting.
Javac produces compilation failure, while Kotilnc 1.8.10 becomes slow
=> chore: pass "same hashcode" to test task only

pgjdbc/src/main/java/org/postgresql/core/Oid.java, pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/core/OidValuesCorrectnessTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataCacheTest.java
PR #2556 introduced a regression. The regression was that a query was added on every new connection.
The fix for this was to add the box type to the cache, however that caused 2 tests to fail.
This PR addresses these issues
=> Pull fixes for PR#2556 into master

pgjdbc-osgi-test/src/test/java/org/postgresql/test/osgi/DefaultPgjdbcOsgiOptions.java
The default timeouts were 5 seconds, so let's check if increasing helps to prevent test failures
=> test: increase timeouts for resolving Maven dependencies in OSGi tests

pgjdbc/build.gradle.kts
It should remove debugging messages from the test execution.
=> chore: bump classloader-leak-test-framework to 1.1.2

benchmarks/src/jmh/java/org/postgresql/benchmark/util/LongParser.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/util/NumberParser.java, pgjdbc/src/test/java/org/postgresql/util/NumberParserTest.java
We met situation when a lot of cpu in some cases consumes by PgResultSet.getLong (according to async-profiler flame graph).
The reason is that current optimised function getFastLong can't work with long numbers with more than 59 significant bits, because of `len(str(2 ** 60)) -> 19`, and we have check of byte[] length.
https://github.com/pgjdbc/pgjdbc/blob/29414ab886553d212b39f94b125662989d270b6e/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java#L2587
We have a lot of numbers, which are exceeds this restriction (almost all ids are generated like `Random.nextLong()`).
This PR modifies getFastLong to be able to process all longs from MIN_VALUE to MAX_VALUE.
Corresponding tests were added, fallback to `toLong()` left in place.
I had to move the method to a separate class for testing …
=> Method getFastLong should be able to parse all longs

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
(I'm one of the PgBouncer maintainers)
This makes variable caching in PgBouncer more efficient, because now the client is setting the same values that the server reports.
See these PgBouncer issues/PRs for details:
https://github.com/pgbouncer/pgbouncer/issues/776
https://github.com/pgbouncer/pgbouncer/pull/879
1. [ ] Does your submission pass tests? **Not sure, I don't use Java normally so I'm hoping that CI will find any issues**
2. [ ] Does `./gradlew autostyleCheck checkstyleAll` pass ? **See 1**
3. [ ] Have you added your new test classes to an existing test suite in alphabetical order? **I did not add any tests**
=> Use canonical DateStyle name

pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/BaseDataSourceFailoverUrlsTest.java
In BaseDataSource, check to make sure the number of servers is equal to the number of ports.
Throw an IllegalArgumentException if they are not. Added test case to ensure
Fixes #2928
=> Fix Issue #2928 number of ports not equal to number of servers in datasource

pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ArrayTest.java
Currently, pgjdbc does not support setting arrays using ANSI type names like `double precision` or `timestamp with time zone`. For example, `conn.createArrayOf("double precision", new Object[] {0d})` fails with the exception "Unable to find server array type for provided name double precision". This can be worked around by using the PostgreSQL type name (e.g. `float8`) instead, however it seems like the driver should be able to handle the same array types as PostgreSQL itself.
This isn't the first attempt to fix this issue. In 2020, #1719 was merged to fix the same problem. The patch caused some introspected types to change (#1744), and was reverted by #1745. Adding the missing types to `TYPE_ALIASES` instead of `types` fixes the problem, and avoids the OID collisions that caused #1744. …
=> fix: allow setting arrays with ANSI type name

pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
It seems that the way names are created for shadowed types has changed
Instead of prepending _ to a shadowed name they now append _N where N is an integer
=> Fix failing tests for version 16. 

pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java, pgjdbc/src/test/java/org/postgresql/jdbc/BitFieldTest.java
Currently, extra queries are needed to resolve type information for the varbit type, even though the OID and type information are entirely predictable. This patch will adds the builtin type into the TypeInfoCache, to avoid extra round trips on high latency connections.
Fixes: #2959
=> fix: add varbit as a basic type inside the TypeInfoCache

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
Use the pg.catalog.pg_database table present in all catalogs to return
the list of available catalogs, instead of just the current one the
connection uses. The table is filtered to include only the
catalogs that can be connected to.
closes pgjdbc#2949
2. [x] Does `./gradlew autostyleCheck` pass ?
=> feat: return all catalogs for getCatalogs metadata query (#2949)

pgjdbc/src/main/java/org/postgresql/geometric/PGpoint.java
This pull request deprecates the following method:
```
org.postgresql.geometric.PGpoint.setLocation(Point)
```
This is in anticipation for possible modularisation of PostgreSQL JDBC driver as described in #2657. That method was the only dependency to the huge `java.desktop` module, because of the `java.awt.Point` argument. Removing that dependency would allow PgJDBC users to depend on a much smaller subset of the Java environment. There is no need to provide a replacement, because the implementation is trivial.
=> Deprecate for removal a trivial dependency to `java.desktop` module

pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java
This fixes the `currentXid={2}` in the PGXAException exception messages
=> Include `currentXid` in exception message

.github/pull_request_template.md, .github/workflows/main.yml, CONTRIBUTING.md, build-logic/verification/src/main/kotlin/build-logic.style.gradle.kts
The mnemonics is:
* `style`: fix code style
* `styleCheck`: report style violations
Most of the time, `./gradlew style` should be good enough.
=> chore: add styleCheck Gradle task to report style violations

pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3CallableStatementTest.java
Previously this would throw an exception when the return type of the procedure was changed from VOID to REFCURSOR
fixes Issue #2983
=> Fix problem when calling a procedure returning a refcursor more than 5 times (prepareThreshold) 

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataPropertiesTest.java
Fixes: #2991
This commit updates `PgDatabaseMetaData.getDefaultTransactionIsolation` to query the database for the default transaction isolation level, instead of assuming that the default isolation level is READ COMMITTED.
=> Return correct default from PgDatabaseMetaData.getDefaultTransactionIsolation

pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/main/java/org/postgresql/core/SqlCommandType.java, pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/ResultWrapper.java, pgjdbc/src/test/java/org/postgresql/core/ParserTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementWithSetTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
Regarding #2966 this PR allows to write SET statements before INSERT/UPDATE/DELETE/UPDATE.
It was possible to run these SET statements in a separate query, but it's more convenient to have them in the same query.
* It avoids round-trip to the server
* We can use local variables in the SET statements
* It allows to use `StatementInspector` to add SET statements in Hibernate
```sql
SET SESSION var.nb_test=10;
SET LOCAL var.test_value=42;
INSERT INTO test_statement
SELECT current_setting('var.test_value')::int
FROM generate_series(1, current_setting('var.nb_test')::int);
```
=> feat: support SET statements combining with other queries with semicolon in PreparedStatement

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataPropertiesTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTransactionIsolationTest.java
=> Use a switch statement to compare transaction isolation levels and let the database do the toUpper

packaging/rpm/postgresql-jdbc.spec.tpl, packaging/rpm/setup-copr/copr-setup
=> fedora/rpm: move source build to java-17-openjdk-devel

pgjdbc/reduced-pom.xml
Previously, pom.xml used source=1.8, target=1.8 so it might produce invalid bytecode when running on Java 1.8
Now pom.xml would use --release 8 to avoid such issues.
See https://github.com/pgjdbc/pgjdbc/issues/3014
=> chore: use java.release=8 when building pgjdbc from the generated source distribution

docs/content/documentation/use.md, pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java
For compatibility with environments where JNA 5 is used, such as certain IDEs.
This is a work in progress because additional modifications, at least to packaging, are required. As it is, this code attempts to use a class that is not available from the declared dependencies (i.e. JNA 4).
Fixes #2690.
The existing tests will cover the new behavior when supplied with the correct JNA version.
=> fix: support waffle-jna 2.x and 3.x by using reflective approach for ManagedSecBufferDesc

pgjdbc/src/main/java/org/postgresql/ssl/MakeSSL.java
Fixes a report that SSL connections do not honour connection timeout.
=> Apply connectTimeout before SSLSocket.startHandshake to avoid infinite wait in case the connection is broken

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/SetObject310Test.java
Previously, LocalDateTime was converted to OffsetDateTime using the default timezone, which made certain values unrepresentable. For instance, 2023-03-12T02:00 in America/New_York is hard to represent as it undergoes DST change.
It does not change resultSet.getObject(int | string), and resultSet.getString(int | string) and those methods would still have issues when accessing timestamps like 2023-03-12T02:00 when the client time zone is America/New_York
Fixes https://github.com/pgjdbc/pgjdbc/issues/1390
Fixes https://github.com/pgjdbc/pgjdbc/issues/2850
Closes https://github.com/pgjdbc/pgjdbc/pull/1391
=> fix: avoid timezone conversions when sending LocalDateTime to the database

pgjdbc/src/main/java/org/postgresql/core/NativeQuery.java, pgjdbc/src/main/java/org/postgresql/core/Parser.java, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/main/java/org/postgresql/util/IntList.java, pgjdbc/src/test/java/org/postgresql/util/IntListTest.java
The parser currently builds a `List<Integer>` (requires boxing) to track bind variables. It then converts this to an `int[]` (requires unboxing) when creating the `NativeQuery`.
This change provides a simple collection backed by an `int[]`.
=> perf: avoid autoboxing bind indexes

.github/workflows/matrix.js, CHANGELOG.md, pgjdbc/src/main/java/org/postgresql/PGConnection.java, pgjdbc/src/main/java/org/postgresql/util/MD5Digest.java, pgjdbc/src/main/java/org/postgresql/util/PasswordUtil.java, pgjdbc/src/test/java/org/postgresql/test/util/PasswordUtilTest.java, pgjdbc/src/testFixtures/java/org/postgresql/test/TestUtil.java
Overall idea is the same as #3067 but couple changes to implementation and presesntation:
* `PasswordUtil` no longer concerns itself with connections. It just hashes passwords and encodes them for using in the DB.
* Adds some overloads for more specific options (e.g. customizing the SCRAM iterations and salt size). Defaults for the no-overload version match up with before which IIRC is the server defaults.
* Adds `alterUserPassword(...)` to `PGConnnection`. That's our "public API" for everything PG-specific so it seemed like a better home than having `PasswordUtil` deal with java.sql.*.
Splitting out the encoding allows the same functions to be used for `CREATE USER ...` (again without passing the credentials in plaintext). The updated test:
* Creates the user using the encoded password
* …
=> Add PasswordUtil for encrypting passwords client side

pgjdbc/src/main/java/org/postgresql/PGConnection.java, pgjdbc/src/main/java/org/postgresql/util/PasswordUtil.java, pgjdbc/src/test/java/org/postgresql/test/util/PasswordUtilTest.java
Having an unknown driver's default password encoding does not help clients as they will not be sure if the database supports the encoding or not. They should prefer org.postgresql.PGConnection#alterUserPassword as it would select database-default encoding which might improve over time.
=> refactor: document that encodePassword will zero out the password array, and remove driver's default encodePassword

.github/workflows/main.yml, .github/workflows/matrix.js, .github/workflows/matrix_builder.js, .github/workflows/rng.js, .github/workflows/seedrandom.js
Change randomized test matrix to use a deterministic RNG. If the RNG_SEED environment variable is defined, it will be used as the initial seed for the RNG. Alternatively, if the GITHUB_PR_NUMBER environment variable is defined, it will be used to generate a deterministic RNG seed to ensure that all test cycles for the same PR generate the same test matrix of random environments.
If neither environment variable is defined then a random seed will be generated and logged to the console. Re-running the action using that seed with the same matrix generation codebase will generate the same matrix.
The actual RNG code is copied from seedrandom:
https://github.com/davidbau/seedrandom/commit/4460ad325a0a15273a211e509f03ae0beb99511a
This commit also adds a manual dispatch option to the primary CI …
=> test: Use deterministic RNG for CI randomized test matrix

pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/PreparedStatementTest.java
make sure we handle boolean types in simple query mode
fixes #3145
=> fix Issue # 3145 boolean types not handled in SimpleQuery mode

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
This PR aims to fix issue #3061 
currently resultSet paramters can accept negative values. I have added a validation that ensures the resultset parameters are always > 0
The parameters being validated are
- resultSetType
- resultSetConcurrency
- resultSetHoldability
The methods where this validation is applied are:
- prepareCall
- prepareStatement
- createStatement
Within pgjdbc/src/test/java/org/postgresql/jdbc & pgjdbc/src/test/java/org/postgresql/core I couldn't find a test file for PGConnection.
I wanted to know if I should add additional tests pertaining to this issue?
=> validates resultset parameters

pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BlobTest.java
Historically, Hibernate was creating such clobs and it relied on the fact that pgjdbc did not use the length in case it was -1.
Now the negative length is treated as if it was infinite (no eplicit limit) The length of 0 means "empty lob".
Fixes https://github.com/pgjdbc/pgjdbc/issues/3134
=> fix: support PreparedStatement.setBlob(1, Blob) and PreparedStatement.setClob(1, Clob) for lobs that return -1 for length

build-logic/jvm/src/main/kotlin/build-logic.test-junit5.gradle.kts, pgjdbc/build.gradle.kts, pgjdbc/reduced-pom.xml, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java, pgjdbc/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, pgjdbc/src/testFixtures/java/org/postgresql/test/impl/AfterBeforeParameterResolver.java, pgjdbc/src/testFixtures/java/org/postgresql/test/impl/DefaultParameterContext.java
Fixes https://github.com/pgjdbc/pgjdbc/issues/3229
It looks like jdbc2.DatabaseMetaDataTest was the only impacted test.
=> test: test both binaryMode=true,false when creating connections in DatabaseMetaDataTest

benchmarks/src/jmh/java/org/postgresql/benchmark/encoding/HexEncodingBenchmark.java, pgjdbc/src/main/java/org/postgresql/core/Utils.java, pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java, pgjdbc/src/main/java/org/postgresql/jdbc/ArrayEncoding.java, pgjdbc/src/main/java/org/postgresql/util/PGbytea.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ServerCursorTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/UpdateableResultTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc3/Jdbc3CallableStatementTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/BinaryStreamTest.java, pgjdbc/src/test/java/org/postgresql/test/util/BrokenInputStream.java, pgjdbc/src/test/java/org/postgresql/test/util/ByteStreamWriterTest.java
This adds text encoding for `bytea`.
Interestingly, the tricks with `private final char[] hexDigits` do not improve performance, and we probably should stick with `Character.forDigit(...)` for `int -> hex` conversions.
----
Unfortunately, we have two different handling of "stream underflow" with `StreamWrapper` and `ByteStreamWriter`.
Both of them might report their lengths, and both of them might happen to underflow or overflow.
`PGStream` handles `StreamWrapper` as follows (see org.postgresql.core.PGStream#sendStream):
* If there's not enough data in the stream => raise "Premature end of input stream"
* If there's too much data => just ignore it
`PGStream` handles `ByteStreamWriter` as follows (see org.postgresql.core.PGStream#send(ByteStreamWriter)):
* If there's not enough data in the …
=> fix: support bytea in preferQueryMode=simple

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/util/ByteConverter.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java, pgjdbc/src/test/java/org/postgresql/util/BigDecimalByteConverterTest.java
Since version 14, PostgreSQL supports `Infinity` and `-Infinity` special values for `numeric` type. This PR adds support for getting them via the `ResultSet.getObject(int)` and `ResultSet.getObject(String)` methods. These methods return values of type `Object` and usually they return `BigDecimal` values for normal `numeric` values. Since `BigDecimal` in Java does not support special values `NaN`, `Infinity` and `-Infinity` the `getObject` methods return them as `Double` values. Prior to this PR only `NaN` was supported and this PR extends the support to `Infinity` and `-Infinity`.
Fixes #3286 
In a way. The `ResultSet.getObject(int)` and `ResultSet.getObject(String)` used to throw an exception when they encountered `Infinity::numeric` or `-Infinity::numeric` value. This PR makes the …
=> Add support for Infinity::numeric values in ResultSet.getObject

.github/workflows/main.yml, .github/workflows/omni.yml, docker/postgres-head/docker-compose.yml, docker/postgres-server/docker-compose.yml
note, the missing `-`
see https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/ for details
=> use docker v2 which changes docker-compose to docker compose 

.github/workflows/matrix.js, CONTRIBUTING.md, README.md, TESTING.md, docker/bin/postgres-server, docs/content/download/_index.md, docs/data/versions.toml, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/ServerVersion.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
Older versions of postgres containers (8.4 and 9.0)  use a Docker Image Format v1 that is no longer supported:
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/library/postgres:8.4 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
Removing them from the matrix.
=> Deprecate all PostgreSQL versions older than 9.1

benchmarks/src/jmh/java/org/postgresql/benchmark/stream/StreamReceiveInteger.java, pgjdbc/src/main/java/org/postgresql/core/PGStream.java, pgjdbc/src/main/java/org/postgresql/core/VisibleBufferedInputStream.java
This PR is for #3250 
I have moved receiveInteger2 and receiveInteger4 to VisibleBufferedInputStream. 
Within PGStream, I have also removed dependency on int4buf and int2buf by directly writing value to OutputStream inside sendInteger2 and sendInteger4
Based on reviews, can further add tests and documentation for the new methods
=> perf: avoid extra copies when receiving int4 and int2 in PGStream

pgjdbc/src/main/java/org/postgresql/util/PGInterval.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/IntervalTest.java
As reported in #3297, PGInteval should be able to ignore case when taking a string interval.
=> bug report: PgInterval ignores case for represented interval string

pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTransactionIsolationTest.java
This commit updates the `DatabaseMetaDataTransactionIsolationTest` suite to not assume that the unit tests are running in the "test" database. Instead, we now use `TestUtil.getDatabase()` to retrieve the current database name.
=> Do not assume "test" database in DatabaseMetaDataTransactionIsolationTest

CONTRIBUTING.md, TESTING.md, docker/bin/postgres-server, docker/postgres-server/README.md
The name postgresql-server is not the real file name inside docker directory. Should instead be postgres-server
Docker compose v2 migration https://docs.docker.com/compose/migrate/
=> Changed docker-compose version and renamed script file in instructions to match the real file name

pgjdbc/src/main/java/org/postgresql/core/PGStream.java
fix this error stack:
```
Caused by: java.io.IOException: GSSException: Failure unspecified at GSS-API level (Mechanism level: Could not use AES128 Cipher - Checksum failed)
at org.postgresql.gss.GSSInputStream.read(GSSInputStream.java:69)
...
Caused by: GSSException: Failure unspecified at GSS-API level (Mechanism level: Could not use AES128 Cipher - Checksum failed)
at java.security.jgss/sun.security.jgss.krb5.CipherHelper.aes128Decrypt(CipherHelper.java:1429)
...
at java.security.jgss/sun.security.jgss.GSSContextImpl.unwrap(GSSContextImpl.java:423)
at org.postgresql.gss.GSSInputStream.read(GSSInputStream.java:58)
...
Caused by: java.security.GeneralSecurityException: Checksum failed
at java.security.jgss/sun.security.krb5.internal.crypto.dk.AesDkCrypto.decryptCTS(AesDkCrypto.java:451) …
```
=> fix: use buffered inputstream to create GSSInputStream

.github/workflows/matrix.js, build-logic/jvm/src/main/kotlin/build-logic.test-junit5.gradle.kts, pgjdbc/build.gradle.kts
=> ci: Test with Java 23

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/GetObjectTest.java
yes
yes
I did, though they weren't
no
see #3269
yes
yes
yes
yes
=> feat: support getObject(int, byte[].class) for bytea

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
In relation to #3432: since PostgreSQL 12, we do not need to mess with extra_float_digits to get the full precision. Since we already check the server version before setting the parameter, it's just an extra check to avoid sending it for nothing. Free bonus: no more complaints with PgBouncer.
=> feat: don't force send extra_float_digits for PostgreSQL >= 12 (#3432)

pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
correct the logic to send `extra_float_digits=2` for versions less than 8 and `extra_float_digits=3` for versions 9-12
=> fix:Fix sending extra_float_digits

pgjdbc/src/main/java/org/postgresql/PGProperty.java
Undeprecates the `sslfactoryarg` connection property. Similar to the `socketfactoyarg`, it can be used to customize the injected factory class. As there are no plans to remove it in the future, we are undeprecating it to silence the deprecation warning in user code that references it.
See https://github.com/pgjdbc/pgjdbc/issues/2725 and https://github.com/pgjdbc/pgjdbc/pull/2923 for related discussion.
=> Undeprecate sslfactoryarg connection property

pgjdbc/src/main/java/org/postgresql/jdbc/ArrayDecoding.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
At best, we should avoid `byte[] -> String -> byte[]` conversions when dealing with datetime, however, currently PgCallableStatement uses getObject eagerly, so we lose the underlying wire format byte[] early.
That is why we have to use .toString() when converting to date. Ideally, we should keep the source byte[] data and convert it on request.
---
The change avoids `getBytes()` with the default encoding. I believe, date-time use limited alphabet, so the encoding should not matter much. However, the use of the default encoding was not the best choice.
=> refactor: factor out duplicated .getBytes() when converting date/time to Date/Time/Timestamp

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
Implemented the feature suggestion in [#3467](https://github.com/pgjdbc/pgjdbc/issues/3467)
Enhanced DatabaseMetadata, added index comment as REMARKS property
=> feat: enhanced DatabaseMetadata.getIndexInfo() method, added index comment as REMARKS property

pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java
This reverts commit 7dbab6511bb30a1564dda044ef07396f6ddedc15 so it could be re-implemented
=> Revert "use in row values instead of union all (#3510)"

pgjdbc/src/testFixtures/java/org/postgresql/test/impl/AfterBeforeParameterResolver.java
This PR fixes JavadocTagContinuationIndentation violations in `pgjdbc/src/testFixtures/java/org/postgresql/test/impl/AfterBeforeParameterResolver.java` that will occur with the latest Checkstyle update.
A build failure was detected in `AfterBeforeParameterResolver.java` where the Javadoc comments have inconsistent indentation, violating the `JavadocTagContinuationIndentationCheck` in the latest Checkstyle version.
Corrected the indentation in Javadoc comments to comply with `JavadocTagContinuationIndentationCheck` rules.
This PR should be merged after we release the new Checkstyle version and `pgjdbc` upgrades to it. Without this change, existing code that was previously compliant may fail validation checks.
=> Fix JavadocTagContinuationIndentation in AfterBeforeParameterResolver

pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
Previously, #abort was using SQLPermission("callAbort").checkGuard(this) to test abort permission, however, Java 24 permanently removes Security Manager, so checkGuard always throws an exception.
The fix is to verify if the security manager is installed before checking the permission.
Fixes https://github.com/pgjdbc/pgjdbc/issues/3581
=> fix: make PgConnection#abort compatible with Java 24

build-logic/jvm/src/main/kotlin/build-logic.test-junit5.gradle.kts
See https://github.com/webcompere/system-stubs/issues/93
=> chore: appply the latest byte-buddy version for tests so we support the latest Java versions

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java, pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
Postgres compatible databases like https://github.com/crate/crate can use PG JDBC as driver. Often the PG JDBC driver is used by a tool or integration (JetBrains DataGrip to name one). As CrateDB isn't fully PG compatible, this patch will make life a bit easier for our users. The issue has been reported as https://github.com/crate/crate/issues/17393.
=> Set column name explicitely when using `current_database()` in queries

.github/workflows/buildcache.yml, .github/workflows/codeql.yml, .github/workflows/debezium.yml, .github/workflows/main.yml, .github/workflows/nightlysnapshot.yml, CONTRIBUTING.md, appveyor.yml, build-logic/build-parameters/build.gradle.kts, certdir/server/pg_hba.conf, docker/postgres-server/scripts/entrypoint.sh
Note: the resulting binaries still target Java 8, so the change should not be use-visible.
However, we would use a newer toolset which should result in fewer bugs in the generated binaries.
=> chore: use Java 21 for building pgjdbc by default

docs/content/documentation/use.md, pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ParameterStatusTest.java
Fixes #3508, by adding back the application_name startup parameters during the initial connection.
=> Add back application name setting

.github/workflows/matrix.mjs, pgjdbc/src/test/java/org/postgresql/test/jdbc2/CursorFetchTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
It might detect regressions if `adaptiveFetch` interferes with the rest of the features.
=> test: add CI executions with adaptive_fetch=true by default

.github/workflows/matrix.mjs, pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
It might detect regressions if `reWriteBatchedInserts` interferes with the rest of the features.
=> test: add tests with reWriteBatchedInserts=true

.github/workflows/gradle-dependency-submit.yaml
See https://github.com/gradle/actions/blob/768a17f3488dc3fe0155ff431553e1f53d57e22e/dependency-submission/README.md#the-dependency-submission-action
=> chore: add gradle/actions/dependency-submission so GitHub shows all dependencies used when building pgjdbc

docs/content/documentation/server-prepare.md, pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTest.java
Previously, the code for `.isValid()` was using `executeWithFlags("", QueryExecutor.QUERY_EXECUTE_AS_SIMPLE)`
However, the execution still went with extended query protocol since `QueryExecutorImpl#updateQueryMode` trimmed the flag in `preferQueryMode=extended` (default) mode.
It does not feel right to trim the flag there since the intention of the option was to "prefer" query mode unless specified explicitly.
The case is identified and tested in `AutoRollbackTest`: isValid should return true after statements like DEALLOCATE, `DISCARD`, and so on.
See https://github.com/pgjdbc/pgjdbc/pull/3631
Fixes https://github.com/pgjdbc/pgjdbc/issues/3630
=> fix: ensure Connection.isValid() returns true even if prepared statements deallocate

pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
9th column should be KEY_SEQ, however it was 11 in case the resultset was empty
This is a fix for #3588
=> fix: make sure getImportedExportedKeys returns columns in consistent order

.github/workflows/ossf-scorecard.yaml, README.md
See https://github.com/ossf/scorecard
Ossf scorecard has previously scanned pgjdbc, and the report was already available at https://scorecard.dev/viewer/?uri=github.com/pgjdbc/pgjdbc
The PR adds on-commit scan, and a badge to the readme.
=> test: add ossf-scorecard security scanning

.github/workflows/codeql.yml, .github/workflows/gradle-dependency-submit.yaml, .github/workflows/ossf-scorecard.yaml, .github/workflows/release-drafter.yml
The top-level permissions configure the defaults, so we'd better have a default read-only configuration so the newly added jobs would not accidentally get write permissions.
=> chore: add top-level read-only permissions for GitHub Actions when missing

pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ArrayTest.java
Fixes #3743:
1. In calcRemainingDataLength, we should traverse the current dimension to get the correct pos.
2. Obviously, the positions of the parameters elementOid and pos are reversed.
=> fix: traverse the current dimension to get the correct pos in PgArray#calcRemainingDataLength

.github/workflows/pgp-key-maintenance.yaml
See https://github.com/vlsi/provision-release-pgp-key
We can copy-paste the workflow right into pgjdbc repository or we can have it as reusable workflow.
Any thoughts?
See also:
* https://slxh.nl/blog/2016/pgp-and-dns/
* https://www.netmeister.org/blog/dnssec-dane.html#dane
=> chore: add GitHub Actions workflow for generating release PGP key

.github/workflows/main.yml
This enables us to have a fixed set of "required checks to pass"
=> chore: remove JDK versions from the key workflow names

pgjdbc-osgi-test/build.gradle.kts
Previously, bcel was updated only in testRuntimeClasspath, so it triggered alarms like "old BCEL used in compilation".
Now we use an updated bcel for both compile and the runtime, and we use constraints rather than direct dependency, so bcel no longer participates in the classpath if third-party libraries move away from bcel.
=> chore: use bump org.apache.bcel:bcel test dependency in testCompileClasspath as well

docs/content/documentation/use.md, pgjdbc/src/main/java/org/postgresql/PGProperty.java, pgjdbc/src/main/java/org/postgresql/core/BaseConnection.java, pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java, pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java, pgjdbc/src/test/java/org/postgresql/jdbc/AbstractArraysTest.java, pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
Addresses: https://github.com/pgjdbc/pgjdbc/issues/367
When calling numeric getters (getByte(), getInt(), getLong(), getShort(), getFloat(), getDouble(), getBigDecimal()) on PostgreSQL boolean columns, the driver
throws PSQLException: Bad value for type byte : f. 
Added a new connection property `convertBooleanToNumeric` that enables automatic conversion of PostgreSQL boolean values to numeric types:
- 't' → 1
- 'f' → 0
- Works with boolean columns
- Property cached per connection for optimal performance
- Boolean column type detection prevents false positive conversions
// JDBC URL
jdbc:postgresql://host:5432/db?convertBooleanToNumeric=true
// HikariCP
config.addDataSourceProperty("convertBooleanToNumeric", "true");
// Spring Boot …
=> Add configurable boolean-to-numeric conversion for ResultSet getters

build.gradle.kts
`projects.pgjdbc` is the root project (it makes no sense publishing it)
`projects.postgresql` is the dirver jar (it should be published)
=> chore: fix published project name
