- build.xml
Junit was specifying the version in the pom
Fixes #251
> fix: Make junit optional in the pom

- README.md
> Added commit message outline

- org/postgresql/core/v3/DescribeRequest.java
- org/postgresql/core/v3/ExecuteRequest.java
- org/postgresql/core/v3/QueryExecutorImpl.java
This makes QueryExecutorImpl more type safe.
> refactor: use Dequeue<...> instead of raw ArrayList in v3.QueryExecutorImpl

- doc/pgjdbc.xml
- org/postgresql/core/CachedQuery.java
- org/postgresql/core/JdbcCallParseInfo.java
- org/postgresql/core/NativeQuery.java
- org/postgresql/core/Parser.java
- org/postgresql/jdbc2/AbstractJdbc2Statement.java
- org/postgresql/jdbc2/CachedQueryCreateAction.java
- org/postgresql/jdbc2/CallableQueryKey.java
- org/postgresql/util/LruCache.java
This PR cleans up comments from #311 and #319
> Cleanup prepared statement cache

- org/postgresql/jdbc2/AbstractJdbc2DatabaseMetaData.java
@sehrope, @dmap do you see any issues with this ?
> remove types in pg_catalog, pg_toast, information_schema

- ubenchmark/src/main/java/org/postgresql/benchmark/profilers/FlightRecorderProfiler.java
- ubenchmark/src/main/java/org/postgresql/benchmark/statement/BindBoolean.java
- ubenchmark/src/main/java/org/postgresql/benchmark/time/AddPaddingZeros.java
Add "bind boolean", "padding zeroes" benchmarks, and missing FlightRecorderProfiler
> chore: add more benchmarks, add missing FlightRecorderProfiler

- org/postgresql/jdbc2/AbstractJdbc2Connection.java
- org/postgresql/jdbc2/AbstractJdbc2Statement.java
- org/postgresql/test/jdbc2/StatementTest.java
If client uses finalizers to cleanup the statement, it should not result in CME
fixes #368, #392
> fix: ConcurrentModificationException when calling PreparedStatement.close from a concurrent thread

- lib/.gitignore
xml-resolver has been visibly forgotten.
> Add missing entry in lib/.gitignore

- org/postgresql/test/jdbc3/Jdbc3CallableStatementTest.java
Adding the test to increase test coverage of sql parser
> test: add {?= call mysum(?, ?)} kind of test for CallableStatement

- README.md
This PR adds the following section to readme: https://github.com/Gordiychuk/pgjdbc/tree/dev_guide#-coding-guidelines
> doc: add coding guidelines to readme

- README.md
> docs: fix broken link to testing README

- pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/ArrayTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/BatchFailureTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/Jdbc2TestSuite.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/ArrayTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/Jdbc4TestSuite.java
> fix: PgArray returning null for binary arrays

- packaging/rpm/postgresql-jdbc.spec.tpl
> packaging: heal Fedora build

- pgjdbc/src/main/java/org/postgresql/Driver.java
- pgjdbc/src/main/java/org/postgresql/PGConnection.java
- pgjdbc/src/main/java/org/postgresql/PGNotification.java
- pgjdbc/src/main/java/org/postgresql/PGRefCursorResultSet.java
- pgjdbc/src/main/java/org/postgresql/PGResultSetMetaData.java
- pgjdbc/src/main/java/org/postgresql/PGStatement.java
- pgjdbc/src/main/java/org/postgresql/copy/CopyIn.java
- pgjdbc/src/main/java/org/postgresql/copy/CopyOperation.java
- pgjdbc/src/main/java/org/postgresql/core/BaseConnection.java
- pgjdbc/src/main/java/org/postgresql/core/BaseStatement.java
- pgjdbc/src/main/java/org/postgresql/core/ParameterList.java
- pgjdbc/src/main/java/org/postgresql/core/ProtocolConnection.java
- pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java
- pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java
- pgjdbc/src/main/java/org/postgresql/ds/PGPoolingDataSource.java
- pgjdbc/src/main/java/org/postgresql/fastpath/Fastpath.java
- pgjdbc/src/main/java/org/postgresql/gss/MakeGSS.java
- pgjdbc/src/main/java/org/postgresql/jdbc/AbstractBlobClob.java
- pgjdbc/src/main/java/org/postgresql/jdbc/EscapedFunctions.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/main/java/org/postgresql/largeobject/LargeObject.java
- pgjdbc/src/main/java/org/postgresql/ssl/jdbc4/LibPQFactory.java
- pgjdbc/src/main/java/org/postgresql/util/ObjectFactory.java
- pgjdbc/src/main/java/org/postgresql/util/PGBinaryObject.java
- pgjdbc/src/main/java/org/postgresql/util/PGtokenizer.java
remove access modifiers from interfaces
Java 5's for-each
simplify some expressions
> style: cleanup and Java 5' features

- pgjdbc/src/main/java/org/postgresql/core/PGStream.java
- pgjdbc/src/main/java/org/postgresql/core/v2/ConnectionFactoryImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v2/FastpathParameterList.java
- pgjdbc/src/main/java/org/postgresql/core/v2/ProtocolConnectionImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v2/QueryExecutorImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v3/ProtocolConnectionImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java
- pgjdbc/src/main/java/org/postgresql/gss/GssAction.java
- pgjdbc/src/main/java/org/postgresql/sspi/NTDSAPIWrapper.java
- pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java
change method names to start with a lower case letter
relates to Fix huntbugs warnings #586
> style: change method names to start with a lower case letter

- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
fix this warnings:
Invocation of toString() on an array
Inefficient use of keySet() iterator instead of values() iterator
Inefficient use of keySet() iterator instead of entrySet() iterator
relates to Fix huntbugs warnings #586
> refactor: fix some hintbugs warnings

- pgjdbc/src/main/java/org/postgresql/PGProperty.java
- pgjdbc/src/main/java/org/postgresql/core/PGStream.java
- pgjdbc/src/main/java/org/postgresql/core/Parser.java
- pgjdbc/src/main/java/org/postgresql/core/v3/CompositeParameterList.java
- pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGbox.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGcircle.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGline.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGlseg.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGpoint.java
- pgjdbc/src/main/java/org/postgresql/jdbc/BatchResultHandler.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgParameterMetaData.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java
- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
- pgjdbc/src/main/java/org/postgresql/ssl/MakeSSL.java
- pgjdbc/src/main/java/org/postgresql/ssl/jdbc4/LazyKeyManager.java
- pgjdbc/src/main/java/org/postgresql/ssl/jdbc4/LibPQFactory.java
- pgjdbc/src/main/java/org/postgresql/util/GT.java
make  Gt.tr with varargs argument and, as consequence,
delete redundant array creation
> refactor: make method Gt.tr with varargs argument

- .travis.yml
- .travis/travis_build.sh
- anorm-sbt/.gitignore
- anorm-sbt/README.md
- anorm-sbt/build.sbt
- anorm-sbt/conf/application.conf
- anorm-sbt/project/build.properties
- anorm-sbt/project/plugins.sbt
- anorm-sbt/test/ExampleSpec.scala
- pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/ArrayTest.java
> fix: json should be returned as PGObject, not as String for backward compatibility reasons

- README.md
> chore:: add coverage badge

- CONTRIBUTING.md
- README.md
> docs: improve readme.md

- LICENSE
- pgjdbc/pom.xml
Clarify license of the project in the pom.xml
Closes: [Issue 335](https://github.com/pgjdbc/pgjdbc/issues/335), [Issue 336](https://github.com/pgjdbc/pgjdbc/issues/336)
> docs: clarify license in pom

- .travis.yml
> test: add CI tests against PostgreSQL 8.3

- pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationStatusTest.java
- pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java
- pgjdbc/src/test/java/org/postgresql/replication/PhysicalReplicationTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/CopyBothResponseTest.java
Related postgres commit: https://github.com/postgres/postgres/commit/d10c626de47d8b048b663471c7785603a2ec8641
> test: yet another rename to use "lsn" not "location" in Pg10.

- CONTRIBUTING.md
> docs: fix header in CONTRIBUTING

- pgjdbc/src/main/java/org/postgresql/core/PGStream.java
make PGStream closable + remove receiveTupleV2 method
> refactor: remove dead code from PGStream, implement Closeable

- docs/documentation/head/thread.md
Either this or change the note to say we don't support threading ?
> remove notes about multithreading

- docs/development/development.html
> docs: fix test db password in docs

- pgjdbc/src/test/java/org/postgresql/test/util/ServerVersionTest.java
> Update ServerVersionTest to compare versions

- pgjdbc/pom.xml
- pgjdbc/src/main/checkstyle/checks.xml
- ubenchmark/pom.xml
> chore: update checkstyle

- CHANGELOG.md
- docs/_posts/2018-01-17-42.2.0-release.md
Fix markdown syntax in the item Make GSS JAAS login optional.
[skipci]
> Fix style changelog

- docs/documentation/head/geometric.md
metioned -> mentioned
Chapter 12 -> Chapter 13
change sample code to match PgJDBC code style guidelines
explicitly close (via try-with-resources) the Statement and ResultSet in retrieveCircle(Connection)
> docs: fix spelling and chapter, update sample code

- pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
> style: spelling in comment

- pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
> spelling mistake correction

- .travis/travis_install_head_postgres.sh
> fix: error on travis build head postgres

- pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
1734 - 1738 - I think this is what the original comment was trying to convey
1743 - 1744 - clarify the meaning of the "usePortal" flag
> style: rephrase comment on named portals

- pgjdbc/src/main/java/org/postgresql/core/CachedQuery.java
- pgjdbc/src/main/java/org/postgresql/core/CachedQueryCreateAction.java
- pgjdbc/src/main/java/org/postgresql/core/JdbcCallParseInfo.java
- pgjdbc/src/main/java/org/postgresql/core/Parser.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
> refactor: remove obsolete outParmBeforeFunc

- certdir/README.md
add hostdb for ssl tests
* [x ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x] Have you successfully run tests with your changes locally?
> docs: update README.md for SSL tests

- .travis.yml
> attempt jdk 10 and postgresql 10

- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
> Issue 1106

- docs/_posts/2017-02-20-42.0.0-release.md
- docs/_posts/2018-01-17-42.2.0-release.md
- docs/documentation/92/escaped-functions.md
- docs/documentation/92/geometric.md
- docs/documentation/92/ssl.md
- docs/documentation/92/use.md
- docs/documentation/93/escaped-functions.md
- docs/documentation/93/geometric.md
- docs/documentation/93/ssl.md
- docs/documentation/93/use.md
- docs/documentation/94/escaped-functions.md
- docs/documentation/94/geometric.md
- docs/documentation/94/ssl.md
- docs/documentation/94/use.md
- docs/documentation/changelog.md
- docs/documentation/head/server-prepare.md
- docs/documentation/head/ssl.md
- docs/documentation/head/use.md
feel free to undo or amend any changes in this PR
> Fix typos in docs/

- CONTRIBUTING.md
[1] 2a715a988bead78aeb0a341a37faf86b62df4975
Signed-off-by: Mykola Nikishov <mn@mn.com.ua>
> Fix link to Test Suite Howto

- docs/documentation/head/connect.md
Add DEM format details and instructions on how to convert from PEM to DER format as discussed in issue #1364
> docs: Add DEM format details for `sslkey`

- docs/documentation/head/connect.md
- pgjdbc/pom.xml
> Update waffle-jna to new artifact coordinates

- pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java
- pgjdbc/src/main/java/org/postgresql/ds/PGPooledConnection.java
- pgjdbc/src/main/java/org/postgresql/ssl/LazyKeyManager.java
- pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java
replace toArray(new T[size]) with toArray(new T[0]) for better performance
https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion (also contains benchmarks).
> Optimize toArray (#1395)

- README.md
add appveyor build status badge
additionally create a PR as a test
> add appveyor build status badg

- pgjdbc/src/main/java/org/postgresql/Driver.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DriverTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/AbortTest.java
add tests that check behaviour with null-arguments
javadoc for tested methods:
* https://docs.oracle.com/javase/8/docs/api/java/sql/Driver.html#connect-java.lang.String-java.util.Properties-
* https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#abort-java.util.concurrent.Executor-
> test: add tests for Driver and PgConnection

- pgjdbc/src/main/java/org/postgresql/ds/PGConnectionPoolDataSource.java
> fix: fix javadoc for defaultAutoCommit to default to true

- docs/documentation/head/logging.md
> They are only cosmetic changes.
> docs: cosmetic fixes on sample logging settings

- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
> change IS_GENERATED to IS_GENERATEDCOLUMN as per spec

- pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java
undoes part of PR #1486  which broke a number of tests
> undo part of fixbugs pull request that set returned NULL mistakenly

- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimestampTest.java
> fix #1499 rounding for timestamps truncated to dates before 1970

- CONTRIBUTING.md
Reverts pgjdbc/pgjdbc#1479
Until I confirm that it is correct.
> Revert "Fix maven coordinates"

- docs/documentation/head/resultset.md
> docs: update resultset.md in head to reflect 94 (#1528)

- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
> Log ignoring rollback when no transaction in progress

- docs/_posts/2019-09-10-42.2.7-release.md
3. [ ] Have you added your new test classes to an existing test suite?
> fix release notes for jekyll

- CHANGELOG.md
- docs/_posts/2019-09-13-42.2.8-release.md
> release notes for 42.2.8

- docs/documentation/head/connect.md
* [ x] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
This is a small documentation fix. I hope it will save that 10 hours for others...
> fix documentation on generating the pk8 key. closes: #1585

- README.md
- docs/documentation/head/connect.md
Fixes #1589
All Submissions:
[YES] Have you followed the guidelines in our Contributing document?
[YES] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
New Feature Submissions:
[YES] Does your submission pass tests?
[YES] Does mvn checkstyle:check pass ?
Changes to Existing Features:
[NO] Does this break existing behaviour? If so please explain.
Have you added an explanation of what your changes do and why you'd like us to include them?
[NO] Have you written new tests for your core changes, as applicable?
[YES] Have you successfully run tests with your changes locally?
> fix camel case writing of 'cleanupSavepoints'

- docs/documentation/head/prepare.md
> Update authentication methods supported to include gss

- docs/documentation/head/connect.md
> chore: Document how to use unix domain sockets. 

- pgjdbc/src/main/java/org/postgresql/Driver.java
#1618 Adjust the default port to 5432.
> Adjust the default port to 5432.

- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc42/Jdbc42CallableStatementTest.java
> fix: Unable to register out parameter Issue #1646

- pgjdbc/pom.xml
> chore: upgrade checkstyle to 8.28

- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
> clean up 1648 - sync error message value with tested value

- docs/documentation/head/ext.md
> Typo in documentation (case instead of cast)

- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/ConnectionTest.java
Connection should return an empty typeMap instead of null as per spec
> fix: getTypeMap() returning null

- pgjdbc/src/test/java/org/postgresql/replication/LogicalReplicationTest.java
reported by Kenichi Nakamura in the mailing list
> fix: replication test we were not waiting for the view to be updated

- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
Identified with https://github.com/pgjdbc/pgjdbc/pull/1814
> fix: avoid preparedStatement leak when using updateable ResultSet via insert/update/refreshRow

- .github/workflows/main.yml
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- test-gss/build.gradle
- test-gss/src/main/groovy/Kerberos.groovy
- test-gss/src/main/groovy/PgJDBC.groovy
- test-gss/src/main/groovy/Postgres.groovy
- test-gss/src/main/groovy/TestPostgres.groovy
- test-gss/src/main/groovy/Util.groovy
> use connection encoding instead of hard coding ISO-8859-1

- docs/documentation/head/classpath.md
- docs/documentation/head/prepare.md
- docs/documentation/head/setup.md
Please review and provide suggestions. Thanks
> update docs into the next century

- CHANGELOG.md
- docs/_posts/2020-08-14-42.2.15-release.md
> move fix to correct place and remove duplicate

- CHANGELOG.md
- pgjdbc/src/main/java/org/postgresql/geometric/PGbox.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGcircle.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGline.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGlseg.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGpath.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGpoint.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGpolygon.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/main/java/org/postgresql/util/PGInterval.java
- pgjdbc/src/main/java/org/postgresql/util/PGmoney.java
- pgjdbc/src/main/java/org/postgresql/util/PGobject.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGObjectGetTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/PGObjectSetTest.java
> Handle nulls when the following clasess are used: PGbox, PGcircle, PGline, PGlseg, PGpath, PGpoint, PGpolygon, and PGmoney

- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc42/Jdbc42CallableStatementTest.java
> Allow setNull with a REF_CURSOR type

- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetMetaDataTest.java
Add smallserial metadata info.
> feat: add smallserial metadata

- CONTRIBUTING.md
> Small tweaks to discussion of null safety

- .github/workflows/main.yml
> Update apt before trying too install packages for gss test

- build.gradle.kts
> add version to javadoc title

- docs/documentation/head/connect.md
* [y] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [y] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
Documentation patch to fix indentation and add examples for the "options" parameter.
> Connect example

- TESTING.md
Document the contrib/lo and contrib/test_decoding requirements
> Document lo and test_decoding requirements

- pgjdbc/src/main/java/org/postgresql/util/MD5Digest.java
have static array of hex characters
collapse some intermediate actions/state
> improv: minor optimizations in MD5Digest

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
- pgjdbc/src/main/java/org/postgresql/util/internal/Unsafe.java
- settings.gradle.kts
See https://github.com/pgjdbc/pgjdbc/pull/2012
> chore: verify code via forbidden-apis (jdk-internal and jdk-non-portable signatures)

- TESTING.md
> style: fix minor style inconsistency

- pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java
> style: fix typo in error message

- CHANGELOG.md
- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/test/java/org/postgresql/test/TestUtil.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/ConnectionValidTimeoutTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/Jdbc4TestSuite.java
- pgjdbc/src/test/java/org/postgresql/test/util/StrangeProxyServer.java
Rebased #2022 with an updated test. See there for more details.
Once this cycles through CI I'll merge it and cherry pick it.
> Fix isValid() to not wait longer than network timeout

- CHANGELOG.md
- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/test/java/org/postgresql/test/TestUtil.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/ConnectionValidTimeoutTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/Jdbc4TestSuite.java
- pgjdbc/src/test/java/org/postgresql/test/util/StrangeProxyServer.java
#2022 cherry picked for master.
> Fix isValid() cherry-picked for master

- pgjdbc/src/main/java/org/postgresql/util/PGtokenizer.java
- pgjdbc/src/test/java/org/postgresql/util/PGtokenizerTest.java
* [x ] Have you followed the guidelines in our [Contributing](https://github.com/pgjdbc/pgjdbc/blob/master/CONTRIBUTING.md) document?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
> PGtokenizer ParseError

- CHANGELOG.md
- contributors.json
- docs/_posts/2021-02-18-42.2.19-release.md
> Update CHANGELOG and posts to reflect todays date

- docs/_posts/2021-02-18-42.2.19-release.md
This is non-consequential to the code, just formatting for the website
> move comments to correct location

- pgjdbc/src/main/java/org/postgresql/PGProperty.java
Found indentation errors during fix https://github.com/checkstyle/checkstyle/pull/9331
> Fixed indentation of PGProperty

- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
We failed to add in the 'I' index type.
I'm still not sure if we can have partitioned system indexes?
> fix: Partitioned indexes were not found fixes (#2078)

- README.md
- pgjdbc/src/main/java/org/postgresql/Driver.java
- pgjdbc/src/main/java/org/postgresql/core/PGStream.java
- pgjdbc/src/main/java/org/postgresql/util/HostSpec.java
- pgjdbc/src/test/java/org/postgresql/test/util/HostSpecTest.java
> feat: Add new property to specify local Socket Address (#2081)

- pgjdbc/src/test/java/org/postgresql/test/jdbc4/BlobTest.java
Found indentation error during fix of checkstyle issue 3132
> Fixed indentation of BlobTest.java

- pgjdbc/src/test/java/org/postgresql/core/v3/V3ParameterListTests.java
Found wrong indentation while fixing checkstyle issue 618
> Fixed indentation of V3ParameterListTest.java

- CHANGELOG.md
- pgjdbc/src/main/java/org/postgresql/core/Field.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
> cherry-pick PR #2092 PgDatabaseMetaData.getTables() should return UPPERCASE column names as per spec

- CHANGELOG.md
- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataTest.java
> fix: backpatch PR#2174 to Fix metadata functions getProcedures() and getFunctions() to ignore search_path

- CHANGELOG.md
- docs/_posts/2021-06-10-42.2.21-release.md
small changes to fix formatting issues
> Fixchangelog [skip-ci]

- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
This PR is to backpatch the testing fixes in #2251 into the v42.2 branch.
> Backpatching #2251 into 42 2

- pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
This just mimics code in release/42.2
> fix: Regressions caused by PR#1949

- pgjdbc/src/main/java/org/postgresql/PGProperty.java
> fix spacing on GSS_ENC_MODE [SKIP-CI]

- CONTRIBUTING.md
> [typo] typo in CONTRIBUTING.md

- docs/documentation/head/connect.md
`OutOfMemoryException` => `OutOfMemoryError`
> [typo] in connect.md

- pgjdbc/src/main/java/org/postgresql/util/PGPropertyPasswordParser.java
- pgjdbc/src/main/java/org/postgresql/util/PGPropertyServiceParser.java
- pgjdbc/src/test/java/org/postgresql/util/PGPropertyPasswordParserTest.java
- pgjdbc/src/test/java/org/postgresql/util/PGPropertyServiceParserTest.java
- pgjdbc/src/test/resources/pg_service/postgresql/pg_service.conf
- pgjdbc/src/test/resources/pg_service/postgresql/pgpass.conf
make the checking for resource as a URL more robust
> fix: parsing service file tests for windows

- pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
When ConnectionFactoryImpl#tryConnect fails with an exception,
a newly created PGStream is left without closing it. The finalizer
handles the close, so it's not a problem most of the time.
But Finalizer has no guarantees on the time when it'll close
the resource. The resource may hang open for a longer period.
After the change PGStream is closed just before losing the reference.
> fix: Connection leak in ConnectionFactoryImpl#tryConnect #2350

- pgjdbc/src/main/java/org/postgresql/translation/messages_ru.java
> Misprint in messages_ru.java

- pgjdbc/src/main/java/org/postgresql/PGProperty.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc3/TestReturning.java
after fix of checkstyle bug https://github.com/checkstyle/checkstyle/pull/11245 new violations discovered in pgjdbc, this PR fixes them
> minor: fix checkstyle violations for empty lines in enum

- pgjdbc/src/main/java/org/postgresql/gss/GssAction.java
- pgjdbc/src/main/java/org/postgresql/gss/GssEncAction.java
- pgjdbc/src/main/java/org/postgresql/gss/MakeGSS.java
> Trying to fix: https://github.com/pgjdbc/pgjdbc/issues/2469

- README.md
I forgot to update to change this one
> docs: fix readme.md after #2495

- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
Fixes #2518 
Signed-off-by: Sven Diedrichsen <sdiedrichsen@yahoo.de>
> Enhancement: Made TimestampUtils.utcTz static and renamed to UTC_TIMEZONE

- .github/workflows/gradle-wrapper-validation.yml
See https://github.com/gradle/wrapper-validation-action
> chore: add gradle/wrapper-validation-action

- test-gss/build.gradle
> Bump Groovy to version 3 to fix compile errors with jdk17

- pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
> fix: revert change in PR#2597 where float was aliased to float4 from float8

- .github/workflows/gh-pages.yml
> publish to external repository

- docs/content/documentation/_index.md
- docs/content/documentation/binary-data.md
- docs/content/documentation/callproc.md
- docs/content/documentation/datasource.md
- docs/content/documentation/escapes.md
- docs/content/documentation/logging.md
- docs/content/documentation/query.md
- docs/content/documentation/reading.md
- docs/content/documentation/server-prepare.md
- docs/content/documentation/setup.md
- docs/content/documentation/ssl.md
- docs/content/documentation/thread.md
- docs/content/documentation/use.md
- docs/data/versions.toml
- docs/layouts/shortcodes/past-versions.html
- docs/layouts/shortcodes/recent-versions.html
fix docs in general
add TM to PostgreSQL
> fix maven coordinates

- pgjdbc/src/main/java/org/postgresql/largeobject/LargeObject.java
- pgjdbc/src/main/java/org/postgresql/replication/PGReplicationStream.java
minor: Update the LeftCurly according to the updation in checkstyle
> minor: Update the LeftCurly according to the updation in checkstyle

- pgjdbc/src/main/java/org/postgresql/core/Oid.java
> style: Style only change to use diamond operator in Oid

- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
> minor: set private attribute as final

- pgjdbc/src/main/java/org/postgresql/core/ConnectionFactory.java
> minor: log warning on stream close failure

- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/ResultSetTest.java
https://github.com/pgjdbc/pgjdbc/issues/2696
> fix binary transfer floating point overflow

- docs/content/changelogs/2023-01-31-42.5.2-release.md
- docs/content/changelogs/2023-02-03-42.5.3-release.md
> minor changes

- docs/content/changelogs/2021-12-22-log4j.md
- docs/content/download/_index.md
- docs/layouts/changelogs/list.html
add SNAPSHOT link to download page
> make changelogs more compact, only show the link to the changelog

- pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/SchemaTest.java
PostgreSQL allows you to label a function as immutable even if it is not. But this can lead to non-deterministic results. 
See:
https://www.postgresql.org/docs/current/sql-createfunction.html
```
IMMUTABLE indicates that the function cannot modify the database and
always returns the same result when given the same argument values;
that is, it does not do database lookups or otherwise use information
not directly present in its argument list. If this option is given,
any call of the function with all-constant arguments can be immediately
replaced with the function value.
```
And:
https://www.postgresql.org/docs/current/xfunc-volatility.html
```
Labeling a function IMMUTABLE when it really isn't might allow it
to be prematurely folded to a constant during planning, resulting
in a stale …
```
> fix: Update function volatility in SchemaTest setup

- .github/workflows/main.yml
> Make sure that github CI runs tests on all PRs

- CHANGELOG.md
- docs/content/changelogs/2023-02-15-42.5.4-release.md
- docs/content/changelogs/2023-02-16-42.5.4-release.md
- docs/data/homepagedata.toml
- docs/data/versions.toml
- docs/layouts/partials/home/info.html
docs: Update site for release 42.5.x cherry-pick document changes from release 42.5.4
> Update site for release 42.5.4

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Fixes https://github.com/pgjdbc/pgjdbc/issues/2799
> feat: add Release Drafter for preparing release notes on GitHub

- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
> fix: remove redundant code

- renovate.json
Let's try if that reduces the update noise enough.
> chore: reduce Renovate frequency to once every 3 weeks

- docs/content/documentation/use.md
> Remove stray whitespace and use code formatting

- docs/layouts/partials/home/info.html
Could also use `<code>` tags for `synchronized` and `finalize`.
> fix: typos in info.html

- pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java
> put double ' around log parameter

- docs/content/security/_index.md
> update security message

- pgjdbc/src/main/java/org/postgresql/core/QueryExecutor.java
- pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/StatementTest.java
checkConnectionQuery was never ever set or used, removed
> Use simple query for isValid. Using Extended query sends two messages

- pgjdbc/src/main/java/org/postgresql/jdbc/ArrayDecoding.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
for now see if this fails any tests
> WIP speed up getDate

- pgjdbc/src/main/java/org/postgresql/jdbc/ArrayDecoding.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
> Revert "speed up getDate by parsing incoming bytes instead of String"

- docs/content/changelogs/2023-11-20-42.7.0-release.md
- docs/content/changelogs/2023-12-06-42.7.1-release.md
> Fix 2 changelog entry titles

- TESTING.md
> The Gradle config enforces 17+

- pgjdbc/src/main/java/org/postgresql/jdbc/ArrayDecoding.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgCallableStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java
- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
Keep old API and deprecate
Add in new binary API
> Speed up getDate by parsing bytes instead of String

- .github/workflows/main.yml
- .github/workflows/matrix.js
The self hosted runner no longer builds and the owner is no longer maintaining it.
> remove self-hosted runner

- pgjdbc/src/main/java/org/postgresql/core/CommandCompleteParser.java
- pgjdbc/src/test/java/org/postgresql/core/CommandCompleteParserTest.java
> Fix #3234 - Return -1 as update count for stored procedure calls

- CHANGELOG.md
- TESTING.md
- docs/content/changelogs/2017-02-20-42.0.0-release.md
- docs/content/changelogs/2023-03-17-42.6.0-release.md
- docs/content/documentation/server-prepare.md
- docs/static/js/menutoggle.js
- pgjdbc/src/main/java/org/postgresql/core/VisibleBufferedInputStream.java
- pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
- pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java
- pgjdbc/src/main/java/org/postgresql/util/PGInterval.java
- pgjdbc/src/main/java/org/postgresql/xa/PGXAConnection.java
- pgjdbc/src/test/java/org/postgresql/core/CommandCompleteParserNegativeTest.java
> Fixed typos in all source code and documentations

- pgjdbc/src/main/java/org/postgresql/translation/ko.po
added ko.po file for translation
> Add translation file

- pgjdbc/src/test/java/org/postgresql/test/jdbc4/jdbc41/GetObjectTest.java
fix test to use try/catch as well
> Test for +/- infinity double values

- docs/content/documentation/use.md
> Update use.md, typo

- pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java
see https://github.com/pgjdbc/pgjdbc/issues/2882#issuecomment-1519757606
Apparently, "pre-describe" was there for some reason, so let's see what breaks if we remove it.
However, since insert-batch-rewrite splits a query into different queries, the pre-describe logic was not probably working properly for them anyway.
Just in case, preDescribe has been added in https://github.com/pgjdbc/pgjdbc/commit/a8e937881cc208c1b5f50cdc18730a2f340d3ac6#diff-187b86a2e212c5ab745cad4efe9147e999478a079e8ffab5d05f5d4f3db69855R2853-R2860
fixes #2882
> fix: remove preDescribe from internalExecuteBatch

- CHANGELOG.md
- contributors.json
- docs/content/changelogs/2024-03-13-42.2.29-release.md
- docs/content/changelogs/2024-03-13-42.3.10-release.md
- docs/content/changelogs/2024-03-13-42.4.5-release.md
- docs/content/changelogs/2024-03-13-42.5.6-release.md
- docs/content/changelogs/2024-03-13-42.6.2-release.md
- docs/content/changelogs/2024-03-14-42.7.3-release.md
- docs/content/changelogs/2024-08-22-42.7.4-release.md
- docs/data/homepagedata.toml
- docs/data/versions.toml
Also added change logs for previous versions that were missing
> Prepare for 42.7.4 release

- packaging/rpm/postgresql-jdbc.spec.tpl
Fedora rename commit: https://src.fedoraproject.org/rpms/maven-plugin-bundle/c/87020cfee32050a555090936074f8c67def6aa40?branch=rawhide
> Package was renamed to maven-bundle-plugin

- packaging/rpm/postgresql-jdbc.spec.tpl
> Update rpm postgresql-jdbc.spec.tpl with scram-client

- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
Fixes https://github.com/pgjdbc/pgjdbc/issues/3385 "Column alias names for metadata returned by getSchemas() violate JDBC spec"
> Fix getSchemas()

- pgjdbc/src/main/java/org/postgresql/core/AsciiStringInterner.java
- pgjdbc/src/main/java/org/postgresql/geometric/PGpoint.java
- pgjdbc/src/main/java/org/postgresql/util/ByteStreamWriter.java
follow up of my previous PR https://github.com/pgjdbc/pgjdbc/pull/3397
I forgot to edit some files so our CI was still complaining about it: https://checkstyle.semaphoreci.com/jobs/3916946d-b853-406b-b72e-70d0f92b71af
This should have been done in my previous PR but I missed them. I have tried to fix them in this PR.
> fixed remaining paragraphs

- docs/content/documentation/query.md
- docs/content/documentation/server-prepare.md
fixes https://github.com/pgjdbc/pgjdbc/issues/3401
> docs: document infinity and some minor edits

- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java
Before modification:
Red line above indicates a full table scan with poor performance.
After modification:
> Enhance the meta query performance by specifying the oid.

- pgjdbc/src/main/java/org/postgresql/PGProperty.java
- pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
fixes [Issue #3475](https://github.com/pgjdbc/pgjdbc/issues/3475)
> regression: revert change in https://github.com/pgjdbc/pgjdbc/commit/fc60537 

- .github/workflows/matrix.js
See https://github.com/oracle-actions/setup-java/issues/80
> chore: exclude Oracle Java 17 from CI tests

- .github/workflows/main.yml
> Nit: correct message in main.yml test action

- pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java
There have been issues regarding performance, hopefully this helps.
The select is certainly simpler
> use in row values instead of union all

- .github/workflows/matrix.mjs
> ci: add Java 24 tests

- pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/DatabaseMetaDataTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc4/DatabaseMetaDataTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc42/DatabaseMetaDataTest.java
Alternative to https://github.com/pgjdbc/pgjdbc/pull/3528
> refactor empty resultset to use empty result set if the catalog is not correct

- pgjdbc/src/main/java/org/postgresql/core/PgMessageType.java
- pgjdbc/src/main/java/org/postgresql/core/QueryExecutorCloseAction.java
- pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v3/ScramAuthenticator.java
- pgjdbc/src/main/java/org/postgresql/gss/GssAction.java
- pgjdbc/src/main/java/org/postgresql/sspi/SSPIClient.java
Let's see if this passes tests
> add PgMessageType and use static variables for protocol literals

- pgjdbc/src/main/java/org/postgresql/util/PasswordUtil.java
From: https://github.com/checkstyle/checkstyle/pull/16627#issuecomment-2832348354
> fix indentation of return child to allow built pass in Checkstyle's CIs

- build-logic/jvm/src/main/kotlin/build-logic.java.gradle.kts
- packaging/rpm/setup-copr/build-script
- packaging/rpm/setup-copr/copr-setup
> Copr: Use Java 21 as the build dependency

- pgjdbc/src/main/java/org/postgresql/replication/fluent/AbstractStreamBuilder.java
> add override

- pgjdbc/src/main/java/org/postgresql/core/NativeQuery.java
- pgjdbc/src/main/java/org/postgresql/core/ParameterList.java
- pgjdbc/src/main/java/org/postgresql/core/Query.java
- pgjdbc/src/main/java/org/postgresql/core/v3/BatchedQuery.java
- pgjdbc/src/main/java/org/postgresql/core/v3/CompositeParameterList.java
- pgjdbc/src/main/java/org/postgresql/core/v3/CompositeQuery.java
- pgjdbc/src/main/java/org/postgresql/core/v3/DefaultSqlSerializationContext.java
- pgjdbc/src/main/java/org/postgresql/core/v3/QueryExecutorImpl.java
- pgjdbc/src/main/java/org/postgresql/core/v3/SimpleParameterList.java
- pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java
- pgjdbc/src/main/java/org/postgresql/core/v3/SqlSerializationContext.java
- pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java
- pgjdbc/src/main/java/org/postgresql/util/PGbytea.java
- pgjdbc/src/test/java/org/postgresql/core/v3/adaptivefetch/AdaptiveFetchCacheTest.java
- pgjdbc/src/test/java/org/postgresql/test/jdbc2/PreparedStatementTest.java
Test case reproducing issue of #3365.
Fix by @kimjand
> fix: EOFException on PreparedStatement#toString with unset bytea parameter since 42.7.4

- renovate.json
It includes a broader set of defaults: https://docs.renovatebot.com/presets-config/#configbest-practices
> chore: use config:best-practices preset for Renovate

- pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java
- pgjdbc/src/test/java/org/postgresql/jdbc/PgSQLXMLTest.java
Simple fix for allowing to use a custom PGXmlFactoryFactory
> Fix #3747: Incorrect class comparison in PGXmlFactoryFactory validation

- pgjdbc/src/main/java/org/postgresql/replication/PGReplicationStream.java
Hi,
Should "tread safe" be "thread safe"?
> Fix typo in PGReplicationStream.java

- pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java
Previously, and unknown cancel key might cause a NPE.
See https://github.com/pgjdbc/pgjdbc/issues/3530#issuecomment-2948773054
> fix: avoid NullPointerException when cancelling a query if cancel key is not known yet

- benchmarks/README.md
- benchmarks/src/jmh/java/org/postgresql/benchmark/statement/InsertBatch.java
> test: add bench for batch insert via unnest with arrays

- .github/workflows/release.yml
- build-logic/root-build/src/main/kotlin/build-logic.root-build.gradle.kts
This reverts commit ec5a0881ec2f835d66438efec1d713624634c3c4.
> Revert "fix: Update release plugin config to use .set(...) for props and inject nexus creds via gradle props"
